import { readFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { describe, expect, it } from "vitest"

const srcRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..")

describe("shipment surface for 28.0 and 90.0", () => {
  it("keeps /shipments job without legs or HBL", () => {
    const page = readFileSync(path.join(srcRoot, "features/shipment/catalog-page.tsx"), "utf8")
    const route = readFileSync(path.join(srcRoot, "routes/shipments.tsx"), "utf8")
    const nav = readFileSync(path.join(srcRoot, "components/layout/sidebar.tsx"), "utf8")
    const lists = readFileSync(path.join(srcRoot, "lib/business-lists.ts"), "utf8")
    const ops = readFileSync(path.join(srcRoot, "features/ops/ops-index.ts"), "utf8")
    expect(route).toContain("/shipments")
    expect(nav).toContain("/shipments")
    expect(lists).toContain("shipment")
    expect(ops).toContain("/shipments")
    expect(page).toContain('data-shipment="board"')
    expect(page).not.toContain("shipment_leg")
    expect(page).not.toContain("hbl")
    expect(page).not.toContain("acceptExtractionDraft")
  })

  it("records 90.0 as a live shipment table on /shipments", () => {
    const page = readFileSync(path.join(srcRoot, "features/shipment/catalog-page.tsx"), "utf8")
    const api = readFileSync(path.join(srcRoot, "lib/shipments-api.ts"), "utf8")
    const ops = readFileSync(path.join(srcRoot, "features/ops/ops-index.ts"), "utf8")
    expect(ops).toContain('"90.0": "/shipments"')
    expect(api).toContain("createShipment")
    expect(page).toContain("fetchShipments")
    expect(page).toContain("Zapisz zlecenie")
    expect(page).toContain("ShipmentStakeholderPanel")
    expect(page).toContain("BookingInstructionPanel")
    expect(page).toContain("StopPointPanel")
    expect(page).toContain("FleetResourcePanel")
    expect(ops).toContain('"151.0": "/shipments"')
    expect(ops).toContain('"194.0": "/shipments"')
    expect(ops).toContain('"204.0": "/shipments"')
    expect(ops).toContain('"210.0": "/shipments"')
    expect(page).toContain("Numer zlecenia shipment_ref")
    expect(page).toContain("Zlecenie główne parent_shipment_id")
    expect(page).toContain("Rodzaj relacji relation_kind")
    expect(page).not.toContain("qr")
    expect(page).not.toContain("parseFloat")
    const stop = readFileSync(path.join(srcRoot, "features/shipment/stop-panel.tsx"), "utf8")
    expect(stop).toContain("eta_physical")
    expect(stop).toContain("eta_legal")
    expect(stop).toContain("weight_kg")
    expect(stop).toContain("quantity")
    expect(stop).toContain("packaging_code")
    expect(stop).toContain("seal_in")
    expect(stop).toContain("seal_out")
    expect(stop).toContain("appointment_ref")
    expect(stop).toContain("waiting_free_minutes")
    expect(stop).toContain("waiting_started_at")
    expect(stop).toContain("pod_quality")
    expect(stop).not.toContain("Nie ETA")
    expect(stop).not.toContain("parseFloat")
    expect(ops).toContain('"247.0": "/shipments"')
    expect(ops).toContain('"248.0": "/shipments"')
    expect(ops).toContain('"249.0": "/shipments"')
    expect(ops).toContain('"250.0": "/shipments"')
    expect(ops).toContain('"251.0": "/shipments"')
    expect(ops).toContain('"252.0": "/shipments"')
    expect(ops).toContain('"253.0": "/shipments"')
    expect(ops).toContain('"254.0": "/shipments"')
    expect(ops).toContain('"255.0": "/shipments"')
    const fleet = readFileSync(path.join(srcRoot, "features/shipment/fleet-resource-panel.tsx"), "utf8")
    expect(fleet).toContain('data-resource="fleet"')
    expect(fleet).toContain("Zapisz zasób")
    expect(fleet).not.toContain("parseFloat")
    expect(page).toContain("TripRunPanel")
    expect(ops).toContain('"152.0": "/shipments"')
    const run = readFileSync(path.join(srcRoot, "features/shipment/trip-run-panel.tsx"), "utf8")
    expect(run).toContain('data-trip="run"')
    expect(run).toContain("Zapisz przejazd")
    expect(run).toContain("Money")
    expect(run).toContain("expected_buy")
    expect(run).toContain("planned_distance_km")
    expect(run).toContain("actual_distance_km")
    expect(run).toContain("subcontractor_party_id")
    expect(ops).toContain('"167.0": "/shipments"')
    expect(ops).toContain('"256.0": "/shipments"')
    expect(ops).toContain('"257.0": "/shipments"')
    expect(ops).toContain('"258.0": "/shipments"')
    expect(ops).toContain('"259.0": "/fleet"')
    expect(ops).toContain('"589.0": "/fleet"')
    expect(ops).toContain('"590.0": "/fleet"')
    expect(ops).toContain('"591.0": "/fleet"')
    expect(ops).toContain('"592.0": "/fleet"')
    expect(ops).toContain('"594.0": "/fleet"')
    expect(ops).toContain('"595.0": "/fleet"')
    expect(ops).toContain('"596.0": "/fleet"')
    expect(ops).toContain('"597.0": "/fleet"')
    expect(ops).toContain('"598.0": "/fleet"')
    expect(ops).toContain('"599.0": "/fleet"')
    const fleetPage = readFileSync(path.join(srcRoot, "features/shipment/fleet-page.tsx"), "utf8")
    expect(fleetPage).toContain('data-fleet="board"')
    expect(fleetPage).toContain("FleetResourcePanel")
    expect(fleetPage).toContain("ResourceDocumentPanel")
    expect(fleetPage).not.toContain("parseFloat")
    expect(fleet).toContain("capacity_kg")
    expect(fleet).toContain("capacity_ldm")
    expect(fleet).toContain("capacity_m3")
    expect(fleet).toContain("inventory_no")
    expect(fleet).toContain("adr_certified")
    expect(fleet).toContain("reefer")
    expect(fleet).toContain("tail_lift")
    expect(fleet).toContain("phone")
    expect(fleet).toContain("driver_card_no")
    expect(fleet).toContain("vehicle_profile")
    expect(fleet).not.toContain("parseFloat")
    expect(run).not.toContain("parseFloat")
    expect(page).toContain("IsoContainerPanel")
    expect(ops).toContain('"153.0": "/shipments"')
    const box = readFileSync(path.join(srcRoot, "features/shipment/iso-container-panel.tsx"), "utf8")
    expect(box).toContain('data-container="iso"')
    expect(box).toContain("Zapisz kontener")
    expect(box).not.toContain("parseFloat")
    expect(box).toContain("vgm_kg")
    expect(box).toContain("tare_kg")
    expect(box).toContain("pin_code")
    expect(box).toContain("payload_kg")
    expect(box).toContain("teu")
    expect(box).toContain("quantity")
    expect(box).toContain("weight_kg")
    expect(box).toContain("volume_m3")
    expect(box).toContain("pickup_date")
    expect(box).toContain("return_date")
    expect(box).toContain("gate_in_date")
    expect(box).toContain("delivery_date")
    expect(box).toContain("unload_date")
    expect(box).toContain("temp_min")
    expect(box).toContain("temp_max")
    expect(box).toContain("needs_external_power")
    expect(box).toContain("carrier_party_id")
    expect(box).toContain("container_release_party_id")
    expect(box).toContain("shipment_leg_id")
    expect(page).not.toContain("fetchQuotations")
    expect(page).not.toContain("quotationAcceptancePending")
    const panel = readFileSync(path.join(srcRoot, "features/shipment/shipment-stakeholder-panel.tsx"), "utf8")
    expect(panel).toContain('data-shipment-stakeholder="job"')
    expect(panel).toContain("Zapisz stronę")
    expect(panel).toContain("shipmentStakeholderBody")
    expect(panel).not.toContain("sold_to")
    expect(panel).not.toContain("parseFloat")
    const instruction = readFileSync(
      path.join(srcRoot, "features/shipment/booking-instruction-panel.tsx"),
      "utf8",
    )
    expect(ops).toContain('"148.0": "/shipments"')
    expect(instruction).toContain('data-booking-instruction="job"')
    expect(instruction).toContain("Zapisz instrukcję")
    expect(instruction).toContain("bookingInstructionBody")
    expect(instruction).not.toContain("sold_to")
    expect(instruction).not.toContain("parseFloat")
  })
})
