import { BUSINESS_LISTS } from "@/lib/business-lists"

export const ADMIN_REF_SURFACES = [
  "sidebar-density",
  "table-toolbar",
  "command-actions",
] as const

export const OPS_JOBS = [
  { route: BUSINESS_LISTS.extractions.route, label: "Ekstrakcje HITL", job: "extract / accept" },
  {
    route: BUSINESS_LISTS.financeBoard.route,
    label: "Tablica finansowa",
    job: "odczyt marży / NBP / limitu / recenzji",
  },
  {
    route: BUSINESS_LISTS.financeBoard.route,
    label: "Tablica — narracja",
    job: "zdania z pól SQL bez sumy",
  },
  {
    route: BUSINESS_LISTS.salesInvoice.route,
    label: "Faktury",
    job: "zapis faktury i numeru sesji",
  },
  {
    route: BUSINESS_LISTS.quoteInvoiceSettlement.route,
    label: "Rozliczenie wyceny",
    job: "zapis rozliczenia wyceny z fakturą",
  },
  {
    route: BUSINESS_LISTS.bankPayment.route,
    label: "Bank i płatności",
    job: "zapis płatności na rachunek",
  },
  {
    route: BUSINESS_LISTS.moneyCost.route,
    label: "Koszt pieniądza",
    job: "zapis kosztu pieniądza przy płatności",
  },
  {
    route: BUSINESS_LISTS.fxDifference.route,
    label: "Różnice kursowe",
    job: "zapis różnicy kursowej przy wycenie",
  },
  {
    route: BUSINESS_LISTS.cashFlow.route,
    label: "Przepływy",
    job: "zapis przepływu wyceny przy płatności",
  },
  {
    route: BUSINESS_LISTS.costToServe.route,
    label: "Koszt obsługi klienta",
    job: "zapis kosztu obsługi przy SOP",
  },
  {
    route: BUSINESS_LISTS.bookkeeping.route,
    label: "Księgowość",
    job: "zapis dekretu opłaty na fakturę",
  },
  {
    route: BUSINESS_LISTS.roadTransport.route,
    label: "Transport drogowy",
    job: "lokalizacje postal_zone i address",
  },
  {
    route: BUSINESS_LISTS.intermodalRail.route,
    label: "Kolej intermodalna",
    job: "porty z flagą rail",
  },
  {
    route: BUSINESS_LISTS.chinaRail.route,
    label: "Kolej z Chin",
    job: "porty CN z flagą rail",
  },
  {
    route: BUSINESS_LISTS.oceanLcl.route,
    label: "Drobnica morska",
    job: "porty z is_seaport",
  },
  {
    route: BUSINESS_LISTS.oceanBill.route,
    label: "Konosament LCL",
    job: "znacznik ocean_bill HBL/MBL bez PDF",
  },
  {
    route: BUSINESS_LISTS.consignment.route,
    label: "Przesyłki",
    job: "zapis consignment na zleceniu",
  },
  {
    route: BUSINESS_LISTS.palletBalance.route,
    label: "Saldo palet",
    job: "saldo pallet_balance Chep/LPR bez giełdy",
  },
  {
    route: BUSINESS_LISTS.documentTemplate.route,
    label: "Szablony wydruku",
    job: "katalog document_template layout bez PDF",
  },
  {
    route: BUSINESS_LISTS.rateCard.route,
    label: "Karty stawek",
    job: "katalog rate_card applies_when bez matching",
  },
  {
    route: BUSINESS_LISTS.chargeTemplate.route,
    label: "Szablony opłat",
    job: "katalog charge_template kodów bez exclusion",
  },
  {
    route: BUSINESS_LISTS.fuelIndex.route,
    label: "Indeksy paliwowe",
    job: "katalog fuel_index FSC/BAF/CAF bez mnożenia",
  },
  {
    route: BUSINESS_LISTS.localCharge.route,
    label: "Dopłaty lokalne",
    job: "katalog local_charge THC/ISPS bez warning",
  },
  {
    route: BUSINESS_LISTS.tenderDataRoom.route,
    label: "Pokoje danych",
    job: "NDA na tender bez extractu",
  },
  {
    route: BUSINESS_LISTS.tenderDeclineReason.route,
    label: "Tender decline",
    job: "katalog tender_decline_reason HITL",
  },
  {
    route: BUSINESS_LISTS.tenderMatrixCell.route,
    label: "Komórki matrycy",
    job: "kwota Decimal z P bez LLM",
  },
  {
    route: BUSINESS_LISTS.tenderPlaybook.route,
    label: "Playbook przetargu",
    job: "twierdzenie na tender bez extractu",
  },
  {
    route: BUSINESS_LISTS.tenderWinLoss.route,
    label: "Wynik przetargu",
    job: "werdykt win/loss bez extractu",
  },
  {
    route: BUSINESS_LISTS.tenderConsortiumMember.route,
    label: "Konsorcjum przetargu",
    job: "fotel lead/member bez extractu",
  },
  {
    route: BUSINESS_LISTS.tenderRfpIntake.route,
    label: "Przyjęcie RFP",
    job: "HITL przyjęcie RFP bez zapisu z LLM",
  },
  {
    route: BUSINESS_LISTS.tenderProspect.route,
    label: "Prospekt przetargu",
    job: "HITL outreach firmy bez scrape",
  },
  {
    route: BUSINESS_LISTS.tenderBidStance.route,
    label: "Udział w przetargu",
    job: "HITL bid/no-bid bez auto-award",
  },
  {
    route: BUSINESS_LISTS.tenderCarbonMark.route,
    label: "Ślad węglowy przetargu",
    job: "HITL declared/exempt bez kalkulatora kg",
  },
  {
    route: BUSINESS_LISTS.lanePattern.route,
    label: "Wzorzec korytarza",
    job: "HITL para UN/LOCODE bez circle_sim",
  },
  {
    route: BUSINESS_LISTS.kreptdLicence.route,
    label: "Licencja KREPTD",
    job: "HITL numer licencji bez scrape",
  },
  {
    route: BUSINESS_LISTS.monitoringScheme.route,
    label: "Schemat monitoringu",
    job: "HITL katalog schematu bez SENT XML",
  },
  {
    route: BUSINESS_LISTS.partyDocument.route,
    label: "Dokument kontrahenta",
    job: "HITL rodzaj dokumentu bez 409 na zleceniu",
  },
  {
    route: BUSINESS_LISTS.cashDiscount.route,
    label: "Skonto",
    job: "HITL rodzaj skonta bez kwoty",
  },
  {
    route: BUSINESS_LISTS.carbonMethod.route,
    label: "Metodyka CO₂",
    job: "HITL GLEC/GHG bez kalkulatora kg",
  },
  {
    route: BUSINESS_LISTS.predictionLedger.route,
    label: "Ledger predykcji",
    job: "HITL przedział + CRPS bez silnika",
  },
  {
    route: BUSINESS_LISTS.weatherObservation.route,
    label: "Pogoda",
    job: "HITL warunek + UN/LOCODE bez Open-Meteo",
  },
  {
    route: BUSINESS_LISTS.freeTimeClock.route,
    label: "Zegar DD",
    job: "HITL rodzaj + dni wolne bez countdown",
  },
  {
    route: BUSINESS_LISTS.telematicsConnector.route,
    label: "Konektor GPS",
    job: "HITL reżim + dostawca bez live poll",
  },
  {
    route: BUSINESS_LISTS.telematicsDevice.route,
    label: "Urządzenie telematyczne",
    job: "katalog telematics_device HITL",
  },
  {
    route: BUSINESS_LISTS.towerImpact.route,
    label: "Skutek wieży",
    job: "HITL etap łańcucha bez scoringu",
  },
  {
    route: BUSINESS_LISTS.twinKind.route,
    label: "Rodzaj bliźniaka",
    job: "katalog twin_kind HITL",
  },
  {
    route: BUSINESS_LISTS.twinMark.route,
    label: "Bliźniak",
    job: "HITL 8 rodzajów bez fizyki",
  },
  {
    route: BUSINESS_LISTS.warRoomMark.route,
    label: "Sala kryzysowa",
    job: "HITL incydent bez scalania alertów",
  },
  {
    route: BUSINESS_LISTS.memoryEdge.route,
    label: "Krawędź pamięci",
    job: "HITL rodzaj krawędzi bez wyszukiwania stawek",
  },
  {
    route: BUSINESS_LISTS.executiveMark.route,
    label: "Pytanie zarządu",
    job: "HITL rodzaj pytania bez sumy z modelu",
  },
  {
    route: BUSINESS_LISTS.rankMark.route,
    label: "Oś rankingu",
    job: "HITL oś zakupu bez auto-award",
  },
  {
    route: BUSINESS_LISTS.tenderAwardReview.route,
    label: "Cztery oczy nagrody",
    job: "HITL przegląd nagrody bez auto-award",
  },
  {
    route: BUSINESS_LISTS.tenderTedNotice.route,
    label: "Ogłoszenie TED",
    job: "HITL numer TED bez scrape",
  },
  {
    route: BUSINESS_LISTS.tenderLane.route,
    label: "Korytarze przetargu",
    job: "para UN/LOCODE na partii bez rundy",
  },
  {
    route: BUSINESS_LISTS.tenderLot.route,
    label: "Partie przetargu",
    job: "kod partii na tender bez korytarza",
  },
  {
    route: BUSINESS_LISTS.tenderRound.route,
    label: "Rundy przetargu",
    job: "numer rundy na tender bez data room",
  },
  {
    route: BUSINESS_LISTS.tenderQuote.route,
    label: "Oferty przetargowe",
    job: "ważność i limit orderów bez auto-award",
  },
  {
    route: BUSINESS_LISTS.tender.route,
    label: "Przetargi",
    job: "nagłówek tender sell/buy bez auto-award",
  },
  {
    route: BUSINESS_LISTS.airFreight.route,
    label: "Lotniczy",
    job: "lotniska z flagą airport",
  },
  {
    route: BUSINESS_LISTS.groupageLines.route,
    label: "Linie drobnicy",
    job: "katalog groupage_line cutoff i ISODOW",
  },
  {
    route: BUSINESS_LISTS.groupageTariff.route,
    label: "Cennik drobnicy",
    job: "próg groupage_tariff na strefie bez silnika",
  },
  {
    route: BUSINESS_LISTS.shipmentPackage.route,
    label: "Paczki",
    job: "skan shipment_package QR Omni i stop",
  },
  {
    route: BUSINESS_LISTS.dockAppointment.route,
    label: "Awizacje doku",
    job: "okno dock_appointment na stop magazynu",
  },
  {
    route: BUSINESS_LISTS.codInstruction.route,
    label: "Pobranie COD",
    job: "znacznik cod_instruction bez kwoty",
  },
  {
    route: BUSINESS_LISTS.sanctions.route,
    label: "Sankcje",
    job: "aktywni kontrahenci tax_id i kraj",
  },
  {
    route: BUSINESS_LISTS.gdpr.route,
    label: "RODO",
    job: "wniosek i usunięcie katalogu",
  },
  {
    route: BUSINESS_LISTS.generalAverageMark.route,
    label: "General average",
    job: "katalog general_average_mark HITL",
  },
  {
    route: BUSINESS_LISTS.aiCopilot.route,
    label: "Propozycje AI",
    job: "szkice HITL pending",
  },
  {
    route: BUSINESS_LISTS.aiCopilot.route,
    label: "Szkice po SOP",
    job: "odczyt blocks_auto przy mail_draft",
  },
  {
    route: BUSINESS_LISTS.observability.route,
    label: "Obserwowalność",
    job: "status API fetchHealth",
  },
  {
    route: BUSINESS_LISTS.extractionQuality.route,
    label: "Jakość ekstrakcji",
    job: "szkice z unparsed_regions",
  },
  {
    route: BUSINESS_LISTS.tenantRollout.route,
    label: "Wdrożenie",
    job: "klucz default_currency z ustawień",
  },
  {
    route: BUSINESS_LISTS.mailIntegration.route,
    label: "Poczta",
    job: "znane adresy i inbound_message fixture",
  },
  {
    route: BUSINESS_LISTS.mailIntegration.route,
    label: "Poczta — UN",
    job: "Podpnij UN na zapytaniu",
  },
  {
    route: BUSINESS_LISTS.operatorNotice.route,
    label: "Powiadomienia",
    job: "HITL pending i wyceny pending",
  },
  {
    route: BUSINESS_LISTS.operatorNotice.route,
    label: "Powiadomienia — filtr",
    job: "filtr kind na tablicy 27.0",
  },
  {
    route: BUSINESS_LISTS.shipment.route,
    label: "Zlecenia",
    job: "wyceny z party_id jako praca handlowa",
  },
  {
    route: BUSINESS_LISTS.tracking.route,
    label: "Tracking",
    job: "lane POL/POD z wyceny",
  },
  {
    route: BUSINESS_LISTS.trackingConsent.route,
    label: "Zgoda na śledzenie",
    job: "katalog tracking_consent HITL",
  },
  {
    route: BUSINESS_LISTS.operationalException.route,
    label: "Wyjątki",
    job: "wyceny z party bez pełnego POL/POD",
  },
  {
    route: BUSINESS_LISTS.cargoClaim.route,
    label: "Reklamacje ładunku",
    job: "zapis reklamacji na zleceniu",
  },
  {
    route: BUSINESS_LISTS.fraudFlag.route,
    label: "Oszustwo",
    job: "zapis flagi oszustwa na kontrahencie",
  },
  {
    route: BUSINESS_LISTS.watchtower.route,
    label: "Wieża",
    job: "wyjątki i pending S11 plus leniwy panel mapy",
  },
  {
    route: BUSINESS_LISTS.watchtower.route,
    label: "Wieża — szkice",
    job: "odczyt mail_draft na wieży",
  },
  {
    route: BUSINESS_LISTS.watchtower.route,
    label: "Wieża — liczniki",
    job: "podsumowanie wyjątków, pending i szkiców",
  },
  {
    route: BUSINESS_LISTS.shipmentDocument.route,
    label: "Dokumenty zlecenia",
    job: "source_ref wycen z party_id",
  },
  {
    route: BUSINESS_LISTS.ediMessage.route,
    label: "EDI",
    job: "zapis edi_message na zleceniu",
  },
  { route: BUSINESS_LISTS.chargeCodes.route, label: "Kody opłat", job: "katalog charge_code" },
  {
    route: BUSINESS_LISTS.commodityCodes.route,
    label: "Kody towarowe",
    job: "katalog commodity_code",
  },
  {
    route: BUSINESS_LISTS.dangerousGoods.route,
    label: "Towary niebezpieczne",
    job: "katalog dangerous_good UN/IMDG",
  },
  {
    route: BUSINESS_LISTS.networks.route,
    label: "Sieci",
    job: "katalog network per tenant",
  },
  {
    route: BUSINESS_LISTS.nbpRates.route,
    label: "Kursy NBP",
    job: "katalog nbp_rate tabeli A",
  },
  { route: BUSINESS_LISTS.rateLines.route, label: "Stawki kupna", job: "rate_line + source_ref" },
  { route: BUSINESS_LISTS.charges.route, label: "Opłaty", job: "buy+sell / marża" },
  {
    route: BUSINESS_LISTS.channelQuotes.route,
    label: "Oferty kanału",
    job: "katalog channel_quote + resolve",
  },
  {
    route: BUSINESS_LISTS.quotations.route,
    label: "Wyceny",
    job: "SQL z rate_line + kanał + zapytania",
  },
  { route: BUSINESS_LISTS.organizationSettings.route, label: "Ustawienia", job: "config jako dane" },
  { route: BUSINESS_LISTS.ports.route, label: "Porty", job: "katalog UN/LOCODE + resolve" },
  {
    route: BUSINESS_LISTS.portSurcharges.route,
    label: "Opłaty portowe",
    job: "katalog port_surcharge + resolve",
  },
  {
    route: BUSINESS_LISTS.locations.route,
    label: "Lokalizacje",
    job: "strefy taryfowe + resolve kodu",
  },
  {
    route: BUSINESS_LISTS.terminals.route,
    label: "Terminale",
    job: "katalog ISPS + resolve",
  },
  {
    route: BUSINESS_LISTS.parties.route,
    label: "Kontrahenci",
    job: "katalog party + resolve tax_id / mail",
  },
  {
    route: BUSINESS_LISTS.partyScorecards.route,
    label: "Karty wyników",
    job: "snapshot party_scorecard",
  },
  {
    route: BUSINESS_LISTS.partyScorecards.route,
    label: "Karty — decyzje oferty",
    job: "odczyt przyjętych i odrzuconych wycen",
  },
  {
    route: BUSINESS_LISTS.customerSops.route,
    label: "Procedury klienta",
    job: "katalog customer_sop + zatwierdzenie",
  },
  {
    route: BUSINESS_LISTS.creditReviews.route,
    label: "Recenzje kredytowe",
    job: "katalog credit_review + resolve",
  },
  {
    route: BUSINESS_LISTS.operatorDecisions.route,
    label: "Decyzje",
    job: "szyna operator_decision accept/reject",
  },
  {
    route: BUSINESS_LISTS.operatorDecisions.route,
    label: "Decyzje — Zmień",
    job: "werdykt changed z lock_version",
  },
  {
    route: BUSINESS_LISTS.outboxEvents.route,
    label: "Outbox",
    job: "zdarzenie inbound_message_saved",
  },
  {
    route: BUSINESS_LISTS.entityEvents.route,
    label: "Zdarzenia podmiotu",
    job: "ledger entity_event append-only",
  },
  {
    route: BUSINESS_LISTS.fleet.route,
    label: "Flota",
    job: "zapis zasobu pojazdu/kierowcy/naczepy",
  },
  {
    route: BUSINESS_LISTS.planning.route,
    label: "Planowanie",
    job: "leniwy overlay etykiet trip",
  },
  {
    route: BUSINESS_LISTS.taskTemplate.route,
    label: "Szablon zadania",
    job: "katalog task_template HITL",
  },
  {
    route: BUSINESS_LISTS.planSnapshot.route,
    label: "Migawka planu",
    job: "katalog plan_snapshot HITL",
  },
  {
    route: BUSINESS_LISTS.circleSim.route,
    label: "Kółko",
    job: "katalog circle_sim HITL",
  },
  {
    route: BUSINESS_LISTS.laneKm.route,
    label: "Km ładowny",
    job: "katalog lane_km HITL",
  },
  {
    route: BUSINESS_LISTS.lcChecklist.route,
    label: "Checklista LC",
    job: "katalog lc_checklist HITL",
  },
  {
    route: BUSINESS_LISTS.nctsDraft.route,
    label: "Szkic NCTS",
    job: "katalog ncts_draft HITL",
  },
  {
    route: BUSINESS_LISTS.oogMark.route,
    label: "Znacznik OOG",
    job: "katalog oog_mark HITL",
  },
  {
    route: BUSINESS_LISTS.oogPermitMark.route,
    label: "Zezwolenie OOG",
    job: "katalog oog_permit_mark HITL",
  },
  {
    route: BUSINESS_LISTS.lclConsoleMark.route,
    label: "Konsola LCL",
    job: "katalog lcl_console_mark HITL",
  },
  {
    route: BUSINESS_LISTS.nacMark.route,
    label: "NAC i agent nominowany",
    job: "katalog nac_mark HITL",
  },
  {
    route: BUSINESS_LISTS.silkCorridorMark.route,
    label: "Jedwabny Szlak",
    job: "katalog silk_corridor_mark HITL",
  },
  {
    route: BUSINESS_LISTS.factoringConnector.route,
    label: "Faktoring — partner",
    job: "katalog factoring_connector HITL",
  },
  {
    route: BUSINESS_LISTS.poFinancingMark.route,
    label: "Finansowanie zamówienia",
    job: "katalog po_financing_mark HITL",
  },
  {
    route: BUSINESS_LISTS.wmsFlowMark.route,
    label: "Przepływ WMS",
    job: "katalog wms_flow_mark HITL",
  },
  {
    route: BUSINESS_LISTS.rfidMark.route,
    label: "RFID magazyn",
    job: "katalog rfid_mark HITL",
  },
  {
    route: BUSINESS_LISTS.inventoryFinanceMark.route,
    label: "Zapas finansowy",
    job: "katalog inventory_finance_mark HITL",
  },
  {
    route: BUSINESS_LISTS.inventoryCollateralMark.route,
    label: "Zabezpieczenie na towarze",
    job: "katalog inventory_collateral_mark HITL",
  },
  {
    route: BUSINESS_LISTS.opsRoomMark.route,
    label: "Sala operacyjna",
    job: "katalog ops_room_mark HITL",
  },
  {
    route: BUSINESS_LISTS.lineImpactLayerMark.route,
    label: "Warstwa liczona linii",
    job: "katalog line_impact_layer_mark HITL",
  },
  {
    route: BUSINESS_LISTS.productTicketMark.route,
    label: "Ticket produktu",
    job: "katalog product_ticket_mark HITL",
  },
  {
    route: BUSINESS_LISTS.riskRegisterMark.route,
    label: "Rejestr ryzyka",
    job: "katalog risk_register_mark HITL",
  },
  {
    route: BUSINESS_LISTS.automationBiasMark.route,
    label: "Automation bias",
    job: "katalog automation_bias_mark HITL",
  },
  {
    route: BUSINESS_LISTS.l3GateMark.route,
    label: "Brama L3",
    job: "katalog l3_gate_mark HITL",
  },
  {
    route: BUSINESS_LISTS.styleCascadeMark.route,
    label: "Kaskada stylu",
    job: "katalog style_cascade_mark HITL",
  },
  {
    route: BUSINESS_LISTS.styleFidelityMark.route,
    label: "STYLE FIDELITY",
    job: "katalog style_fidelity_mark HITL",
  },
  {
    route: BUSINESS_LISTS.qualityDescentMark.route,
    label: "Zejście jakości",
    job: "katalog quality_descent_mark HITL",
  },
  {
    route: BUSINESS_LISTS.fieldConfidenceMark.route,
    label: "Pewność per pole",
    job: "katalog field_confidence_mark HITL",
  },
  {
    route: BUSINESS_LISTS.complianceProgramMark.route,
    label: "Program zgodności",
    job: "katalog compliance_program_mark HITL",
  },
  {
    route: BUSINESS_LISTS.loadOrderMark.route,
    label: "Kolejność załadunku",
    job: "katalog load_order_mark HITL",
  },
  {
    route: BUSINESS_LISTS.loadPlanMark.route,
    label: "Znacznik planu załadunku",
    job: "katalog load_plan_mark HITL",
  },
  {
    route: BUSINESS_LISTS.routePlanMark.route,
    label: "Znacznik planu trasy",
    job: "katalog route_plan_mark HITL",
  },
  {
    route: BUSINESS_LISTS.cmmsMark.route,
    label: "Znacznik CMMS",
    job: "katalog cmms_mark HITL",
  },
  {
    route: BUSINESS_LISTS.legalHoldMark.route,
    label: "Znacznik legal hold",
    job: "katalog legal_hold_mark HITL",
  },
  {
    route: BUSINESS_LISTS.companyMark.route,
    label: "Znacznik spółki",
    job: "katalog company_mark HITL",
  },
  {
    route: BUSINESS_LISTS.bondedMark.route,
    label: "Znacznik bonded",
    job: "katalog bonded_mark HITL",
  },
  {
    route: BUSINESS_LISTS.filingSchemeMark.route,
    label: "Schemat składania",
    job: "katalog filing_scheme_mark HITL",
  },
  {
    route: BUSINESS_LISTS.ediMapMark.route,
    label: "Mapa EDI",
    job: "katalog edi_map_mark HITL",
  },
  {
    route: BUSINESS_LISTS.aeoDossierMark.route,
    label: "Dossier AEO",
    job: "katalog aeo_dossier_mark HITL",
  },
  {
    route: BUSINESS_LISTS.abandonedRtoMark.route,
    label: "abandoned/RTO",
    job: "katalog abandoned_rto_mark HITL",
  },
  {
    route: BUSINESS_LISTS.yardMark.route,
    label: "Yard / waga / EIR",
    job: "katalog yard_mark HITL",
  },
  {
    route: BUSINESS_LISTS.billingMark.route,
    label: "Billing SaaS Omni",
    job: "katalog billing_mark HITL",
  },
  {
    route: BUSINESS_LISTS.registryPollMark.route,
    label: "Poll rejestrów",
    job: "katalog registry_poll_mark HITL",
  },
  {
    route: BUSINESS_LISTS.workingCapitalMark.route,
    label: "Working capital",
    job: "katalog working_capital_mark HITL",
  },
  {
    route: BUSINESS_LISTS.makeOrBuyMark.route,
    label: "Make-or-buy",
    job: "katalog make_or_buy_mark HITL",
  },
  {
    route: BUSINESS_LISTS.costAllocationMark.route,
    label: "Cost allocation",
    job: "katalog cost_allocation_mark HITL",
  },
  {
    route: BUSINESS_LISTS.cargoCoverMark.route,
    label: "Cargo cover",
    job: "katalog cargo_cover_mark HITL",
  },
  {
    route: BUSINESS_LISTS.sanctionsMark.route,
    label: "Sanctions",
    job: "katalog sanctions_mark HITL",
  },
  {
    route: BUSINESS_LISTS.subcontractEdgeMark.route,
    label: "Subcontract edge",
    job: "katalog subcontract_edge_mark HITL",
  },
  {
    route: BUSINESS_LISTS.switchBlLoiMark.route,
    label: "switch BL/LOI",
    job: "katalog switch_bl_loi_mark HITL",
  },
  {
    route: BUSINESS_LISTS.scheduleExceptionMark.route,
    label: "Schedule exception",
    job: "katalog schedule_exception_mark HITL",
  },
  {
    route: BUSINESS_LISTS.cutoffMark.route,
    label: "Cutoff",
    job: "katalog cutoff_mark HITL",
  },
  {
    route: BUSINESS_LISTS.timeToFixMark.route,
    label: "TIME-TO-FIX",
    job: "katalog time_to_fix_mark HITL",
  },
  {
    route: BUSINESS_LISTS.whatIfMark.route,
    label: "What-if",
    job: "katalog what_if_mark HITL",
  },
  {
    route: BUSINESS_LISTS.cabotageMark.route,
    label: "Kabotaż",
    job: "katalog cabotage_mark HITL",
  },
  {
    route: BUSINESS_LISTS.combinedTransportMark.route,
    label: "Combined transport",
    job: "katalog combined_transport_mark HITL",
  },
  {
    route: BUSINESS_LISTS.ferryArt9Mark.route,
    label: "Ferry art. 9",
    job: "katalog ferry_art9_mark HITL",
  },
  {
    route: BUSINESS_LISTS.ferryBookingMark.route,
    label: "Rezerwacja promu",
    job: "katalog ferry_booking_mark HITL",
  },
  {
    route: BUSINESS_LISTS.fuelAnomalyMark.route,
    label: "Fuel anomaly",
    job: "katalog fuel_anomaly_mark HITL",
  },
  {
    route: BUSINESS_LISTS.fleetCostMark.route,
    label: "Fleet cost",
    job: "katalog fleet_cost_mark HITL",
  },
  {
    route: BUSINESS_LISTS.binPackMark.route,
    label: "Bin-pack",
    job: "katalog bin_pack_mark HITL",
  },
  {
    route: BUSINESS_LISTS.palletPoolMark.route,
    label: "Pallet pool",
    job: "katalog pallet_pool_mark HITL",
  },
  {
    route: BUSINESS_LISTS.eCmrMark.route,
    label: "E-CMR / eFTI",
    job: "katalog e_cmr_mark HITL",
  },
  {
    route: BUSINESS_LISTS.eDeliveryMark.route,
    label: "E-Doręczenia",
    job: "katalog e_delivery_mark HITL",
  },
  {
    route: BUSINESS_LISTS.peppolMark.route,
    label: "Peppol / MPP",
    job: "katalog peppol_mark HITL",
  },
  {
    route: BUSINESS_LISTS.phytoAtaMark.route,
    label: "phyto/ATA",
    job: "katalog phyto_ata_mark HITL",
  },
  {
    route: BUSINESS_LISTS.sidImportMark.route,
    label: "Import SID",
    job: "katalog sid_import_mark HITL",
  },
  {
    route: BUSINESS_LISTS.integrationHubMark.route,
    label: "Integration Hub",
    job: "katalog integration_hub_mark HITL",
  },
  {
    route: BUSINESS_LISTS.webhookOutboxMark.route,
    label: "Webhook outbox",
    job: "katalog webhook_outbox_mark HITL",
  },
  {
    route: BUSINESS_LISTS.partnerExchangeMark.route,
    label: "Giełda partnerska",
    job: "katalog partner_exchange_mark HITL",
  },
  {
    route: BUSINESS_LISTS.regulatoryRadarMark.route,
    label: "Regulatory radar",
    job: "katalog regulatory_radar_mark HITL",
  },
  {
    route: BUSINESS_LISTS.isoNis2Mark.route,
    label: "ISO/NIS2 ops",
    job: "katalog iso_nis2_mark HITL",
  },
  {
    route: BUSINESS_LISTS.offboardingMark.route,
    label: "Offboarding",
    job: "katalog offboarding_mark HITL",
  },
  {
    route: BUSINESS_LISTS.jitJisMark.route,
    label: "JIT/JIS",
    job: "katalog jit_jis_mark HITL",
  },
  {
    route: BUSINESS_LISTS.vdaOdetteMark.route,
    label: "VDA/Odette",
    job: "katalog vda_odette_mark HITL",
  },
  {
    route: BUSINESS_LISTS.inventoryPositionMark.route,
    label: "Inventory position",
    job: "katalog inventory_position_mark HITL",
  },
  {
    route: BUSINESS_LISTS.fairShareMark.route,
    label: "Fair share",
    job: "katalog fair_share_mark HITL",
  },
  {
    route: BUSINESS_LISTS.mqcMark.route,
    label: "MQC",
    job: "katalog mqc_mark HITL",
  },
  {
    route: BUSINESS_LISTS.eccnMark.route,
    label: "ECCN",
    job: "katalog eccn_mark HITL",
  },
  {
    route: BUSINESS_LISTS.eur1AtrMark.route,
    label: "EUR.1/ATR",
    job: "katalog eur1_atr_mark HITL",
  },
  {
    route: BUSINESS_LISTS.erpConnector.route,
    label: "Konektor Optima",
    job: "katalog erp_connector HITL",
  },
  {
    route: BUSINESS_LISTS.idpConnector.route,
    label: "Konektor Auth0",
    job: "katalog idp_connector HITL",
  },
  {
    route: BUSINESS_LISTS.customerContract.route,
    label: "Umowa klienta",
    job: "katalog customer_contract HITL",
  },
  {
    route: BUSINESS_LISTS.tenantContractKek.route,
    label: "Znacznik KEK",
    job: "katalog tenant_contract_kek HITL",
  },
  {
    route: BUSINESS_LISTS.visibilityConnector.route,
    label: "Konektor widoczności",
    job: "katalog visibility_connector HITL",
  },
  {
    route: BUSINESS_LISTS.purchaseOrder.route,
    label: "Zamówienie zakupu",
    job: "katalog purchase_order HITL",
  },
  {
    route: BUSINESS_LISTS.poLine.route,
    label: "Linia zamówienia",
    job: "katalog po_line HITL",
  },
  {
    route: BUSINESS_LISTS.asn.route,
    label: "Awizo wysyłki",
    job: "katalog asn HITL",
  },
  {
    route: BUSINESS_LISTS.routingGuide.route,
    label: "Przewodnik routingu",
    job: "katalog routing_guide HITL",
  },
  {
    route: BUSINESS_LISTS.routingGuideEnforcement.route,
    label: "Egzekucja przewodnika",
    job: "katalog routing_guide_enforcement HITL",
  },
  {
    route: BUSINESS_LISTS.routingGuideMatch.route,
    label: "Dopasowanie przewodnika",
    job: "katalog routing_guide_match HITL",
  },
  {
    route: BUSINESS_LISTS.otifMark.route,
    label: "Znacznik OTIF",
    job: "katalog otif_mark HITL",
  },
  {
    route: BUSINESS_LISTS.sapConnector.route,
    label: "Konektor SAP/Oracle",
    job: "katalog sap_connector HITL",
  },
  {
    route: BUSINESS_LISTS.capaMark.route,
    label: "Znacznik CAPA",
    job: "katalog capa_mark HITL",
  },
  {
    route: BUSINESS_LISTS.slaClause.route,
    label: "Klauzula SLA",
    job: "katalog sla_clause HITL",
  },
  {
    route: BUSINESS_LISTS.delayForecast.route,
    label: "Prognoza opóźnienia",
    job: "katalog delay_forecast HITL",
  },
  {
    route: BUSINESS_LISTS.demandSnapshotMark.route,
    label: "Demand snapshot",
    job: "katalog demand_snapshot_mark HITL",
  },
  {
    route: BUSINESS_LISTS.diversionMark.route,
    label: "Diversion",
    job: "katalog diversion_mark HITL",
  },
  {
    route: BUSINESS_LISTS.spotContractMark.route,
    label: "Spot / contract",
    job: "katalog spot_contract_mark HITL",
  },
  {
    route: BUSINESS_LISTS.bidDecisionMark.route,
    label: "Bid decision",
    job: "katalog bid_decision_mark HITL",
  },
  {
    route: BUSINESS_LISTS.quoteCurrencyMark.route,
    label: "Quote currency",
    job: "katalog quote_currency_mark HITL",
  },
  {
    route: BUSINESS_LISTS.quoteValidityMark.route,
    label: "Quote validity",
    job: "katalog quote_validity_mark HITL",
  },
  {
    route: BUSINESS_LISTS.suggestionLedger.route,
    label: "Ledger podpowiedzi",
    job: "katalog suggestion_ledger HITL",
  },
  {
    route: BUSINESS_LISTS.outcomeLedger.route,
    label: "Ledger wyniku",
    job: "katalog outcome_ledger HITL",
  },
  {
    route: BUSINESS_LISTS.intervalScore.route,
    label: "Wynik przedziału",
    job: "odczyt MAE/CRPS ze złączenia",
  },
  {
    route: BUSINESS_LISTS.versionScore.route,
    label: "Wynik wersji",
    job: "średnie MAE/CRPS per model_version",
  },
  {
    route: BUSINESS_LISTS.versionWindow.route,
    label: "Wynik okna wersji",
    job: "średnie MAE/CRPS per model_version i dzień UTC",
  },
  {
    route: BUSINESS_LISTS.counterfactualRun.route,
    label: "Przebieg what-if",
    job: "katalog counterfactual_run HITL",
  },
  {
    route: BUSINESS_LISTS.benefitLedger.route,
    label: "Ledger oszczędności",
    job: "katalog benefit_ledger HITL",
  },
  {
    route: BUSINESS_LISTS.suggestionKind.route,
    label: "Rodzaj podpowiedzi",
    job: "katalog suggestion_kind HITL",
  },
  {
    route: BUSINESS_LISTS.outcomeKind.route,
    label: "Rodzaj wyniku",
    job: "katalog outcome_kind HITL",
  },
  {
    route: BUSINESS_LISTS.autonomyLevel.route,
    label: "Poziom autonomii",
    job: "katalog autonomy_level HITL",
  },
  {
    route: BUSINESS_LISTS.csrdMark.route,
    label: "CSRD",
    job: "katalog csrd_mark HITL",
  },
  {
    route: BUSINESS_LISTS.airRa3Mark.route,
    label: "Air RA3",
    job: "katalog air_ra3_mark HITL",
  },
  {
    route: BUSINESS_LISTS.railCimMark.route,
    label: "Rail CIM",
    job: "katalog rail_cim_mark HITL",
  },
  {
    route: BUSINESS_LISTS.railUicMark.route,
    label: "Rail UIC",
    job: "katalog rail_uic_mark HITL",
  },
  {
    route: BUSINESS_LISTS.oceanAllianceMark.route,
    label: "Ocean alliance",
    job: "katalog ocean_alliance_mark HITL",
  },
  {
    route: BUSINESS_LISTS.oceanFeederMark.route,
    label: "Ocean feeder",
    job: "katalog ocean_feeder_mark HITL",
  },
  {
    route: BUSINESS_LISTS.chassisMark.route,
    label: "Chassis",
    job: "katalog chassis_mark HITL",
  },
  {
    route: BUSINESS_LISTS.lineImpactMark.route,
    label: "Skutek linii",
    job: "katalog line_impact_mark HITL",
  },
  {
    route: BUSINESS_LISTS.threeWayMark.route,
    label: "Znacznik 3-way",
    job: "katalog three_way_mark HITL",
  },
  {
    route: BUSINESS_LISTS.reeferMark.route,
    label: "Reefer",
    job: "katalog reefer_mark HITL",
  },
  {
    route: BUSINESS_LISTS.emptyDepotMark.route,
    label: "Empty / depot",
    job: "katalog empty_depot_mark HITL",
  },

  {
    route: BUSINESS_LISTS.nvoccMark.route,
    label: "NVOCC",
    job: "katalog nvocc_mark HITL",
  },
  {
    route: BUSINESS_LISTS.multiManningMark.route,
    label: "Multi-manning",
    job: "katalog multi_manning_mark HITL",
  },
  {
    route: BUSINESS_LISTS.postingMark.route,
    label: "Posting",
    job: "katalog posting_mark HITL",
  },
  {
    route: BUSINESS_LISTS.tachoOfficeMark.route,
    label: "Tacho Office",
    job: "katalog tacho_office_mark HITL",
  },
  {
    route: BUSINESS_LISTS.tachoPlanMark.route,
    label: "Tacho w planie",
    job: "katalog tacho_plan_mark HITL",
  },
  {
    route: BUSINESS_LISTS.lezMark.route,
    label: "LEZ / zakazy",
    job: "katalog lez_mark HITL",
  },
  {
    route: BUSINESS_LISTS.labelParkingMark.route,
    label: "LABEL parking",
    job: "katalog label_parking_mark HITL",
  },
  {
    route: BUSINESS_LISTS.abSusMark.route,
    label: "A/B+SUS",
    job: "katalog ab_sus_mark HITL",
  },
  {
    route: BUSINESS_LISTS.termsAiMark.route,
    label: "Terms AI",
    job: "katalog terms_ai_mark HITL",
  },
  {
    route: BUSINESS_LISTS.funnelMark.route,
    label: "X7 lejek",
    job: "katalog funnel_mark HITL",
  },
  {
    route: BUSINESS_LISTS.mailAcceptMark.route,
    label: "Accept z maila",
    job: "katalog mail_accept_mark HITL",
  },
  {
    route: BUSINESS_LISTS.roleViewMark.route,
    label: "Widok roli",
    job: "katalog role_view_mark HITL",
  },
  {
    route: BUSINESS_LISTS.ragSopMark.route,
    label: "Zakres RAG",
    job: "katalog rag_sop_mark HITL",
  },
  {
    route: BUSINESS_LISTS.copyBanMark.route,
    label: "Zakaz copy claimów",
    job: "katalog copy_ban_mark HITL",
  },
  {
    route: BUSINESS_LISTS.erruMark.route,
    label: "Sprawdzenie ERRU",
    job: "katalog erru_mark HITL",
  },
  {
    route: BUSINESS_LISTS.mobileClientMark.route,
    label: "Klient mobilny",
    job: "katalog mobile_client_mark HITL",
  },
  {
    route: BUSINESS_LISTS.jobMetricMark.route,
    label: "Metryka jobu",
    job: "katalog job_metric_mark HITL",
  },
  {
    route: BUSINESS_LISTS.demoGpsMark.route,
    label: "Demo GPS",
    job: "katalog demo_gps_mark HITL",
  },
  {
    route: BUSINESS_LISTS.demoWipeMark.route,
    label: "Wipe demo",
    job: "katalog demo_wipe_mark HITL",
  },
  {
    route: BUSINESS_LISTS.demoSimMark.route,
    label: "Demo sim",
    job: "katalog demo_sim_mark HITL",
  },
  {
    route: BUSINESS_LISTS.poPlantMark.route,
    label: "PO plant",
    job: "katalog po_plant_mark HITL",
  },
  {
    route: BUSINESS_LISTS.poSkuMark.route,
    label: "PO SKU",
    job: "katalog po_sku_mark HITL",
  },
  {
    route: BUSINESS_LISTS.poBatchMark.route,
    label: "PO batch",
    job: "katalog po_batch_mark HITL",
  },
  {
    route: BUSINESS_LISTS.unSegregationMark.route,
    label: "Segregacja UN",
    job: "katalog un_segregation_mark HITL",
  },
  {
    route: BUSINESS_LISTS.dualLedgerMark.route,
    label: "Dual ledger",
    job: "katalog dual_ledger_mark HITL",
  },
  {
    route: BUSINESS_LISTS.namedPlaceMark.route,
    label: "Miejsce nazwane",
    job: "katalog named_place_mark HITL",
  },
  {
    route: BUSINESS_LISTS.slotGuaranteeMark.route,
    label: "Stance slotu",
    job: "katalog slot_guarantee_mark HITL",
  },
  {
    route: BUSINESS_LISTS.freightTermMark.route,
    label: "Warunek frachtu",
    job: "katalog freight_term_mark HITL",
  },
  {
    route: BUSINESS_LISTS.customerPoMark.route,
    label: "Referencja PO klienta",
    job: "katalog customer_po_mark HITL",
  },
  {
    route: BUSINESS_LISTS.profitCenterMark.route,
    label: "Centrum zysku/kosztu",
    job: "katalog profit_center_mark HITL",
  },
  {
    route: BUSINESS_LISTS.highValueMark.route,
    label: "Protokol high-value",
    job: "katalog high_value_mark HITL",
  },
  {
    route: BUSINESS_LISTS.paymentTermsMark.route,
    label: "Warunki platnosci",
    job: "katalog payment_terms_mark HITL",
  },
  {
    route: BUSINESS_LISTS.languageCodeMark.route,
    label: "Kod jezyka",
    job: "katalog language_code_mark HITL",
  },
  {
    route: BUSINESS_LISTS.haulierRoleMark.route,
    label: "Rola przewoznika",
    job: "katalog haulier_role_mark HITL",
  },
  {
    route: BUSINESS_LISTS.impersonateGuardMark.route,
    label: "Impersonate guard",
    job: "katalog impersonate_guard_mark HITL",
  },
  {
    route: BUSINESS_LISTS.fuelCardMark.route,
    label: "Fuel card",
    job: "katalog fuel_card_mark HITL",
  },
  {
    route: BUSINESS_LISTS.eDoreczeniaMark.route,
    label: "e-Doręczenia",
    job: "katalog e_doreczenia_mark HITL",
  },
  {
    route: BUSINESS_LISTS.remediationOption.route,
    label: "Opcja naprawy",
    job: "katalog remediation_option HITL",
  },
  {
    route: BUSINESS_LISTS.impactScenario.route,
    label: "Scenariusz skutku",
    job: "katalog impact_scenario HITL",
  },
  {
    route: BUSINESS_LISTS.clauseNotice.route,
    label: "Powiadomienie o klauzuli",
    job: "katalog clause_notice HITL",
  },
  {
    route: BUSINESS_LISTS.calibrationMark.route,
    label: "Znacznik kalibracji",
    job: "katalog calibration_mark HITL",
  },
  {
    route: BUSINESS_LISTS.campaignMark.route,
    label: "Kampania marketingowa",
    job: "katalog campaign_mark HITL",
  },
  {
    route: BUSINESS_LISTS.groupageDispatcherMark.route,
    label: "Dyspozytor drobnicy",
    job: "katalog groupage_dispatcher_mark HITL",
  },
  {
    route: BUSINESS_LISTS.repairPlaybook.route,
    label: "Playbook naprawy",
    job: "katalog repair_playbook HITL",
  },
  {
    route: BUSINESS_LISTS.spendMark.route,
    label: "Znacznik wycieku",
    job: "katalog spend_mark HITL",
  },
  {
    route: BUSINESS_LISTS.penaltyMark.route,
    label: "Znacznik kary",
    job: "katalog penalty_mark HITL",
  },
  {
    route: BUSINESS_LISTS.interventionOutcome.route,
    label: "Wynik interwencji",
    job: "katalog intervention_outcome HITL",
  },
  {
    route: BUSINESS_LISTS.freightAuditMark.route,
    label: "Audyt frachtu",
    job: "katalog freight_audit_mark HITL",
  },
  {
    route: BUSINESS_LISTS.collaborationMark.route,
    label: "Współpraca 3 stron",
    job: "katalog collaboration_mark HITL",
  },
  {
    route: BUSINESS_LISTS.crmLead.route,
    label: "Lead CRM",
    job: "katalog crm_lead HITL",
  },
  {
    route: BUSINESS_LISTS.crmOpportunity.route,
    label: "Okazja CRM",
    job: "katalog crm_opportunity HITL",
  },
  {
    route: BUSINESS_LISTS.crmActivity.route,
    label: "Aktywność CRM",
    job: "katalog crm_activity HITL",
  },
  {
    route: BUSINESS_LISTS.crmPipelineMark.route,
    label: "Etap CRM",
    job: "katalog crm_pipeline_mark HITL",
  },
  {
    route: BUSINESS_LISTS.salesLane.route,
    label: "Korytarz sprzedażowy",
    job: "katalog sales_lane HITL",
  },
  {
    route: BUSINESS_LISTS.shipperTenderMark.route,
    label: "Przetarg załadowcy",
    job: "katalog shipper_tender_mark HITL",
  },
  {
    route: BUSINESS_LISTS.positionEvent.route,
    label: "Zdarzenie pozycji",
    job: "katalog position_event HITL",
  },
  {
    route: BUSINESS_LISTS.exchangeConnector.route,
    label: "Konektor giełdy",
    job: "katalog exchange_connector HITL",
  },
  {
    route: BUSINESS_LISTS.terminalSlotConnector.route,
    label: "Konektor slotu",
    job: "katalog terminal_slot_connector HITL",
  },
  { route: BUSINESS_LISTS.users.route, label: "Użytkownicy", job: "tenant users" },
  { route: "/session", label: "Sesja", job: "token klienta" },
] as const

export const HELLO_DASHBOARD_MARKERS = ["Shell 0.5", "hello-dashboard", "kafelki"] as const

export const SHIPPED_CHARGE_ROUTES = {
  "1.0": "/charge-codes",
  "1.1": "/rate-lines",
  "1.2": "/charges",
  "2.0": "/quotations",
  "3.0": "/organization-settings",
  "4.0": "/ports",
  "4.1": "/locations",
  "4.2": "/terminals",
  "5.0": "/parties",
  "5.2": "/commodity-codes",
  "6.0": "/nbp-rates",
  "7.0": "/dangerous-goods",
  "8.0": "/parties",
  "9.0": "/networks",
  "10.0": "/party-scorecards",
  "11.0": "/customer-sops",
  "12.0": "/port-surcharges",
  "13.0": "/channel-quotes",
  "14.0": "/credit-reviews",
  "15.0": "/finance",
  "16.0": "/quotations",
  "17.0": "/quotations",
  "18.0": "/quotations",
  "19.0": "/quotations",
  "20.0": "/quotations",
  "21.0": "/quotations",
  "22.0": "/quotations",
  "23.0": "/quotations",
  "24.0": "/quotations",
  "25.0": "/mail",
  "26.0": "/mail",
  "27.0": "/notifications",
  "28.0": "/shipments",
  "29.0": "/tracking",
  "30.0": "/exceptions",
  "31.0": "/shipment-documents",
  "32.0": "/edi",
  "33.0": "/invoices",
  "34.0": "/quote-invoices",
  "35.0": "/payments",
  "36.0": "/money-cost",
  "37.0": "/fx-differences",
  "38.0": "/cashflows",
  "39.0": "/cost-to-serve",
  "40.0": "/bookkeeping",
  "41.0": "/road",
  "42.0": "/rail",
  "43.0": "/china-rail",
  "44.0": "/lcl",
  "45.0": "/sanctions",
  "46.0": "/gdpr",
  "47.0": "/ai",
  "48.0": "/health",
  "49.0": "/quality",
  "50.0": "/rollout",
  "74.0": "/decisions",
  "75.0": "/notifications",
  "76.0": "/ai",
  "77.0": "/decisions",
  "78.0": "/mail",
  "79.0": "/outbox",
  "80.0": "/mail",
  "81.0": "/ai",
  "82.0": "/networks",
  "83.0": "/networks",
  "84.0": "/quotations",
  "85.0": "/quotations",
  "86.0": "/quotations",
  "87.0": "/quotations",
  "88.0": "/credit-reviews",
  "89.0": "/sanctions",
  "90.0": "/shipments",
  "91.0": "/tracking",
  "92.0": "/shipment-documents",
  "93.0": "/exceptions",
  "94.0": "/watchtower",
  "95.0": "/edi",
  "96.0": "/invoices",
  "97.0": "/invoices",
  "98.0": "/quote-invoices",
  "99.0": "/payments",
  "100.0": "/money-cost",
  "101.0": "/fx-differences",
  "102.0": "/cashflows",
  "103.0": "/cost-to-serve",
  "104.0": "/bookkeeping",
  "105.0": "/invoices",
  "106.0": "/finance",
  "107.0": "/gdpr",
  "108.0": "/road",
  "109.0": "/rail",
  "110.0": "/china-rail",
  "111.0": "/lcl",
  "113.0": "/claims",
  "114.0": "/fraud",
  "116.0": "/watchtower",
  "117.0": "/finance",
  "118.0": "/ai",
  "120.0": "/party-scorecards",
  "121.0": "/decisions",
  "122.0": "/mail",
  "123.0": "/notifications",
  "124.0": "/watchtower",
  "129.0": "/charges",
  "130.0": "/networks",
  "131.0": "/parties",
  "132.0": "/parties",
  "133.0": "/entity-events",
  "134.0": "/quotations",
  "135.0": "/quotations",
  "136.0": "/networks",
  "137.0": "/quotations",
  "138.0": "/networks",
  "139.0": "/party-scorecards",
  "140.0": "/ai",
  "141.0": "/networks",
  "142.0": "/mail",
  "143.0": "/networks",
  "144.0": "/quotations",
  "145.0": "/quotations",
  "146.0": "/shipments",
  "147.0": "/quotations",
  "148.0": "/shipments",
  "149.0": "/organization-settings",
  "150.0": "/shipments",
  "151.0": "/shipments",
  "152.0": "/shipments",
  "153.0": "/shipments",
  "154.0": "/air",
  "155.0": "/groupage",
  "156.0": "/shipment-packages",
  "157.0": "/dock-appointments",
  "158.0": "/cod",
  "159.0": "/groupage-tariffs",
  "160.0": "/ocean-bills",
  "161.0": "/pallet-balances",
  "162.0": "/document-templates",
  "163.0": "/rate-cards",
  "164.0": "/charge-templates",
  "165.0": "/fuel-indexes",
  "166.0": "/local-charges",
  "167.0": "/shipments",
  "168.0": "/tender-quotes",
  "169.0": "/tenders",
  "170.0": "/tender-lots",
  "171.0": "/tender-lanes",
  "172.0": "/tender-rounds",
  "173.0": "/tender-data-rooms",
  "174.0": "/tender-matrix-cells",
  "175.0": "/tender-playbooks",
  "176.0": "/tender-win-losses",
  "177.0": "/tender-consortium-members",
  "178.0": "/tender-rfp-intakes",
  "179.0": "/ai",
  "180.0": "/tender-prospects",
  "181.0": "/tender-bid-stances",
  "182.0": "/tender-award-reviews",
  "183.0": "/tender-ted-notices",
  "184.0": "/tender-carbon-marks",
  "185.0": "/lane-patterns",
  "186.0": "/kreptd-licences",
  "187.0": "/monitoring-schemes",
  "188.0": "/party-documents",
  "189.0": "/cash-discounts",
  "190.0": "/carbon-methods",
  "191.0": "/claims",
  "192.0": "/dangerous-goods",
  "193.0": "/prediction-ledgers",
  "194.0": "/shipments",
  "195.0": "/weather-observations",
  "196.0": "/free-time-clocks",
  "197.0": "/telematics-connectors",
  "198.0": "/tower-impacts",
  "199.0": "/twin-marks",
  "200.0": "/war-room-marks",
  "201.0": "/memory-edges",
  "202.0": "/executive-marks",
  "203.0": "/rank-marks",
  "204.0": "/shipments",
  "205.0": "/rate-cards",
  "206.0": "/charge-templates",
  "207.0": "/local-charges",
  "208.0": "/local-charges",
  "209.0": "/air",
  "210.0": "/shipments",
  "211.0": "/organization-settings",
  "212.0": "/shipments",
  "213.0": "/shipments",
  "214.0": "/shipments",
  "215.0": "/shipments",
  "216.0": "/shipments",
  "217.0": "/shipments",
  "218.0": "/shipments",
  "219.0": "/shipments",
  "220.0": "/shipments",
  "221.0": "/shipments",
  "222.0": "/shipments",
  "223.0": "/shipments",
  "224.0": "/shipments",
  "225.0": "/shipments",
  "226.0": "/shipments",
  "227.0": "/shipments",
  "228.0": "/shipments",
  "229.0": "/shipments",
  "230.0": "/shipments",
  "231.0": "/shipments",
  "232.0": "/shipments",
  "233.0": "/shipments",
  "234.0": "/shipments",
  "235.0": "/shipments",
  "236.0": "/shipments",
  "237.0": "/shipments",
  "238.0": "/shipments",
  "239.0": "/shipments",
  "240.0": "/shipments",
  "241.0": "/shipments",
  "242.0": "/shipments",
  "243.0": "/shipments",
  "244.0": "/entity-events",
  "245.0": "/entity-events",
  "246.0": "/entity-events",
  "247.0": "/shipments",
  "248.0": "/shipments",
  "249.0": "/shipments",
  "250.0": "/shipments",
  "251.0": "/shipments",
  "252.0": "/shipments",
  "253.0": "/shipments",
  "254.0": "/shipments",
  "255.0": "/shipments",
  "256.0": "/shipments",
  "257.0": "/shipments",
  "258.0": "/shipments",
  "259.0": "/fleet",
  "260.0": "/consignments",
  "261.0": "/planning",
  "262.0": "/charges",
  "263.0": "/task-templates",
  "264.0": "/outbox",
  "265.0": "/plan-snapshots",
  "452.0": "/plan-snapshots",
  "266.0": "/circle-sims",
  "454.0": "/circle-sims",
  "455.0": "/route-plan-marks",
  "456.0": "/crm-opportunities",
  "489.0": "/crm-activities",
  "490.0": "/crm-pipeline-marks",
  "457.0": "/position-events",
  "458.0": "/telematics-devices",
  "459.0": "/tracking-consents",
  "460.0": "/sales-lanes",
  "461.0": "/shipper-tender-marks",
  "462.0": "/campaign-marks",
  "463.0": "/groupage-dispatcher-marks",
  "464.0": "/load-order-marks",
  "465.0": "/tacho-plan-marks",
  "466.0": "/ferry-booking-marks",
  "467.0": "/oog-permit-marks",
  "468.0": "/lcl-console-marks",
  "469.0": "/nac-marks",
  "470.0": "/silk-corridor-marks",
  "471.0": "/factoring-connectors",
  "472.0": "/po-financing-marks",
  "474.0": "/wms-flow-marks",
  "475.0": "/rfid-marks",
  "476.0": "/inventory-finance-marks",
  "477.0": "/inventory-collateral-marks",
  "478.0": "/ops-room-marks",
  "479.0": "/line-impact-layer-marks",
  "480.0": "/product-ticket-marks",
  "481.0": "/risk-register-marks",
  "482.0": "/automation-bias-marks",
  "483.0": "/l3-gate-marks",
  "484.0": "/style-cascade-marks",
  "485.0": "/style-fidelity-marks",
  "486.0": "/quality-descent-marks",
  "487.0": "/field-confidence-marks",
  "488.0": "/compliance-program-marks",
  "267.0": "/lane-kms",
  "268.0": "/erp-connectors",
  "269.0": "/terminal-slot-connectors",
  "270.0": "/idp-connectors",
  "271.0": "/exchange-connectors",
  "473.0": "/exchange-connectors",
  "272.0": "/customer-contracts",
  "273.0": "/customer-contracts",
  "274.0": "/tenant-contract-keks",
  "275.0": "/visibility-connectors",
  "276.0": "/purchase-orders",
  "277.0": "/po-lines",
  "278.0": "/asns",
  "279.0": "/routing-guides",
  "280.0": "/otif-marks",
  "281.0": "/sap-connectors",
  "282.0": "/capa-marks",
  "283.0": "/freight-audit-marks",
  "284.0": "/collaboration-marks",
  "285.0": "/routing-guide-enforcements",
  "286.0": "/asns",
  "287.0": "/shipments",
  "288.0": "/routing-guide-matches",
  "289.0": "/asns",
  "290.0": "/shipments",
  "291.0": "/asns",
  "313.0": "/sla-clauses",
  "314.0": "/delay-forecasts",
  "315.0": "/remediation-options",
  "316.0": "/impact-scenarios",
  "317.0": "/clause-notices",
  "318.0": "/calibration-marks",
  "319.0": "/repair-playbooks",
  "320.0": "/spend-marks",
  "321.0": "/penalty-marks",
  "322.0": "/intervention-outcomes",
  "323.0": "/crm-leads",
  "324.0": "/lc-checklists",
  "325.0": "/ncts-drafts",
  "326.0": "/oog-marks",
  "327.0": "/load-plan-marks",
  "328.0": "/cmms-marks",
  "329.0": "/legal-hold-marks",
  "330.0": "/company-marks",
  "331.0": "/bonded-marks",
  "332.0": "/filing-scheme-marks",
  "333.0": "/edi-map-marks",
  "334.0": "/aeo-dossier-marks",
  "335.0": "/yard-marks",
  "336.0": "/billing-marks",
  "337.0": "/registry-poll-marks",
  "338.0": "/working-capital-marks",
  "339.0": "/make-or-buy-marks",
  "340.0": "/cost-allocation-marks",
  "341.0": "/cargo-cover-marks",
  "342.0": "/sanctions-marks",
  "343.0": "/subcontract-edge-marks",
  "344.0": "/schedule-exception-marks",
  "345.0": "/cutoff-marks",
  "346.0": "/time-to-fix-marks",
  "347.0": "/what-if-marks",
  "348.0": "/cabotage-marks",
  "349.0": "/combined-transport-marks",
  "350.0": "/ferry-art9-marks",
  "351.0": "/fuel-anomaly-marks",
  "352.0": "/fleet-cost-marks",
  "353.0": "/bin-pack-marks",
  "354.0": "/pallet-pool-marks",
  "355.0": "/e-cmr-marks",
  "356.0": "/e-delivery-marks",
  "357.0": "/peppol-marks",
  "358.0": "/sid-import-marks",
  "359.0": "/integration-hub-marks",
  "360.0": "/webhook-outbox-marks",
  "361.0": "/partner-exchange-marks",
  "362.0": "/regulatory-radar-marks",
  "363.0": "/iso-nis2-marks",
  "365.0": "/offboarding-marks",
  "366.0": "/jit-jis-marks",
  "367.0": "/vda-odette-marks",
  "368.0": "/inventory-position-marks",
  "369.0": "/fair-share-marks",
  "370.0": "/mqc-marks",
  "371.0": "/eccn-marks",
  "372.0": "/eur1-atr-marks",
  "373.0": "/phyto-ata-marks",
  "374.0": "/switch-bl-loi-marks",
  "375.0": "/abandoned-rto-marks",
  "376.0": "/general-average-marks",
  "377.0": "/tender-decline-reasons",
  "378.0": "/demand-snapshot-marks",
  "379.0": "/csrd-marks",
  "380.0": "/air-ra3-marks",
  "381.0": "/rail-cim-marks",
  "382.0": "/ocean-alliance-marks",
  "383.0": "/reefer-marks",
  "384.0": "/empty-depot-marks",
  "385.0": "/nvocc-marks",
  "386.0": "/multi-manning-marks",
  "387.0": "/posting-marks",
  "388.0": "/tacho-office-marks",
  "389.0": "/lez-marks",
  "390.0": "/label-parking-marks",
  "391.0": "/ab-sus-marks",
  "392.0": "/funnel-marks",
  "393.0": "/terms-ai-marks",
  "394.0": "/mail-accept-marks",
  "395.0": "/role-view-marks",
  "396.0": "/rag-sop-marks",
  "397.0": "/copy-ban-marks",
  "398.0": "/erru-marks",
  "399.0": "/mobile-client-marks",
  "401.0": "/job-metric-marks",
  "402.0": "/demo-gps-marks",
  "403.0": "/impersonate-guard-marks",
  "404.0": "/fuel-card-marks",
  "405.0": "/e-doreczenia-marks",
  "406.0": "/rail-uic-marks",
  "407.0": "/ocean-feeder-marks",
  "408.0": "/chassis-marks",
  "409.0": "/line-impact-marks",
  "410.0": "/three-way-marks",
  "411.0": "/demo-wipe-marks",
  "412.0": "/demo-sim-marks",
  "413.0": "/po-plant-marks",
  "414.0": "/po-sku-marks",
  "415.0": "/po-batch-marks",
  "416.0": "/un-segregation-marks",
  "417.0": "/dual-ledger-marks",
  "418.0": "/named-place-marks",
  "419.0": "/slot-guarantee-marks",
  "420.0": "/freight-term-marks",
  "421.0": "/customer-po-marks",
  "422.0": "/profit-center-marks",
  "423.0": "/high-value-marks",
  "424.0": "/payment-terms-marks",
  "425.0": "/language-code-marks",
  "426.0": "/haulier-role-marks",
  "427.0": "/diversion-marks",
  "428.0": "/spot-contract-marks",
  "429.0": "/bid-decision-marks",
  "430.0": "/quote-currency-marks",
  "431.0": "/quote-validity-marks",
  "432.0": "/suggestion-ledgers",
  "433.0": "/outcome-ledgers",
  "434.0": "/counterfactual-runs",
  "453.0": "/counterfactual-runs",
  "435.0": "/benefit-ledgers",
  "436.0": "/suggestion-kinds",
  "437.0": "/twin-kinds",
  "438.0": "/autonomy-levels",
  "441.0": "/outcome-kinds",
  "443.0": "/interval-scores",
  "444.0": "/version-scores",
  "445.0": "/version-windows",
  "446.0": "/prediction-ledgers",
  "447.0": "/extractions",
  "448.0": "/extractions",
  "449.0": "/extractions",
  "451.0": "/extractions",
} as const


export const ROUTES_BREADTH_STANDING =
  "Nowe BC z jobem operatora = trasa w tym samym plasterze. Charge 1.0–1.2 już mają UI. To standing, nie 70 modułów."
