import { BUSINESS_LISTS } from "@/lib/business-lists"

export const ADMIN_REF_SURFACES = [
  "sidebar-density",
  "table-toolbar",
  "command-actions",
] as const

export const OPS_JOBS = [
  { route: BUSINESS_LISTS.extractions.route, label: "Ekstrakcje HITL", job: "extract / accept" },
  {
    route: BUSINESS_LISTS.financeBoard.route,
    label: "Tablica finansowa",
    job: "odczyt marży / NBP / limitu / recenzji",
  },
  {
    route: BUSINESS_LISTS.financeBoard.route,
    label: "Tablica — narracja",
    job: "zdania z pól SQL bez sumy",
  },
  {
    route: BUSINESS_LISTS.salesInvoice.route,
    label: "Faktury",
    job: "zapis faktury i numeru sesji",
  },
  {
    route: BUSINESS_LISTS.quoteInvoiceSettlement.route,
    label: "Rozliczenie wyceny",
    job: "zapis rozliczenia wyceny z fakturą",
  },
  {
    route: BUSINESS_LISTS.bankPayment.route,
    label: "Bank i płatności",
    job: "zapis płatności na rachunek",
  },
  {
    route: BUSINESS_LISTS.moneyCost.route,
    label: "Koszt pieniądza",
    job: "zapis kosztu pieniądza przy płatności",
  },
  {
    route: BUSINESS_LISTS.fxDifference.route,
    label: "Różnice kursowe",
    job: "zapis różnicy kursowej przy wycenie",
  },
  {
    route: BUSINESS_LISTS.cashFlow.route,
    label: "Przepływy",
    job: "zapis przepływu wyceny przy płatności",
  },
  {
    route: BUSINESS_LISTS.costToServe.route,
    label: "Koszt obsługi klienta",
    job: "zapis kosztu obsługi przy SOP",
  },
  {
    route: BUSINESS_LISTS.bookkeeping.route,
    label: "Księgowość",
    job: "zapis dekretu opłaty na fakturę",
  },
  {
    route: BUSINESS_LISTS.roadTransport.route,
    label: "Transport drogowy",
    job: "lokalizacje postal_zone i address",
  },
  {
    route: BUSINESS_LISTS.intermodalRail.route,
    label: "Kolej intermodalna",
    job: "porty z flagą rail",
  },
  {
    route: BUSINESS_LISTS.chinaRail.route,
    label: "Kolej z Chin",
    job: "porty CN z flagą rail",
  },
  {
    route: BUSINESS_LISTS.oceanLcl.route,
    label: "Drobnica morska",
    job: "porty z is_seaport",
  },
  {
    route: BUSINESS_LISTS.oceanBill.route,
    label: "Konosament LCL",
    job: "znacznik ocean_bill HBL/MBL bez PDF",
  },
  {
    route: BUSINESS_LISTS.consignment.route,
    label: "Przesyłki",
    job: "zapis consignment na zleceniu",
  },
  {
    route: BUSINESS_LISTS.palletBalance.route,
    label: "Saldo palet",
    job: "saldo pallet_balance Chep/LPR bez giełdy",
  },
  {
    route: BUSINESS_LISTS.documentTemplate.route,
    label: "Szablony wydruku",
    job: "katalog document_template layout bez PDF",
  },
  {
    route: BUSINESS_LISTS.rateCard.route,
    label: "Karty stawek",
    job: "katalog rate_card applies_when bez matching",
  },
  {
    route: BUSINESS_LISTS.chargeTemplate.route,
    label: "Szablony opłat",
    job: "katalog charge_template kodów bez exclusion",
  },
  {
    route: BUSINESS_LISTS.fuelIndex.route,
    label: "Indeksy paliwowe",
    job: "katalog fuel_index FSC/BAF/CAF bez mnożenia",
  },
  {
    route: BUSINESS_LISTS.localCharge.route,
    label: "Dopłaty lokalne",
    job: "katalog local_charge THC/ISPS bez warning",
  },
  {
    route: BUSINESS_LISTS.tenderDataRoom.route,
    label: "Pokoje danych",
    job: "NDA na tender bez extractu",
  },
  {
    route: BUSINESS_LISTS.tenderMatrixCell.route,
    label: "Komórki matrycy",
    job: "kwota Decimal z P bez LLM",
  },
  {
    route: BUSINESS_LISTS.tenderPlaybook.route,
    label: "Playbook przetargu",
    job: "twierdzenie na tender bez extractu",
  },
  {
    route: BUSINESS_LISTS.tenderWinLoss.route,
    label: "Wynik przetargu",
    job: "werdykt win/loss bez extractu",
  },
  {
    route: BUSINESS_LISTS.tenderConsortiumMember.route,
    label: "Konsorcjum przetargu",
    job: "fotel lead/member bez extractu",
  },
  {
    route: BUSINESS_LISTS.tenderRfpIntake.route,
    label: "Przyjęcie RFP",
    job: "HITL przyjęcie RFP bez zapisu z LLM",
  },
  {
    route: BUSINESS_LISTS.tenderProspect.route,
    label: "Prospekt przetargu",
    job: "HITL outreach firmy bez scrape",
  },
  {
    route: BUSINESS_LISTS.tenderBidStance.route,
    label: "Udział w przetargu",
    job: "HITL bid/no-bid bez auto-award",
  },
  {
    route: BUSINESS_LISTS.tenderCarbonMark.route,
    label: "Ślad węglowy przetargu",
    job: "HITL declared/exempt bez kalkulatora kg",
  },
  {
    route: BUSINESS_LISTS.lanePattern.route,
    label: "Wzorzec korytarza",
    job: "HITL para UN/LOCODE bez circle_sim",
  },
  {
    route: BUSINESS_LISTS.kreptdLicence.route,
    label: "Licencja KREPTD",
    job: "HITL numer licencji bez scrape",
  },
  {
    route: BUSINESS_LISTS.monitoringScheme.route,
    label: "Schemat monitoringu",
    job: "HITL katalog schematu bez SENT XML",
  },
  {
    route: BUSINESS_LISTS.partyDocument.route,
    label: "Dokument kontrahenta",
    job: "HITL rodzaj dokumentu bez 409 na zleceniu",
  },
  {
    route: BUSINESS_LISTS.cashDiscount.route,
    label: "Skonto",
    job: "HITL rodzaj skonta bez kwoty",
  },
  {
    route: BUSINESS_LISTS.carbonMethod.route,
    label: "Metodyka CO₂",
    job: "HITL GLEC/GHG bez kalkulatora kg",
  },
  {
    route: BUSINESS_LISTS.predictionLedger.route,
    label: "Ledger predykcji",
    job: "HITL przedział + CRPS bez silnika",
  },
  {
    route: BUSINESS_LISTS.weatherObservation.route,
    label: "Pogoda",
    job: "HITL warunek + UN/LOCODE bez Open-Meteo",
  },
  {
    route: BUSINESS_LISTS.freeTimeClock.route,
    label: "Zegar DD",
    job: "HITL rodzaj + dni wolne bez countdown",
  },
  {
    route: BUSINESS_LISTS.telematicsConnector.route,
    label: "Konektor GPS",
    job: "HITL reżim + dostawca bez live poll",
  },
  {
    route: BUSINESS_LISTS.towerImpact.route,
    label: "Skutek wieży",
    job: "HITL etap łańcucha bez scoringu",
  },
  {
    route: BUSINESS_LISTS.twinMark.route,
    label: "Bliźniak",
    job: "HITL 8 rodzajów bez fizyki",
  },
  {
    route: BUSINESS_LISTS.warRoomMark.route,
    label: "Sala kryzysowa",
    job: "HITL incydent bez scalania alertów",
  },
  {
    route: BUSINESS_LISTS.memoryEdge.route,
    label: "Krawędź pamięci",
    job: "HITL rodzaj krawędzi bez wyszukiwania stawek",
  },
  {
    route: BUSINESS_LISTS.executiveMark.route,
    label: "Pytanie zarządu",
    job: "HITL rodzaj pytania bez sumy z modelu",
  },
  {
    route: BUSINESS_LISTS.rankMark.route,
    label: "Oś rankingu",
    job: "HITL oś zakupu bez auto-award",
  },
  {
    route: BUSINESS_LISTS.tenderAwardReview.route,
    label: "Cztery oczy nagrody",
    job: "HITL przegląd nagrody bez auto-award",
  },
  {
    route: BUSINESS_LISTS.tenderTedNotice.route,
    label: "Ogłoszenie TED",
    job: "HITL numer TED bez scrape",
  },
  {
    route: BUSINESS_LISTS.tenderLane.route,
    label: "Korytarze przetargu",
    job: "para UN/LOCODE na partii bez rundy",
  },
  {
    route: BUSINESS_LISTS.tenderLot.route,
    label: "Partie przetargu",
    job: "kod partii na tender bez korytarza",
  },
  {
    route: BUSINESS_LISTS.tenderRound.route,
    label: "Rundy przetargu",
    job: "numer rundy na tender bez data room",
  },
  {
    route: BUSINESS_LISTS.tenderQuote.route,
    label: "Oferty przetargowe",
    job: "ważność i limit orderów bez auto-award",
  },
  {
    route: BUSINESS_LISTS.tender.route,
    label: "Przetargi",
    job: "nagłówek tender sell/buy bez auto-award",
  },
  {
    route: BUSINESS_LISTS.airFreight.route,
    label: "Lotniczy",
    job: "lotniska z flagą airport",
  },
  {
    route: BUSINESS_LISTS.groupageLines.route,
    label: "Linie drobnicy",
    job: "katalog groupage_line cutoff i ISODOW",
  },
  {
    route: BUSINESS_LISTS.groupageTariff.route,
    label: "Cennik drobnicy",
    job: "próg groupage_tariff na strefie bez silnika",
  },
  {
    route: BUSINESS_LISTS.shipmentPackage.route,
    label: "Paczki",
    job: "skan shipment_package QR Omni i stop",
  },
  {
    route: BUSINESS_LISTS.dockAppointment.route,
    label: "Awizacje doku",
    job: "okno dock_appointment na stop magazynu",
  },
  {
    route: BUSINESS_LISTS.codInstruction.route,
    label: "Pobranie COD",
    job: "znacznik cod_instruction bez kwoty",
  },
  {
    route: BUSINESS_LISTS.sanctions.route,
    label: "Sankcje",
    job: "aktywni kontrahenci tax_id i kraj",
  },
  {
    route: BUSINESS_LISTS.gdpr.route,
    label: "RODO",
    job: "wniosek i usunięcie katalogu",
  },
  {
    route: BUSINESS_LISTS.aiCopilot.route,
    label: "Propozycje AI",
    job: "szkice HITL pending",
  },
  {
    route: BUSINESS_LISTS.aiCopilot.route,
    label: "Szkice po SOP",
    job: "odczyt blocks_auto przy mail_draft",
  },
  {
    route: BUSINESS_LISTS.observability.route,
    label: "Obserwowalność",
    job: "status API fetchHealth",
  },
  {
    route: BUSINESS_LISTS.extractionQuality.route,
    label: "Jakość ekstrakcji",
    job: "szkice z unparsed_regions",
  },
  {
    route: BUSINESS_LISTS.tenantRollout.route,
    label: "Wdrożenie",
    job: "klucz default_currency z ustawień",
  },
  {
    route: BUSINESS_LISTS.mailIntegration.route,
    label: "Poczta",
    job: "znane adresy i inbound_message fixture",
  },
  {
    route: BUSINESS_LISTS.mailIntegration.route,
    label: "Poczta — UN",
    job: "Podpnij UN na zapytaniu",
  },
  {
    route: BUSINESS_LISTS.operatorNotice.route,
    label: "Powiadomienia",
    job: "HITL pending i wyceny pending",
  },
  {
    route: BUSINESS_LISTS.operatorNotice.route,
    label: "Powiadomienia — filtr",
    job: "filtr kind na tablicy 27.0",
  },
  {
    route: BUSINESS_LISTS.shipment.route,
    label: "Zlecenia",
    job: "wyceny z party_id jako praca handlowa",
  },
  {
    route: BUSINESS_LISTS.tracking.route,
    label: "Tracking",
    job: "lane POL/POD z wyceny",
  },
  {
    route: BUSINESS_LISTS.operationalException.route,
    label: "Wyjątki",
    job: "wyceny z party bez pełnego POL/POD",
  },
  {
    route: BUSINESS_LISTS.cargoClaim.route,
    label: "Reklamacje ładunku",
    job: "zapis reklamacji na zleceniu",
  },
  {
    route: BUSINESS_LISTS.fraudFlag.route,
    label: "Oszustwo",
    job: "zapis flagi oszustwa na kontrahencie",
  },
  {
    route: BUSINESS_LISTS.watchtower.route,
    label: "Wieża",
    job: "wyjątki i pending S11 plus leniwy panel mapy",
  },
  {
    route: BUSINESS_LISTS.watchtower.route,
    label: "Wieża — szkice",
    job: "odczyt mail_draft na wieży",
  },
  {
    route: BUSINESS_LISTS.watchtower.route,
    label: "Wieża — liczniki",
    job: "podsumowanie wyjątków, pending i szkiców",
  },
  {
    route: BUSINESS_LISTS.shipmentDocument.route,
    label: "Dokumenty zlecenia",
    job: "source_ref wycen z party_id",
  },
  {
    route: BUSINESS_LISTS.ediMessage.route,
    label: "EDI",
    job: "zapis edi_message na zleceniu",
  },
  { route: BUSINESS_LISTS.chargeCodes.route, label: "Kody opłat", job: "katalog charge_code" },
  {
    route: BUSINESS_LISTS.commodityCodes.route,
    label: "Kody towarowe",
    job: "katalog commodity_code",
  },
  {
    route: BUSINESS_LISTS.dangerousGoods.route,
    label: "Towary niebezpieczne",
    job: "katalog dangerous_good UN/IMDG",
  },
  {
    route: BUSINESS_LISTS.networks.route,
    label: "Sieci",
    job: "katalog network per tenant",
  },
  {
    route: BUSINESS_LISTS.nbpRates.route,
    label: "Kursy NBP",
    job: "katalog nbp_rate tabeli A",
  },
  { route: BUSINESS_LISTS.rateLines.route, label: "Stawki kupna", job: "rate_line + source_ref" },
  { route: BUSINESS_LISTS.charges.route, label: "Opłaty", job: "buy+sell / marża" },
  {
    route: BUSINESS_LISTS.channelQuotes.route,
    label: "Oferty kanału",
    job: "katalog channel_quote + resolve",
  },
  {
    route: BUSINESS_LISTS.quotations.route,
    label: "Wyceny",
    job: "SQL z rate_line + kanał + zapytania",
  },
  { route: BUSINESS_LISTS.organizationSettings.route, label: "Ustawienia", job: "config jako dane" },
  { route: BUSINESS_LISTS.ports.route, label: "Porty", job: "katalog UN/LOCODE + resolve" },
  {
    route: BUSINESS_LISTS.portSurcharges.route,
    label: "Opłaty portowe",
    job: "katalog port_surcharge + resolve",
  },
  {
    route: BUSINESS_LISTS.locations.route,
    label: "Lokalizacje",
    job: "strefy taryfowe + resolve kodu",
  },
  {
    route: BUSINESS_LISTS.terminals.route,
    label: "Terminale",
    job: "katalog ISPS + resolve",
  },
  {
    route: BUSINESS_LISTS.parties.route,
    label: "Kontrahenci",
    job: "katalog party + resolve tax_id / mail",
  },
  {
    route: BUSINESS_LISTS.partyScorecards.route,
    label: "Karty wyników",
    job: "snapshot party_scorecard",
  },
  {
    route: BUSINESS_LISTS.partyScorecards.route,
    label: "Karty — decyzje oferty",
    job: "odczyt przyjętych i odrzuconych wycen",
  },
  {
    route: BUSINESS_LISTS.customerSops.route,
    label: "Procedury klienta",
    job: "katalog customer_sop + zatwierdzenie",
  },
  {
    route: BUSINESS_LISTS.creditReviews.route,
    label: "Recenzje kredytowe",
    job: "katalog credit_review + resolve",
  },
  {
    route: BUSINESS_LISTS.operatorDecisions.route,
    label: "Decyzje",
    job: "szyna operator_decision accept/reject",
  },
  {
    route: BUSINESS_LISTS.operatorDecisions.route,
    label: "Decyzje — Zmień",
    job: "werdykt changed z lock_version",
  },
  {
    route: BUSINESS_LISTS.outboxEvents.route,
    label: "Outbox",
    job: "zdarzenie inbound_message_saved",
  },
  {
    route: BUSINESS_LISTS.entityEvents.route,
    label: "Zdarzenia podmiotu",
    job: "ledger entity_event append-only",
  },
  {
    route: BUSINESS_LISTS.fleet.route,
    label: "Flota",
    job: "zapis zasobu pojazdu/kierowcy/naczepy",
  },
  {
    route: BUSINESS_LISTS.planning.route,
    label: "Planowanie",
    job: "leniwy overlay etykiet trip",
  },
  {
    route: BUSINESS_LISTS.taskTemplate.route,
    label: "Szablon zadania",
    job: "katalog task_template HITL",
  },
  {
    route: BUSINESS_LISTS.planSnapshot.route,
    label: "Migawka planu",
    job: "katalog plan_snapshot HITL",
  },
  {
    route: BUSINESS_LISTS.circleSim.route,
    label: "Kółko",
    job: "katalog circle_sim HITL",
  },
  {
    route: BUSINESS_LISTS.laneKm.route,
    label: "Km ładowny",
    job: "katalog lane_km HITL",
  },
  {
    route: BUSINESS_LISTS.erpConnector.route,
    label: "Konektor Optima",
    job: "katalog erp_connector HITL",
  },
  {
    route: BUSINESS_LISTS.idpConnector.route,
    label: "Konektor Auth0",
    job: "katalog idp_connector HITL",
  },
  {
    route: BUSINESS_LISTS.customerContract.route,
    label: "Umowa klienta",
    job: "katalog customer_contract HITL",
  },
  {
    route: BUSINESS_LISTS.tenantContractKek.route,
    label: "Znacznik KEK",
    job: "katalog tenant_contract_kek HITL",
  },
  {
    route: BUSINESS_LISTS.visibilityConnector.route,
    label: "Konektor widoczności",
    job: "katalog visibility_connector HITL",
  },
  {
    route: BUSINESS_LISTS.purchaseOrder.route,
    label: "Zamówienie zakupu",
    job: "katalog purchase_order HITL",
  },
  {
    route: BUSINESS_LISTS.poLine.route,
    label: "Linia zamówienia",
    job: "katalog po_line HITL",
  },
  {
    route: BUSINESS_LISTS.asn.route,
    label: "Awizo wysyłki",
    job: "katalog asn HITL",
  },
  {
    route: BUSINESS_LISTS.routingGuide.route,
    label: "Przewodnik routingu",
    job: "katalog routing_guide HITL",
  },
  {
    route: BUSINESS_LISTS.routingGuideEnforcement.route,
    label: "Egzekucja przewodnika",
    job: "katalog routing_guide_enforcement HITL",
  },
  {
    route: BUSINESS_LISTS.routingGuideMatch.route,
    label: "Dopasowanie przewodnika",
    job: "katalog routing_guide_match HITL",
  },
  {
    route: BUSINESS_LISTS.otifMark.route,
    label: "Znacznik OTIF",
    job: "katalog otif_mark HITL",
  },
  {
    route: BUSINESS_LISTS.sapConnector.route,
    label: "Konektor SAP/Oracle",
    job: "katalog sap_connector HITL",
  },
  {
    route: BUSINESS_LISTS.capaMark.route,
    label: "Znacznik CAPA",
    job: "katalog capa_mark HITL",
  },
  {
    route: BUSINESS_LISTS.freightAuditMark.route,
    label: "Audyt frachtu",
    job: "katalog freight_audit_mark HITL",
  },
  {
    route: BUSINESS_LISTS.collaborationMark.route,
    label: "Współpraca 3 stron",
    job: "katalog collaboration_mark HITL",
  },
  {
    route: BUSINESS_LISTS.exchangeConnector.route,
    label: "Konektor giełdy",
    job: "katalog exchange_connector HITL",
  },
  {
    route: BUSINESS_LISTS.terminalSlotConnector.route,
    label: "Konektor slotu",
    job: "katalog terminal_slot_connector HITL",
  },
  { route: BUSINESS_LISTS.users.route, label: "Użytkownicy", job: "tenant users" },
  { route: "/session", label: "Sesja", job: "token klienta" },
] as const

export const HELLO_DASHBOARD_MARKERS = ["Shell 0.5", "hello-dashboard", "kafelki"] as const

export const SHIPPED_CHARGE_ROUTES = {
  "1.0": "/charge-codes",
  "1.1": "/rate-lines",
  "1.2": "/charges",
  "2.0": "/quotations",
  "3.0": "/organization-settings",
  "4.0": "/ports",
  "4.1": "/locations",
  "4.2": "/terminals",
  "5.0": "/parties",
  "5.2": "/commodity-codes",
  "6.0": "/nbp-rates",
  "7.0": "/dangerous-goods",
  "8.0": "/parties",
  "9.0": "/networks",
  "10.0": "/party-scorecards",
  "11.0": "/customer-sops",
  "12.0": "/port-surcharges",
  "13.0": "/channel-quotes",
  "14.0": "/credit-reviews",
  "15.0": "/finance",
  "16.0": "/quotations",
  "17.0": "/quotations",
  "18.0": "/quotations",
  "19.0": "/quotations",
  "20.0": "/quotations",
  "21.0": "/quotations",
  "22.0": "/quotations",
  "23.0": "/quotations",
  "24.0": "/quotations",
  "25.0": "/mail",
  "26.0": "/mail",
  "27.0": "/notifications",
  "28.0": "/shipments",
  "29.0": "/tracking",
  "30.0": "/exceptions",
  "31.0": "/shipment-documents",
  "32.0": "/edi",
  "33.0": "/invoices",
  "34.0": "/quote-invoices",
  "35.0": "/payments",
  "36.0": "/money-cost",
  "37.0": "/fx-differences",
  "38.0": "/cashflows",
  "39.0": "/cost-to-serve",
  "40.0": "/bookkeeping",
  "41.0": "/road",
  "42.0": "/rail",
  "43.0": "/china-rail",
  "44.0": "/lcl",
  "45.0": "/sanctions",
  "46.0": "/gdpr",
  "47.0": "/ai",
  "48.0": "/health",
  "49.0": "/quality",
  "50.0": "/rollout",
  "74.0": "/decisions",
  "75.0": "/notifications",
  "76.0": "/ai",
  "77.0": "/decisions",
  "78.0": "/mail",
  "79.0": "/outbox",
  "80.0": "/mail",
  "81.0": "/ai",
  "82.0": "/networks",
  "83.0": "/networks",
  "84.0": "/quotations",
  "85.0": "/quotations",
  "86.0": "/quotations",
  "87.0": "/quotations",
  "88.0": "/credit-reviews",
  "89.0": "/sanctions",
  "90.0": "/shipments",
  "91.0": "/tracking",
  "92.0": "/shipment-documents",
  "93.0": "/exceptions",
  "94.0": "/watchtower",
  "95.0": "/edi",
  "96.0": "/invoices",
  "97.0": "/invoices",
  "98.0": "/quote-invoices",
  "99.0": "/payments",
  "100.0": "/money-cost",
  "101.0": "/fx-differences",
  "102.0": "/cashflows",
  "103.0": "/cost-to-serve",
  "104.0": "/bookkeeping",
  "105.0": "/invoices",
  "106.0": "/finance",
  "107.0": "/gdpr",
  "108.0": "/road",
  "109.0": "/rail",
  "110.0": "/china-rail",
  "111.0": "/lcl",
  "113.0": "/claims",
  "114.0": "/fraud",
  "116.0": "/watchtower",
  "117.0": "/finance",
  "118.0": "/ai",
  "120.0": "/party-scorecards",
  "121.0": "/decisions",
  "122.0": "/mail",
  "123.0": "/notifications",
  "124.0": "/watchtower",
  "129.0": "/charges",
  "130.0": "/networks",
  "131.0": "/parties",
  "132.0": "/parties",
  "133.0": "/entity-events",
  "134.0": "/quotations",
  "135.0": "/quotations",
  "136.0": "/networks",
  "137.0": "/quotations",
  "138.0": "/networks",
  "139.0": "/party-scorecards",
  "140.0": "/ai",
  "141.0": "/networks",
  "142.0": "/mail",
  "143.0": "/networks",
  "144.0": "/quotations",
  "145.0": "/quotations",
  "146.0": "/shipments",
  "147.0": "/quotations",
  "148.0": "/shipments",
  "149.0": "/organization-settings",
  "150.0": "/shipments",
  "151.0": "/shipments",
  "152.0": "/shipments",
  "153.0": "/shipments",
  "154.0": "/air",
  "155.0": "/groupage",
  "156.0": "/shipment-packages",
  "157.0": "/dock-appointments",
  "158.0": "/cod",
  "159.0": "/groupage-tariffs",
  "160.0": "/ocean-bills",
  "161.0": "/pallet-balances",
  "162.0": "/document-templates",
  "163.0": "/rate-cards",
  "164.0": "/charge-templates",
  "165.0": "/fuel-indexes",
  "166.0": "/local-charges",
  "167.0": "/shipments",
  "168.0": "/tender-quotes",
  "169.0": "/tenders",
  "170.0": "/tender-lots",
  "171.0": "/tender-lanes",
  "172.0": "/tender-rounds",
  "173.0": "/tender-data-rooms",
  "174.0": "/tender-matrix-cells",
  "175.0": "/tender-playbooks",
  "176.0": "/tender-win-losses",
  "177.0": "/tender-consortium-members",
  "178.0": "/tender-rfp-intakes",
  "179.0": "/ai",
  "180.0": "/tender-prospects",
  "181.0": "/tender-bid-stances",
  "182.0": "/tender-award-reviews",
  "183.0": "/tender-ted-notices",
  "184.0": "/tender-carbon-marks",
  "185.0": "/lane-patterns",
  "186.0": "/kreptd-licences",
  "187.0": "/monitoring-schemes",
  "188.0": "/party-documents",
  "189.0": "/cash-discounts",
  "190.0": "/carbon-methods",
  "191.0": "/claims",
  "192.0": "/dangerous-goods",
  "193.0": "/prediction-ledgers",
  "194.0": "/shipments",
  "195.0": "/weather-observations",
  "196.0": "/free-time-clocks",
  "197.0": "/telematics-connectors",
  "198.0": "/tower-impacts",
  "199.0": "/twin-marks",
  "200.0": "/war-room-marks",
  "201.0": "/memory-edges",
  "202.0": "/executive-marks",
  "203.0": "/rank-marks",
  "204.0": "/shipments",
  "205.0": "/rate-cards",
  "206.0": "/charge-templates",
  "207.0": "/local-charges",
  "208.0": "/local-charges",
  "209.0": "/air",
  "210.0": "/shipments",
  "211.0": "/organization-settings",
  "212.0": "/shipments",
  "213.0": "/shipments",
  "214.0": "/shipments",
  "215.0": "/shipments",
  "216.0": "/shipments",
  "217.0": "/shipments",
  "218.0": "/shipments",
  "219.0": "/shipments",
  "220.0": "/shipments",
  "221.0": "/shipments",
  "222.0": "/shipments",
  "223.0": "/shipments",
  "224.0": "/shipments",
  "225.0": "/shipments",
  "226.0": "/shipments",
  "227.0": "/shipments",
  "228.0": "/shipments",
  "229.0": "/shipments",
  "230.0": "/shipments",
  "231.0": "/shipments",
  "232.0": "/shipments",
  "233.0": "/shipments",
  "234.0": "/shipments",
  "235.0": "/shipments",
  "236.0": "/shipments",
  "237.0": "/shipments",
  "238.0": "/shipments",
  "239.0": "/shipments",
  "240.0": "/shipments",
  "241.0": "/shipments",
  "242.0": "/shipments",
  "243.0": "/shipments",
  "244.0": "/entity-events",
  "245.0": "/entity-events",
  "246.0": "/entity-events",
  "247.0": "/shipments",
  "248.0": "/shipments",
  "249.0": "/shipments",
  "250.0": "/shipments",
  "251.0": "/shipments",
  "252.0": "/shipments",
  "253.0": "/shipments",
  "254.0": "/shipments",
  "255.0": "/shipments",
  "256.0": "/shipments",
  "257.0": "/shipments",
  "258.0": "/shipments",
  "259.0": "/fleet",
  "260.0": "/consignments",
  "261.0": "/planning",
  "262.0": "/charges",
  "263.0": "/task-templates",
  "264.0": "/outbox",
  "265.0": "/plan-snapshots",
  "266.0": "/circle-sims",
  "267.0": "/lane-kms",
  "268.0": "/erp-connectors",
  "269.0": "/terminal-slot-connectors",
  "270.0": "/idp-connectors",
  "271.0": "/exchange-connectors",
  "272.0": "/customer-contracts",
  "273.0": "/customer-contracts",
  "274.0": "/tenant-contract-keks",
  "275.0": "/visibility-connectors",
  "276.0": "/purchase-orders",
  "277.0": "/po-lines",
  "278.0": "/asns",
  "279.0": "/routing-guides",
  "280.0": "/otif-marks",
  "281.0": "/sap-connectors",
  "282.0": "/capa-marks",
  "283.0": "/freight-audit-marks",
  "284.0": "/collaboration-marks",
  "285.0": "/routing-guide-enforcements",
  "286.0": "/asns",
  "287.0": "/shipments",
  "288.0": "/routing-guide-matches",
} as const

export const ROUTES_BREADTH_STANDING =
  "Nowe BC z jobem operatora = trasa w tym samym plasterze. Charge 1.0–1.2 już mają UI. To standing, nie 70 modułów."
