import { createElement } from "react"
import { renderToStaticMarkup } from "react-dom/server"
import { describe, expect, it } from "vitest"
import { OpsIndex } from "@/features/ops/ops-index-page"
import {
  OPS_JOBS,
  ROUTES_BREADTH_STANDING,
  SHIPPED_CHARGE_ROUTES,
} from "@/features/ops/ops-index"

describe("U-routes-breadth standing", () => {
  it("records Charge 1.0–1.2 routes and refuses a 70-module claim", () => {
    // Pełna kopia mapy vs ops-index puchła jscpd — próbki + długość.
    expect(SHIPPED_CHARGE_ROUTES["1.0"]).toBe("/charge-codes")
    expect(SHIPPED_CHARGE_ROUTES["1.1"]).toBe("/rate-lines")
    expect(SHIPPED_CHARGE_ROUTES["1.2"]).toBe("/charges")
    expect(SHIPPED_CHARGE_ROUTES["2.0"]).toBe("/quotations")
    expect(SHIPPED_CHARGE_ROUTES["447.0"]).toBe("/extractions")
    expect(SHIPPED_CHARGE_ROUTES["499.0"]).toBe("/shipper-award-marks")
    expect(SHIPPED_CHARGE_ROUTES["502.0"]).toBe("/extraction-prompt-marks")
    expect(SHIPPED_CHARGE_ROUTES["503.0"]).toBe("/extractions")
    expect(SHIPPED_CHARGE_ROUTES["504.0"]).toBe("/extractions")
    expect(SHIPPED_CHARGE_ROUTES["505.0"]).toBe("/organization-settings")
    expect(SHIPPED_CHARGE_ROUTES["506.0"]).toBe("/extractions")
    expect(SHIPPED_CHARGE_ROUTES["507.0"]).toBe("/extractions")
    expect(SHIPPED_CHARGE_ROUTES["508.0"]).toBe("/extractions")
    expect(SHIPPED_CHARGE_ROUTES["512.0"]).toBe("/extractions")
    expect(SHIPPED_CHARGE_ROUTES["514.0"]).toBe("/extractions")
    expect(SHIPPED_CHARGE_ROUTES["515.0"]).toBe("/extractions")
    expect(SHIPPED_CHARGE_ROUTES["516.0"]).toBe("/allocation-keys")
    expect(SHIPPED_CHARGE_ROUTES["517.0"]).toBe("/cost-category-marks")
    expect(SHIPPED_CHARGE_ROUTES["518.0"]).toBe("/allocation-levels")
    expect(SHIPPED_CHARGE_ROUTES["519.0"]).toBe("/impact-node-marks")
    expect(SHIPPED_CHARGE_ROUTES["520.0"]).toBe("/impact-edge-marks")
    expect(SHIPPED_CHARGE_ROUTES["521.0"]).toBe("/article50-marks")
    expect(SHIPPED_CHARGE_ROUTES["522.0"]).toBe("/data-sources")
    expect(SHIPPED_CHARGE_ROUTES["523.0"]).toBe("/ingest-gate-marks")
    expect(SHIPPED_CHARGE_ROUTES["524.0"]).toBe("/model-feature-marks")
    expect(SHIPPED_CHARGE_ROUTES["525.0"]).toBe("/cfo-narrative-marks")
    expect(SHIPPED_CHARGE_ROUTES["526.0"]).toBe("/kpi-definition-marks")
    expect(SHIPPED_CHARGE_ROUTES["527.0"]).toBe("/margin-floors")
    expect(SHIPPED_CHARGE_ROUTES["528.0"]).toBe("/shipment-clone-marks")
    expect(SHIPPED_CHARGE_ROUTES["529.0"]).toBe("/handover-sbar-marks")
    expect(SHIPPED_CHARGE_ROUTES["530.0"]).toBe("/trip-bill-marks")
    expect(SHIPPED_CHARGE_ROUTES["532.0"]).toBe("/networks")
    expect(SHIPPED_CHARGE_ROUTES["533.0"]).toBe("/networks")
    expect(SHIPPED_CHARGE_ROUTES["534.0"]).toBe("/entity-events")
    expect(SHIPPED_CHARGE_ROUTES["535.0"]).toBe("/networks")
    expect(SHIPPED_CHARGE_ROUTES["536.0"]).toBe("/mail")
    expect(SHIPPED_CHARGE_ROUTES["537.0"]).toBe("/extractions")
    expect(SHIPPED_CHARGE_ROUTES["538.0"]).toBe("/mail")
    expect(SHIPPED_CHARGE_ROUTES["539.0"]).toBe("/charges")
    expect(SHIPPED_CHARGE_ROUTES["540.0"]).toBe("/consignments")
    expect(SHIPPED_CHARGE_ROUTES["541.0"]).toBe("/shipment-packages")
    expect(SHIPPED_CHARGE_ROUTES["542.0"]).toBe("/consignments")
    expect(SHIPPED_CHARGE_ROUTES["543.0"]).toBe("/handover-notes")
    expect(SHIPPED_CHARGE_ROUTES["544.0"]).toBe("/charges")
    expect(SHIPPED_CHARGE_ROUTES["545.0"]).toBe("/product-tickets")
    expect(SHIPPED_CHARGE_ROUTES["546.0"]).toBe("/product-tickets")
    expect(SHIPPED_CHARGE_ROUTES["547.0"]).toBe("/charges")
    expect(SHIPPED_CHARGE_ROUTES["548.0"]).toBe("/self-billing-marks")
    expect(SHIPPED_CHARGE_ROUTES["549.0"]).toBe("/purchase-invoices")
    expect(SHIPPED_CHARGE_ROUTES["550.0"]).toBe("/invoice-match-marks")
    expect(SHIPPED_CHARGE_ROUTES["551.0"]).toBe("/invoice-alloc-marks")
    expect(SHIPPED_CHARGE_ROUTES["552.0"]).toBe("/postal-dispatch-marks")
    expect(SHIPPED_CHARGE_ROUTES["555.0"]).toBe("/invoice-match-candidates")
    expect(SHIPPED_CHARGE_ROUTES["556.0"]).toBe("/create-block-marks")
    expect(SHIPPED_CHARGE_ROUTES["557.0"]).toBe("/document-kind-match-marks")
    expect(SHIPPED_CHARGE_ROUTES["558.0"]).toBe("/filing-bind-marks")
    expect(SHIPPED_CHARGE_ROUTES["559.0"]).toBe("/postal-epo-marks")
    expect(SHIPPED_CHARGE_ROUTES["560.0"]).toBe("/blocks-create-enforcement-marks")
    expect(SHIPPED_CHARGE_ROUTES["561.0"]).toBe("/filing-fk-marks")
    expect(SHIPPED_CHARGE_ROUTES["562.0"]).toBe("/ais-import-marks")
    expect(SHIPPED_CHARGE_ROUTES["563.0"]).toBe("/waste-marks")
    expect(SHIPPED_CHARGE_ROUTES["564.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["565.0"]).toBe("/blank-sailing-marks")
    expect(SHIPPED_CHARGE_ROUTES["566.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["567.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["568.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["569.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["570.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["571.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["572.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["573.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["574.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["575.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["576.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["577.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["578.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["579.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["580.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["581.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["582.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["583.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["584.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["585.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["586.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["587.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["589.0"]).toBe("/fleet")
    expect(SHIPPED_CHARGE_ROUTES["590.0"]).toBe("/fleet")
    expect(SHIPPED_CHARGE_ROUTES["591.0"]).toBe("/fleet")
    expect(SHIPPED_CHARGE_ROUTES["592.0"]).toBe("/fleet")
    expect(SHIPPED_CHARGE_ROUTES["593.0"]).toBe("/fleet")
    expect(SHIPPED_CHARGE_ROUTES["594.0"]).toBe("/fleet")
    expect(SHIPPED_CHARGE_ROUTES["595.0"]).toBe("/fleet")
    expect(SHIPPED_CHARGE_ROUTES["596.0"]).toBe("/fleet")
    expect(SHIPPED_CHARGE_ROUTES["597.0"]).toBe("/fleet")
    expect(SHIPPED_CHARGE_ROUTES["598.0"]).toBe("/fleet")
    expect(SHIPPED_CHARGE_ROUTES["599.0"]).toBe("/fleet")
    expect(SHIPPED_CHARGE_ROUTES["600.0"]).toBe("/stop-groups")
    expect(SHIPPED_CHARGE_ROUTES["601.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["602.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["603.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["604.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["605.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["606.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["607.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["608.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["609.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["610.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["611.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["612.0"]).toBe("/shipments")
    expect(SHIPPED_CHARGE_ROUTES["613.0"]).toBe("/charges")
    expect(SHIPPED_CHARGE_ROUTES["614.0"]).toBe("/charges")
    expect(SHIPPED_CHARGE_ROUTES["615.0"]).toBe("/charges")
    expect(SHIPPED_CHARGE_ROUTES["616.0"]).toBe("/tasks")
    expect(SHIPPED_CHARGE_ROUTES["617.0"]).toBe("/organization-settings")
    expect(SHIPPED_CHARGE_ROUTES["618.0"]).toBe("/charges")
    expect(SHIPPED_CHARGE_ROUTES["619.0"]).toBe("/air")
    expect(SHIPPED_CHARGE_ROUTES["620.0"]).toBe("/channel-quotes")
    expect(SHIPPED_CHARGE_ROUTES["621.0"]).toBe("/ocean-bills")
    expect(SHIPPED_CHARGE_ROUTES["622.0"]).toBe("/air")
    expect(SHIPPED_CHARGE_ROUTES["623.0"]).toBe("/pallet-balances")
    expect(SHIPPED_CHARGE_ROUTES["624.0"]).toBe("/shipment-documents")
    expect(Object.keys(SHIPPED_CHARGE_ROUTES)).toHaveLength(564)

    expect(OPS_JOBS.map((job) => job.route)).toEqual(
      expect.arrayContaining(Object.values(SHIPPED_CHARGE_ROUTES)),
    )
    expect(OPS_JOBS).toHaveLength(338)

    expect(OPS_JOBS.length).not.toBe(157)

    const html = renderToStaticMarkup(
      createElement(OpsIndex, { healthLabel: "ok", healthState: "ok" }),
    )
    expect(html).toContain(ROUTES_BREADTH_STANDING)
    expect(html).toContain('data-routes-breadth="standing"')
    expect(html).not.toContain("70 modułów done")
    expect(html).not.toContain("powierzchnia 2026")
  })
})
