import { Link } from "@tanstack/react-router"
import { cn } from "@/lib/utils"

const NAV = [
  { to: "/", label: "Pulpit" },
  { to: "/tenancy/users", label: "Użytkownicy" },
  { to: "/extractions", label: "Ekstrakcje" },
  { to: "/finance", label: "Tablica finansowa" },
  { to: "/invoices", label: "Faktury" },
  { to: "/quote-invoices", label: "Rozliczenie wyceny" },
  { to: "/payments", label: "Bank i płatności" },
  { to: "/money-cost", label: "Koszt pieniądza" },
  { to: "/fx-differences", label: "Różnice kursowe" },
  { to: "/cashflows", label: "Przepływy" },
  { to: "/cost-to-serve", label: "Koszt obsługi klienta" },
  { to: "/bookkeeping", label: "Księgowość" },
  { to: "/road", label: "Transport drogowy" },
  { to: "/rail", label: "Kolej intermodalna" },
  { to: "/china-rail", label: "Kolej z Chin" },
  { to: "/lcl", label: "Drobnica morska" },
  { to: "/ocean-bills", label: "Konosament LCL" },
  { to: "/consignments", label: "Przesyłki" },
  { to: "/stop-groups", label: "Grupy punktów" },
  { to: "/air", label: "Lotniczy" },
  { to: "/groupage", label: "Linie drobnicy" },
  { to: "/groupage-tariffs", label: "Cennik drobnicy" },
  { to: "/shipment-packages", label: "Paczki" },
  { to: "/dock-appointments", label: "Awizacje doku" },
  { to: "/cod", label: "Pobranie COD" },
  { to: "/sanctions", label: "Sankcje" },
  { to: "/fraud", label: "Oszustwo" },
  { to: "/gdpr", label: "RODO" },
  { to: "/ai", label: "Propozycje AI" },
  { to: "/health", label: "Obserwowalność" },
  { to: "/quality", label: "Jakość ekstrakcji" },
  { to: "/rollout", label: "Wdrożenie" },
  { to: "/mail", label: "Poczta" },
  { to: "/notifications", label: "Powiadomienia" },
  { to: "/outbox", label: "Outbox" },
  { to: "/entity-events", label: "Zdarzenia podmiotu" },
  { to: "/shipments", label: "Zlecenia" },
  { to: "/fleet", label: "Flota" },
  { to: "/planning", label: "Planowanie" },
  { to: "/tracking", label: "Tracking" },
  { to: "/exceptions", label: "Wyjątki" },
  { to: "/claims", label: "Reklamacje ładunku" },
  { to: "/watchtower", label: "Wieża" },
  { to: "/shipment-documents", label: "Dokumenty zlecenia" },
  { to: "/edi", label: "EDI" },
  { to: "/charge-codes", label: "Kody opłat" },
  { to: "/charge-templates", label: "Szablony opłat" },
  { to: "/commodity-codes", label: "Kody towarowe" },
  { to: "/dangerous-goods", label: "Towary niebezpieczne" },
  { to: "/networks", label: "Sieci" },
  { to: "/nbp-rates", label: "Kursy NBP" },
  { to: "/fuel-indexes", label: "Indeksy paliwowe" },
  { to: "/charges", label: "Opłaty" },
  { to: "/channel-quotes", label: "Oferty kanału" },
  { to: "/rate-lines", label: "Stawki" },
  { to: "/rate-cards", label: "Karty stawek" },
  { to: "/quotations", label: "Wyceny" },
  { to: "/ports", label: "Porty" },
  { to: "/port-surcharges", label: "Opłaty portowe" },
  { to: "/local-charges", label: "Dopłaty lokalne" },
  { to: "/tender-data-rooms", label: "Pokoje danych" },
  { to: "/tender-matrix-cells", label: "Komórki matrycy" },
  { to: "/tender-playbooks", label: "Playbook przetargu" },
  { to: "/tender-win-losses", label: "Wynik przetargu" },
  { to: "/tender-consortium-members", label: "Konsorcjum przetargu" },
  { to: "/tender-rfp-intakes", label: "Przyjęcie RFP" },
  { to: "/tender-prospects", label: "Prospekt przetargu" },
  { to: "/tender-bid-stances", label: "Udział w przetargu" },
  { to: "/tender-carbon-marks", label: "Ślad węglowy przetargu" },
  { to: "/lane-patterns", label: "Wzorzec korytarza" },
  { to: "/kreptd-licences", label: "Licencja KREPTD" },
  { to: "/monitoring-schemes", label: "Schemat monitoringu" },
  { to: "/party-documents", label: "Dokument kontrahenta" },
  { to: "/cash-discounts", label: "Skonto" },
  { to: "/carbon-methods", label: "Metodyka CO₂" },
  { to: "/prediction-ledgers", label: "Ledger predykcji" },
  { to: "/suggestion-ledgers", label: "Ledger podpowiedzi" },
  { to: "/outcome-ledgers", label: "Ledger wyniku" },
  { to: "/interval-scores", label: "Wynik przedziału" },
  { to: "/version-scores", label: "Wynik wersji" },
  { to: "/version-windows", label: "Wynik okna wersji" },
  { to: "/outcome-kinds", label: "Rodzaj wyniku" },
  { to: "/counterfactual-runs", label: "Przebieg what-if" },
  { to: "/benefit-ledgers", label: "Ledger oszczędności" },
  { to: "/suggestion-kinds", label: "Rodzaj podpowiedzi" },
  { to: "/autonomy-levels", label: "Poziom autonomii" },
  { to: "/allocation-keys", label: "Klucz alokacji" },
  { to: "/allocation-levels", label: "Poziom alokacji" },
  { to: "/cost-category-marks", label: "Kategoria kosztu" },
  { to: "/impact-edge-marks", label: "Krawedz skutku" },
  { to: "/impact-node-marks", label: "Wezel skutku" },
  { to: "/plan-snapshots", label: "Migawka planu" },
  { to: "/circle-sims", label: "Kółko" },
  { to: "/route-plan-marks", label: "Znacznik planu trasy" },
  { to: "/crm-opportunities", label: "Okazja CRM" },
  { to: "/crm-activities", label: "Aktywność CRM" },
  { to: "/crm-pipeline-marks", label: "Etap CRM" },
  { to: "/crm-dedup-marks", label: "Dedup CRM" },
  { to: "/crm-link-marks", label: "Link CRM" },
  { to: "/sales-bind-marks", label: "Bind sprzedaży" },
  { to: "/shipper-bind-marks", label: "Bind załadowcy" },
  { to: "/shipper-award-marks", label: "Award załadowcy" },
  { to: "/extraction-prompt-marks", label: "Prompt ekstrakcji" },
  { to: "/sales-lanes", label: "Korytarz sprzedażowy" },
  { to: "/shipper-like-marks", label: "Like-for-like załadowcy" },
  { to: "/shipper-round-marks", label: "Runda załadowcy" },
  { to: "/shipper-tender-marks", label: "Przetarg załadowcy" },
  { to: "/campaign-marks", label: "Kampania marketingowa" },
  { to: "/groupage-dispatcher-marks", label: "Dyspozytor drobnicy" },
  { to: "/load-order-marks", label: "Kolejność załadunku" },
  { to: "/tacho-plan-marks", label: "Tacho w planie" },
  { to: "/ferry-booking-marks", label: "Rezerwacja promu" },
  { to: "/oog-permit-marks", label: "Zezwolenie OOG" },
  { to: "/lcl-console-marks", label: "Konsola LCL" },
  { to: "/nac-marks", label: "NAC i agent" },
  { to: "/silk-corridor-marks", label: "Jedwabny Szlak" },
  { to: "/factoring-connectors", label: "Faktoring" },
  { to: "/po-financing-marks", label: "PO Financing" },
  { to: "/wms-flow-marks", label: "Przepływ WMS" },
  { to: "/rfid-marks", label: "RFID magazyn" },
  { to: "/inventory-finance-marks", label: "Zapas finansowy" },
  { to: "/inventory-collateral-marks", label: "Zabezpieczenie na towarze" },
  { to: "/ops-room-marks", label: "Sala operacyjna" },
  { to: "/line-impact-layer-marks", label: "Warstwa liczona linii" },
  { to: "/product-ticket-marks", label: "Stancja ticketu" },
  { to: "/product-tickets", label: "Ticket produktu" },
  { to: "/self-billing-marks", label: "Self-billing" },
  { to: "/purchase-invoices", label: "FV zakupu" },
  { to: "/risk-register-marks", label: "Rejestr ryzyka" },
  { to: "/article50-marks", label: "Art. 50" },
  { to: "/data-sources", label: "Zrodla danych" },
  { to: "/ingest-gate-marks", label: "Brama ingest" },
  { to: "/model-feature-marks", label: "Cecha modelu" },
  { to: "/cfo-narrative-marks", label: "Narracja CFO" },
  { to: "/kpi-definition-marks", label: "Definicja KPI" },
  { to: "/margin-floors", label: "Podłoga marży" },
  { to: "/shipment-clone-marks", label: "Intencja klonu" },
  { to: "/handover-sbar-marks", label: "Przekazanie SBAR" },
  { to: "/handover-notes", label: "Notatka SBAR" },
  { to: "/trip-bill-marks", label: "Gotowość do FV" },
  { to: "/automation-bias-marks", label: "Automation bias" },
  { to: "/l3-gate-marks", label: "Brama L3" },
  { to: "/style-cascade-marks", label: "Kaskada stylu" },
  { to: "/style-fidelity-marks", label: "STYLE FIDELITY" },
  { to: "/quality-descent-marks", label: "Zejście jakości" },
  { to: "/field-confidence-marks", label: "Pewność per pole" },
  { to: "/compliance-program-marks", label: "Program zgodności" },
  { to: "/position-events", label: "Zdarzenie pozycji" },
  { to: "/telematics-devices", label: "Urządzenie telematyczne" },
  { to: "/tracking-consents", label: "Zgoda na śledzenie" },
  { to: "/lane-kms", label: "Km ładowny" },
  { to: "/erp-connectors", label: "Konektor Optima" },
  { to: "/idp-connectors", label: "Konektor Auth0" },
  { to: "/customer-contracts", label: "Umowa klienta" },
  { to: "/tenant-contract-keks", label: "Znacznik KEK" },
  { to: "/visibility-connectors", label: "Konektor widoczności" },
  { to: "/purchase-orders", label: "Zamówienie zakupu" },
  { to: "/po-lines", label: "Linia zamówienia" },
  { to: "/asns", label: "Awizo wysyłki" },
  { to: "/routing-guide-enforcements", label: "Egzekucja przewodnika" },
  { to: "/routing-guide-matches", label: "Dopasowanie przewodnika" },
  { to: "/routing-guides", label: "Przewodnik routingu" },
  { to: "/otif-marks", label: "Znacznik OTIF" },
  { to: "/sap-connectors", label: "Konektor SAP/Oracle" },
  { to: "/capa-marks", label: "Znacznik CAPA" },
  { to: "/freight-audit-marks", label: "Audyt frachtu" },
  { to: "/collaboration-marks", label: "Współpraca 3 stron" },
  { to: "/exchange-connectors", label: "Konektor giełdy" },
  { to: "/terminal-slot-connectors", label: "Konektor slotu" },
  { to: "/weather-observations", label: "Pogoda" },
  { to: "/free-time-clocks", label: "Zegar DD" },
  { to: "/telematics-connectors", label: "Konektor GPS" },
  { to: "/tower-impacts", label: "Skutek wieży" },
  { to: "/twin-kinds", label: "Rodzaj bliźniaka" },
  { to: "/twin-marks", label: "Bliźniak" },
  { to: "/war-room-marks", label: "Sala kryzysowa" },
  { to: "/memory-edges", label: "Krawędź pamięci" },
  { to: "/executive-marks", label: "Pytanie zarządu" },
  { to: "/rank-marks", label: "Oś rankingu" },
  { to: "/task-templates", label: "Szablon zadania" },
  { to: "/tasks", label: "Zadanie" },
  { to: "/tender-award-reviews", label: "Cztery oczy nagrody" },
  { to: "/tender-ted-notices", label: "Ogłoszenie TED" },
  { to: "/tender-lanes", label: "Korytarze przetargu" },
  { to: "/tender-lots", label: "Partie przetargu" },
  { to: "/tender-rounds", label: "Rundy przetargu" },
  { to: "/tender-quotes", label: "Oferty przetargowe" },
  { to: "/tenders", label: "Przetargi" },
  { to: "/locations", label: "Lokalizacje" },
  { to: "/terminals", label: "Terminale" },
  { to: "/parties", label: "Kontrahenci" },
  { to: "/pallet-balances", label: "Saldo palet" },
  { to: "/document-templates", label: "Szablony wydruku" },
  { to: "/party-scorecards", label: "Karty wyników" },
  { to: "/customer-sops", label: "Procedury klienta" },
  { to: "/credit-reviews", label: "Recenzje kredytowe" },
  { to: "/decisions", label: "Decyzje" },
  { to: "/organization-settings", label: "Ustawienia" },
  { to: "/session", label: "Sesja" },
] as const

export function Sidebar({ currentPath }: { currentPath: string }) {
  return (
    <aside
      data-admin-ref="sidebar-density"
      className="flex h-full min-h-0 w-44 shrink-0 flex-col overflow-y-auto border-r border-border bg-sidebar text-sidebar-foreground"
    >
      <div className="border-b border-border px-2 py-1.5">
        <div className="text-sm font-semibold tracking-tight">OmniRoute</div>
        <div className="text-[11px] text-sidebar-foreground/70">gęsty admin</div>
      </div>
      <nav className="flex flex-col gap-px p-1">
        {NAV.map((item) => {
          const active = currentPath === item.to
          return (
            <Link
              key={item.to}
              to={item.to}
              aria-current={active ? "page" : undefined}
              className={cn(
                "rounded-sm px-2 py-1 text-xs text-sidebar-foreground/80 hover:bg-sidebar-foreground/15 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
                active && "bg-sidebar-foreground/15 font-medium text-sidebar-foreground",
              )}
            >
              {item.label}
            </Link>
          )
        })}
      </nav>
      <div className="mt-auto border-t border-border px-2 py-1.5 text-[11px] text-sidebar-foreground/70">
        ⌘K · akcje operatora
      </div>
    </aside>
  )
}
