// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateTableViewApiV1TenancyTableViewsPostData, CreateTableViewApiV1TenancyTableViewsPostErrors, CreateTableViewApiV1TenancyTableViewsPostResponses, DeleteTableViewApiV1TenancyTableViewsViewIdDeleteData, DeleteTableViewApiV1TenancyTableViewsViewIdDeleteErrors, DeleteTableViewApiV1TenancyTableViewsViewIdDeleteResponses, HealthHealthGetData, HealthHealthGetResponses, ListTableViewsApiV1TenancyTableViewsGetData, ListTableViewsApiV1TenancyTableViewsGetErrors, ListTableViewsApiV1TenancyTableViewsGetResponses, ListUsersApiV1TenancyUsersGetData, ListUsersApiV1TenancyUsersGetErrors, ListUsersApiV1TenancyUsersGetResponses, UpdateTableViewApiV1TenancyTableViewsViewIdPatchData, UpdateTableViewApiV1TenancyTableViewsViewIdPatchErrors, UpdateTableViewApiV1TenancyTableViewsViewIdPatchResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List Users
 */
export const listUsersApiV1TenancyUsersGet = <ThrowOnError extends boolean = false>(options: Options<ListUsersApiV1TenancyUsersGetData, ThrowOnError>): RequestResult<ListUsersApiV1TenancyUsersGetResponses, ListUsersApiV1TenancyUsersGetErrors, ThrowOnError> => (options.client ?? client).get<ListUsersApiV1TenancyUsersGetResponses, ListUsersApiV1TenancyUsersGetErrors, ThrowOnError>({ url: '/api/v1/tenancy/users', ...options });

/**
 * List Table Views
 */
export const listTableViewsApiV1TenancyTableViewsGet = <ThrowOnError extends boolean = false>(options: Options<ListTableViewsApiV1TenancyTableViewsGetData, ThrowOnError>): RequestResult<ListTableViewsApiV1TenancyTableViewsGetResponses, ListTableViewsApiV1TenancyTableViewsGetErrors, ThrowOnError> => (options.client ?? client).get<ListTableViewsApiV1TenancyTableViewsGetResponses, ListTableViewsApiV1TenancyTableViewsGetErrors, ThrowOnError>({ url: '/api/v1/tenancy/table-views', ...options });

/**
 * Create Table View
 */
export const createTableViewApiV1TenancyTableViewsPost = <ThrowOnError extends boolean = false>(options: Options<CreateTableViewApiV1TenancyTableViewsPostData, ThrowOnError>): RequestResult<CreateTableViewApiV1TenancyTableViewsPostResponses, CreateTableViewApiV1TenancyTableViewsPostErrors, ThrowOnError> => (options.client ?? client).post<CreateTableViewApiV1TenancyTableViewsPostResponses, CreateTableViewApiV1TenancyTableViewsPostErrors, ThrowOnError>({
    url: '/api/v1/tenancy/table-views',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Table View
 */
export const deleteTableViewApiV1TenancyTableViewsViewIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteTableViewApiV1TenancyTableViewsViewIdDeleteData, ThrowOnError>): RequestResult<DeleteTableViewApiV1TenancyTableViewsViewIdDeleteResponses, DeleteTableViewApiV1TenancyTableViewsViewIdDeleteErrors, ThrowOnError> => (options.client ?? client).delete<DeleteTableViewApiV1TenancyTableViewsViewIdDeleteResponses, DeleteTableViewApiV1TenancyTableViewsViewIdDeleteErrors, ThrowOnError>({ url: '/api/v1/tenancy/table-views/{view_id}', ...options });

/**
 * Update Table View
 */
export const updateTableViewApiV1TenancyTableViewsViewIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateTableViewApiV1TenancyTableViewsViewIdPatchData, ThrowOnError>): RequestResult<UpdateTableViewApiV1TenancyTableViewsViewIdPatchResponses, UpdateTableViewApiV1TenancyTableViewsViewIdPatchErrors, ThrowOnError> => (options.client ?? client).patch<UpdateTableViewApiV1TenancyTableViewsViewIdPatchResponses, UpdateTableViewApiV1TenancyTableViewsViewIdPatchErrors, ThrowOnError>({
    url: '/api/v1/tenancy/table-views/{view_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>): RequestResult<HealthHealthGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });
