// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AppUserResponse
 */
export type AppUserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
};

/**
 * BankAccountCreate
 */
export type BankAccountCreate = {
    /**
     * Iban
     */
    iban: string;
    /**
     * Currency
     */
    currency: string;
    /**
     * Bank Name
     */
    bank_name?: string | null;
    /**
     * Whitelist Status
     */
    whitelist_status?: string;
};

/**
 * BankAccountResponse
 */
export type BankAccountResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Party Id
     */
    party_id: string;
    /**
     * Iban
     */
    iban: string;
    /**
     * Currency
     */
    currency: string;
    /**
     * Bank Name
     */
    bank_name: string | null;
    /**
     * Whitelist Status
     */
    whitelist_status: string;
};

/**
 * CarrierProfileResponse
 */
export type CarrierProfileResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Party Id
     */
    party_id: string;
    /**
     * Scac Code
     */
    scac_code: string | null;
    /**
     * Is Nvocc
     */
    is_nvocc: boolean;
    /**
     * Rate Source Email
     */
    rate_source_email: string | null;
    /**
     * Api Adapter
     */
    api_adapter: string;
    /**
     * Dcsa Tnt Version
     */
    dcsa_tnt_version: string | null;
};

/**
 * CarrierProfileUpsert
 */
export type CarrierProfileUpsert = {
    /**
     * Scac Code
     */
    scac_code?: string | null;
    /**
     * Is Nvocc
     */
    is_nvocc?: boolean;
    /**
     * Rate Source Email
     */
    rate_source_email?: string | null;
    /**
     * Api Adapter
     */
    api_adapter?: string;
    /**
     * Dcsa Tnt Version
     */
    dcsa_tnt_version?: string | null;
};

/**
 * ChargeCodeCreate
 */
export type ChargeCodeCreate = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Aliases
     */
    aliases?: Array<string>;
};

/**
 * ChargeCodeResponse
 */
export type ChargeCodeResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Aliases
     */
    aliases: Array<string>;
};

/**
 * ChargeCreate
 */
export type ChargeCreate = {
    /**
     * Charge Code
     */
    charge_code: string;
    /**
     * Buy Amount
     */
    buy_amount: string;
    /**
     * Buy Currency
     */
    buy_currency: string;
    /**
     * Sell Amount
     */
    sell_amount: string;
    /**
     * Sell Currency
     */
    sell_currency: string;
    /**
     * Rate Line Id
     */
    rate_line_id?: string | null;
};

/**
 * ChargeOverrideCreate
 */
export type ChargeOverrideCreate = {
    /**
     * Charge Code
     */
    charge_code: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Currency
     */
    currency: string;
    /**
     * Lane Pattern
     */
    lane_pattern?: string | null;
    /**
     * Basis
     */
    basis?: string | null;
    /**
     * Source Ref
     */
    source_ref?: string | null;
};

/**
 * ChargeOverrideResponse
 */
export type ChargeOverrideResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Party Id
     */
    party_id: string;
    /**
     * Charge Code
     */
    charge_code: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Currency
     */
    currency: string;
    /**
     * Lane Pattern
     */
    lane_pattern: string | null;
    /**
     * Basis
     */
    basis: string | null;
    /**
     * Source Ref
     */
    source_ref: string;
};

/**
 * ChargeResponse
 */
export type ChargeResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * Charge Code
     */
    charge_code: string;
    /**
     * Buy Amount
     */
    buy_amount: string;
    /**
     * Buy Currency
     */
    buy_currency: string;
    /**
     * Sell Amount
     */
    sell_amount: string;
    /**
     * Sell Currency
     */
    sell_currency: string;
    /**
     * Margin Amount
     */
    margin_amount: string;
    /**
     * Margin Currency
     */
    margin_currency: string;
    /**
     * Rate Line Id
     */
    rate_line_id: string | null;
};

/**
 * ContactCreate
 */
export type ContactCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Position
     */
    position?: string | null;
    /**
     * Is Primary
     */
    is_primary?: boolean;
};

/**
 * ContactResponse
 */
export type ContactResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Party Id
     */
    party_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string | null;
    /**
     * Phone
     */
    phone: string | null;
    /**
     * Position
     */
    position: string | null;
    /**
     * Is Primary
     */
    is_primary: boolean;
};

/**
 * EmailDomainCreate
 */
export type EmailDomainCreate = {
    /**
     * Domain
     */
    domain: string;
    /**
     * Source Ref
     */
    source_ref?: string | null;
};

/**
 * EmailDomainResponse
 */
export type EmailDomainResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Party Id
     */
    party_id: string;
    /**
     * Domain
     */
    domain: string;
    /**
     * Source Ref
     */
    source_ref: string;
};

/**
 * ExtractRequest
 */
export type ExtractRequest = {
    /**
     * Source Ref
     */
    source_ref: string;
    /**
     * Input Text
     */
    input_text?: string | null;
    /**
     * Document Base64
     */
    document_base64?: string | null;
};

/**
 * ExtractionDraftResponse
 */
export type ExtractionDraftResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Source Ref
     */
    source_ref: string;
    /**
     * Input Text
     */
    input_text: string;
    /**
     * Payload
     */
    payload: {
        [key: string]: unknown;
    };
    /**
     * Reviewed By
     */
    reviewed_by: string | null;
    /**
     * Reviewed At
     */
    reviewed_at: string | null;
    /**
     * Rate Line Ids
     */
    rate_line_ids?: Array<string>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IbanDraftResponse
 */
export type IbanDraftResponse = {
    /**
     * Iban
     */
    iban: string;
    /**
     * Whitelist Status
     */
    whitelist_status: string;
};

/**
 * IbanLookupRequest
 */
export type IbanLookupRequest = {
    /**
     * Iban
     */
    iban: string;
};

/**
 * LocationResponse
 */
export type LocationResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code: string | null;
    /**
     * Port Id
     */
    port_id: string | null;
    /**
     * Country Code
     */
    country_code: string | null;
    /**
     * City
     */
    city: string | null;
    /**
     * Address Line
     */
    address_line: string | null;
    /**
     * Postal Code
     */
    postal_code: string | null;
    /**
     * Lat
     */
    lat: string | null;
    /**
     * Lng
     */
    lng: string | null;
    /**
     * Source Ref
     */
    source_ref: string;
};

/**
 * OrganizationSettingResponse
 */
export type OrganizationSettingResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * Setting Key
     */
    setting_key: string;
    /**
     * Setting Value
     */
    setting_value: string;
};

/**
 * OrganizationSettingUpsert
 */
export type OrganizationSettingUpsert = {
    /**
     * Setting Key
     */
    setting_key: string;
    /**
     * Setting Value
     */
    setting_value: string;
};

/**
 * PartyCreate
 */
export type PartyCreate = {
    /**
     * Legal Name
     */
    legal_name: string;
    /**
     * Country Code
     */
    country_code: string;
    /**
     * Roles
     */
    roles: Array<string>;
    /**
     * Tax Id
     */
    tax_id?: string | null;
    /**
     * Short Name
     */
    short_name?: string | null;
    /**
     * Credit Limit
     */
    credit_limit?: string | null;
    /**
     * Credit Currency
     */
    credit_currency?: string | null;
    /**
     * Lookup Source
     */
    lookup_source?: string | null;
};

/**
 * PartyDraftResponse
 */
export type PartyDraftResponse = {
    /**
     * Legal Name
     */
    legal_name: string;
    /**
     * Tax Id
     */
    tax_id: string;
    /**
     * Source
     */
    source: string;
    /**
     * Vies Valid
     */
    vies_valid: boolean | null;
};

/**
 * PartyLookupRequest
 */
export type PartyLookupRequest = {
    /**
     * Tax Id
     */
    tax_id: string;
    /**
     * Country Code
     */
    country_code: string;
};

/**
 * PartyResponse
 */
export type PartyResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * Legal Name
     */
    legal_name: string;
    /**
     * Short Name
     */
    short_name: string | null;
    /**
     * Tax Id
     */
    tax_id: string | null;
    /**
     * Country Code
     */
    country_code: string;
    /**
     * Roles
     */
    roles: Array<string>;
    /**
     * Credit Limit
     */
    credit_limit: string | null;
    /**
     * Credit Currency
     */
    credit_currency: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Source Ref
     */
    source_ref: string;
};

/**
 * PortCreate
 */
export type PortCreate = {
    /**
     * Unlocode
     */
    unlocode: string;
    /**
     * Name
     */
    name: string;
    /**
     * Country Code
     */
    country_code: string;
    /**
     * Lat
     */
    lat?: number | string | null;
    /**
     * Lng
     */
    lng?: number | string | null;
    /**
     * Is Seaport
     */
    is_seaport?: boolean;
    /**
     * Function Flags
     */
    function_flags?: Array<string>;
    /**
     * Aliases
     */
    aliases?: Array<string>;
};

/**
 * PortResponse
 */
export type PortResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * Unlocode
     */
    unlocode: string;
    /**
     * Name
     */
    name: string;
    /**
     * Country Code
     */
    country_code: string;
    /**
     * Lat
     */
    lat: string | null;
    /**
     * Lng
     */
    lng: string | null;
    /**
     * Is Seaport
     */
    is_seaport: boolean;
    /**
     * Function Flags
     */
    function_flags: Array<string>;
    /**
     * Aliases
     */
    aliases: Array<string>;
    /**
     * Is Official
     */
    is_official: boolean;
    /**
     * Source Ref
     */
    source_ref: string;
    /**
     * Wpi Number
     */
    wpi_number?: number | null;
    /**
     * Harbor Size
     */
    harbor_size?: string | null;
    /**
     * Harbor Type
     */
    harbor_type?: string | null;
    /**
     * Shelter
     */
    shelter?: string | null;
    /**
     * Channel Depth M
     */
    channel_depth_m?: string | null;
    /**
     * Cargo Pier Depth M
     */
    cargo_pier_depth_m?: string | null;
    /**
     * Wpi Source Ref
     */
    wpi_source_ref?: string | null;
};

/**
 * QuotationCreate
 */
export type QuotationCreate = {
    /**
     * Charge Code
     */
    charge_code: string;
    /**
     * Origin Port Id
     */
    origin_port_id: string;
    /**
     * Destination Port Id
     */
    destination_port_id: string;
    /**
     * Party Id
     */
    party_id: string;
};

/**
 * QuotationResponse
 */
export type QuotationResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * Charge Code
     */
    charge_code: string;
    /**
     * Rate Line Id
     */
    rate_line_id: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Currency
     */
    currency: string;
    /**
     * Source Ref
     */
    source_ref: string;
    /**
     * Origin Port Id
     */
    origin_port_id: string | null;
    /**
     * Destination Port Id
     */
    destination_port_id: string | null;
    /**
     * Party Id
     */
    party_id: string | null;
};

/**
 * RateLineCreate
 */
export type RateLineCreate = {
    /**
     * Charge Code
     */
    charge_code: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Currency
     */
    currency: string;
    /**
     * Source Ref
     */
    source_ref: string;
};

/**
 * RateLineResponse
 */
export type RateLineResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * Charge Code
     */
    charge_code: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Currency
     */
    currency: string;
    /**
     * Source Ref
     */
    source_ref: string;
    /**
     * Superseded By
     */
    superseded_by: string | null;
};

/**
 * RateLineSupersede
 */
export type RateLineSupersede = {
    /**
     * Amount
     */
    amount: string;
    /**
     * Currency
     */
    currency: string;
    /**
     * Source Ref
     */
    source_ref: string;
};

/**
 * SessionMeResponse
 */
export type SessionMeResponse = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Organization Id
     */
    organization_id: string;
};

/**
 * SessionRefreshRequest
 */
export type SessionRefreshRequest = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * SessionTokenRequest
 */
export type SessionTokenRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * SessionTokenResponse
 */
export type SessionTokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * TableViewConfig
 */
export type TableViewConfig = {
    /**
     * Column Order
     */
    column_order?: Array<string>;
    /**
     * Column Visibility
     */
    column_visibility?: {
        [key: string]: boolean;
    };
    /**
     * Filters
     */
    filters?: {
        [key: string]: unknown;
    };
    /**
     * Sorting
     */
    sorting?: Array<{
        [key: string]: string;
    }>;
    /**
     * Density
     */
    density?: string;
};

/**
 * TableViewCreate
 */
export type TableViewCreate = {
    /**
     * Table Key
     */
    table_key: string;
    /**
     * Name
     */
    name: string;
    config?: TableViewConfig;
};

/**
 * TableViewResponse
 */
export type TableViewResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Table Key
     */
    table_key: string;
    /**
     * Name
     */
    name: string;
    /**
     * Config
     */
    config: {
        [key: string]: unknown;
    };
};

/**
 * TableViewUpdate
 */
export type TableViewUpdate = {
    /**
     * Name
     */
    name?: string | null;
    config?: TableViewConfig | null;
};

/**
 * TerminalCreate
 */
export type TerminalCreate = {
    /**
     * Port Id
     */
    port_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Isps Code
     */
    isps_code?: string | null;
    /**
     * Operator Name
     */
    operator_name?: string | null;
    /**
     * Operator Party Id
     */
    operator_party_id?: string | null;
    /**
     * Lat
     */
    lat?: number | string | null;
    /**
     * Lng
     */
    lng?: number | string | null;
};

/**
 * TerminalResponse
 */
export type TerminalResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * Port Id
     */
    port_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Isps Code
     */
    isps_code: string | null;
    /**
     * Operator Name
     */
    operator_name: string | null;
    /**
     * Operator Party Id
     */
    operator_party_id: string | null;
    /**
     * Lat
     */
    lat: string | null;
    /**
     * Lng
     */
    lng: string | null;
    /**
     * Source Ref
     */
    source_ref: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * ZoneCreate
 */
export type ZoneCreate = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
};

/**
 * ZoneMemberCreate
 */
export type ZoneMemberCreate = {
    /**
     * Country Code
     */
    country_code: string;
    /**
     * Postal From
     */
    postal_from: string;
    /**
     * Postal To
     */
    postal_to: string;
};

/**
 * ZoneMemberResponse
 */
export type ZoneMemberResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * Zone Location Id
     */
    zone_location_id: string;
    /**
     * Country Code
     */
    country_code: string;
    /**
     * Postal From
     */
    postal_from: string;
    /**
     * Postal To
     */
    postal_to: string;
    /**
     * Source Ref
     */
    source_ref: string;
};

export type CreateSessionTokenApiV1SessionTokenPostData = {
    body: SessionTokenRequest;
    path?: never;
    query?: never;
    url: '/api/v1/session/token';
};

export type CreateSessionTokenApiV1SessionTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSessionTokenApiV1SessionTokenPostError = CreateSessionTokenApiV1SessionTokenPostErrors[keyof CreateSessionTokenApiV1SessionTokenPostErrors];

export type CreateSessionTokenApiV1SessionTokenPostResponses = {
    /**
     * Successful Response
     */
    201: SessionTokenResponse;
};

export type CreateSessionTokenApiV1SessionTokenPostResponse = CreateSessionTokenApiV1SessionTokenPostResponses[keyof CreateSessionTokenApiV1SessionTokenPostResponses];

export type RefreshSessionApiV1SessionRefreshPostData = {
    body: SessionRefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/session/refresh';
};

export type RefreshSessionApiV1SessionRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshSessionApiV1SessionRefreshPostError = RefreshSessionApiV1SessionRefreshPostErrors[keyof RefreshSessionApiV1SessionRefreshPostErrors];

export type RefreshSessionApiV1SessionRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: SessionTokenResponse;
};

export type RefreshSessionApiV1SessionRefreshPostResponse = RefreshSessionApiV1SessionRefreshPostResponses[keyof RefreshSessionApiV1SessionRefreshPostResponses];

export type ReadSessionApiV1SessionMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/session/me';
};

export type ReadSessionApiV1SessionMeGetResponses = {
    /**
     * Successful Response
     */
    200: SessionMeResponse;
};

export type ReadSessionApiV1SessionMeGetResponse = ReadSessionApiV1SessionMeGetResponses[keyof ReadSessionApiV1SessionMeGetResponses];

export type ListUsersApiV1TenancyUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenancy/users';
};

export type ListUsersApiV1TenancyUsersGetResponses = {
    /**
     * Response List Users Api V1 Tenancy Users Get
     *
     * Successful Response
     */
    200: Array<AppUserResponse>;
};

export type ListUsersApiV1TenancyUsersGetResponse = ListUsersApiV1TenancyUsersGetResponses[keyof ListUsersApiV1TenancyUsersGetResponses];

export type ListTableViewsApiV1TenancyTableViewsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Table Key
         */
        table_key: string;
    };
    url: '/api/v1/tenancy/table-views';
};

export type ListTableViewsApiV1TenancyTableViewsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTableViewsApiV1TenancyTableViewsGetError = ListTableViewsApiV1TenancyTableViewsGetErrors[keyof ListTableViewsApiV1TenancyTableViewsGetErrors];

export type ListTableViewsApiV1TenancyTableViewsGetResponses = {
    /**
     * Response List Table Views Api V1 Tenancy Table Views Get
     *
     * Successful Response
     */
    200: Array<TableViewResponse>;
};

export type ListTableViewsApiV1TenancyTableViewsGetResponse = ListTableViewsApiV1TenancyTableViewsGetResponses[keyof ListTableViewsApiV1TenancyTableViewsGetResponses];

export type CreateTableViewApiV1TenancyTableViewsPostData = {
    body: TableViewCreate;
    path?: never;
    query?: never;
    url: '/api/v1/tenancy/table-views';
};

export type CreateTableViewApiV1TenancyTableViewsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTableViewApiV1TenancyTableViewsPostError = CreateTableViewApiV1TenancyTableViewsPostErrors[keyof CreateTableViewApiV1TenancyTableViewsPostErrors];

export type CreateTableViewApiV1TenancyTableViewsPostResponses = {
    /**
     * Successful Response
     */
    201: TableViewResponse;
};

export type CreateTableViewApiV1TenancyTableViewsPostResponse = CreateTableViewApiV1TenancyTableViewsPostResponses[keyof CreateTableViewApiV1TenancyTableViewsPostResponses];

export type DeleteTableViewApiV1TenancyTableViewsViewIdDeleteData = {
    body?: never;
    path: {
        /**
         * View Id
         */
        view_id: string;
    };
    query?: never;
    url: '/api/v1/tenancy/table-views/{view_id}';
};

export type DeleteTableViewApiV1TenancyTableViewsViewIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTableViewApiV1TenancyTableViewsViewIdDeleteError = DeleteTableViewApiV1TenancyTableViewsViewIdDeleteErrors[keyof DeleteTableViewApiV1TenancyTableViewsViewIdDeleteErrors];

export type DeleteTableViewApiV1TenancyTableViewsViewIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTableViewApiV1TenancyTableViewsViewIdDeleteResponse = DeleteTableViewApiV1TenancyTableViewsViewIdDeleteResponses[keyof DeleteTableViewApiV1TenancyTableViewsViewIdDeleteResponses];

export type UpdateTableViewApiV1TenancyTableViewsViewIdPatchData = {
    body: TableViewUpdate;
    path: {
        /**
         * View Id
         */
        view_id: string;
    };
    query?: never;
    url: '/api/v1/tenancy/table-views/{view_id}';
};

export type UpdateTableViewApiV1TenancyTableViewsViewIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTableViewApiV1TenancyTableViewsViewIdPatchError = UpdateTableViewApiV1TenancyTableViewsViewIdPatchErrors[keyof UpdateTableViewApiV1TenancyTableViewsViewIdPatchErrors];

export type UpdateTableViewApiV1TenancyTableViewsViewIdPatchResponses = {
    /**
     * Successful Response
     */
    200: TableViewResponse;
};

export type UpdateTableViewApiV1TenancyTableViewsViewIdPatchResponse = UpdateTableViewApiV1TenancyTableViewsViewIdPatchResponses[keyof UpdateTableViewApiV1TenancyTableViewsViewIdPatchResponses];

export type ListExtractionDraftsApiV1ExtractionsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: string | null;
    };
    url: '/api/v1/extractions';
};

export type ListExtractionDraftsApiV1ExtractionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListExtractionDraftsApiV1ExtractionsGetError = ListExtractionDraftsApiV1ExtractionsGetErrors[keyof ListExtractionDraftsApiV1ExtractionsGetErrors];

export type ListExtractionDraftsApiV1ExtractionsGetResponses = {
    /**
     * Response List Extraction Drafts Api V1 Extractions Get
     *
     * Successful Response
     */
    200: Array<ExtractionDraftResponse>;
};

export type ListExtractionDraftsApiV1ExtractionsGetResponse = ListExtractionDraftsApiV1ExtractionsGetResponses[keyof ListExtractionDraftsApiV1ExtractionsGetResponses];

export type CreateExtractionDraftApiV1ExtractionsPostData = {
    body: ExtractRequest;
    path?: never;
    query?: never;
    url: '/api/v1/extractions';
};

export type CreateExtractionDraftApiV1ExtractionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateExtractionDraftApiV1ExtractionsPostError = CreateExtractionDraftApiV1ExtractionsPostErrors[keyof CreateExtractionDraftApiV1ExtractionsPostErrors];

export type CreateExtractionDraftApiV1ExtractionsPostResponses = {
    /**
     * Successful Response
     */
    201: ExtractionDraftResponse;
};

export type CreateExtractionDraftApiV1ExtractionsPostResponse = CreateExtractionDraftApiV1ExtractionsPostResponses[keyof CreateExtractionDraftApiV1ExtractionsPostResponses];

export type AcceptExtractionDraftApiV1ExtractionsDraftIdAcceptPostData = {
    body?: never;
    path: {
        /**
         * Draft Id
         */
        draft_id: string;
    };
    query?: never;
    url: '/api/v1/extractions/{draft_id}/accept';
};

export type AcceptExtractionDraftApiV1ExtractionsDraftIdAcceptPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AcceptExtractionDraftApiV1ExtractionsDraftIdAcceptPostError = AcceptExtractionDraftApiV1ExtractionsDraftIdAcceptPostErrors[keyof AcceptExtractionDraftApiV1ExtractionsDraftIdAcceptPostErrors];

export type AcceptExtractionDraftApiV1ExtractionsDraftIdAcceptPostResponses = {
    /**
     * Successful Response
     */
    200: ExtractionDraftResponse;
};

export type AcceptExtractionDraftApiV1ExtractionsDraftIdAcceptPostResponse = AcceptExtractionDraftApiV1ExtractionsDraftIdAcceptPostResponses[keyof AcceptExtractionDraftApiV1ExtractionsDraftIdAcceptPostResponses];

export type RejectExtractionDraftApiV1ExtractionsDraftIdRejectPostData = {
    body?: never;
    path: {
        /**
         * Draft Id
         */
        draft_id: string;
    };
    query?: never;
    url: '/api/v1/extractions/{draft_id}/reject';
};

export type RejectExtractionDraftApiV1ExtractionsDraftIdRejectPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RejectExtractionDraftApiV1ExtractionsDraftIdRejectPostError = RejectExtractionDraftApiV1ExtractionsDraftIdRejectPostErrors[keyof RejectExtractionDraftApiV1ExtractionsDraftIdRejectPostErrors];

export type RejectExtractionDraftApiV1ExtractionsDraftIdRejectPostResponses = {
    /**
     * Successful Response
     */
    200: ExtractionDraftResponse;
};

export type RejectExtractionDraftApiV1ExtractionsDraftIdRejectPostResponse = RejectExtractionDraftApiV1ExtractionsDraftIdRejectPostResponses[keyof RejectExtractionDraftApiV1ExtractionsDraftIdRejectPostResponses];

export type ListChargeCodesApiV1ChargeCodesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/charge-codes';
};

export type ListChargeCodesApiV1ChargeCodesGetResponses = {
    /**
     * Response List Charge Codes Api V1 Charge Codes Get
     *
     * Successful Response
     */
    200: Array<ChargeCodeResponse>;
};

export type ListChargeCodesApiV1ChargeCodesGetResponse = ListChargeCodesApiV1ChargeCodesGetResponses[keyof ListChargeCodesApiV1ChargeCodesGetResponses];

export type CreateChargeCodeApiV1ChargeCodesPostData = {
    body: ChargeCodeCreate;
    path?: never;
    query?: never;
    url: '/api/v1/charge-codes';
};

export type CreateChargeCodeApiV1ChargeCodesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateChargeCodeApiV1ChargeCodesPostError = CreateChargeCodeApiV1ChargeCodesPostErrors[keyof CreateChargeCodeApiV1ChargeCodesPostErrors];

export type CreateChargeCodeApiV1ChargeCodesPostResponses = {
    /**
     * Successful Response
     */
    201: ChargeCodeResponse;
};

export type CreateChargeCodeApiV1ChargeCodesPostResponse = CreateChargeCodeApiV1ChargeCodesPostResponses[keyof CreateChargeCodeApiV1ChargeCodesPostResponses];

export type ResolveChargeCodeApiV1ChargeCodesResolveGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Token
         */
        token: string;
    };
    url: '/api/v1/charge-codes/resolve';
};

export type ResolveChargeCodeApiV1ChargeCodesResolveGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResolveChargeCodeApiV1ChargeCodesResolveGetError = ResolveChargeCodeApiV1ChargeCodesResolveGetErrors[keyof ResolveChargeCodeApiV1ChargeCodesResolveGetErrors];

export type ResolveChargeCodeApiV1ChargeCodesResolveGetResponses = {
    /**
     * Successful Response
     */
    200: ChargeCodeResponse;
};

export type ResolveChargeCodeApiV1ChargeCodesResolveGetResponse = ResolveChargeCodeApiV1ChargeCodesResolveGetResponses[keyof ResolveChargeCodeApiV1ChargeCodesResolveGetResponses];

export type ListChargesApiV1ChargesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/charges';
};

export type ListChargesApiV1ChargesGetResponses = {
    /**
     * Response List Charges Api V1 Charges Get
     *
     * Successful Response
     */
    200: Array<ChargeResponse>;
};

export type ListChargesApiV1ChargesGetResponse = ListChargesApiV1ChargesGetResponses[keyof ListChargesApiV1ChargesGetResponses];

export type CreateChargeApiV1ChargesPostData = {
    body: ChargeCreate;
    path?: never;
    query?: never;
    url: '/api/v1/charges';
};

export type CreateChargeApiV1ChargesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateChargeApiV1ChargesPostError = CreateChargeApiV1ChargesPostErrors[keyof CreateChargeApiV1ChargesPostErrors];

export type CreateChargeApiV1ChargesPostResponses = {
    /**
     * Successful Response
     */
    201: ChargeResponse;
};

export type CreateChargeApiV1ChargesPostResponse = CreateChargeApiV1ChargesPostResponses[keyof CreateChargeApiV1ChargesPostResponses];

export type ListRateLinesApiV1RateLinesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/rate-lines';
};

export type ListRateLinesApiV1RateLinesGetResponses = {
    /**
     * Response List Rate Lines Api V1 Rate Lines Get
     *
     * Successful Response
     */
    200: Array<RateLineResponse>;
};

export type ListRateLinesApiV1RateLinesGetResponse = ListRateLinesApiV1RateLinesGetResponses[keyof ListRateLinesApiV1RateLinesGetResponses];

export type CreateRateLineApiV1RateLinesPostData = {
    body: RateLineCreate;
    path?: never;
    query?: never;
    url: '/api/v1/rate-lines';
};

export type CreateRateLineApiV1RateLinesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRateLineApiV1RateLinesPostError = CreateRateLineApiV1RateLinesPostErrors[keyof CreateRateLineApiV1RateLinesPostErrors];

export type CreateRateLineApiV1RateLinesPostResponses = {
    /**
     * Successful Response
     */
    201: RateLineResponse;
};

export type CreateRateLineApiV1RateLinesPostResponse = CreateRateLineApiV1RateLinesPostResponses[keyof CreateRateLineApiV1RateLinesPostResponses];

export type SupersedeRateLineApiV1RateLinesRateLineIdSupersedePostData = {
    body: RateLineSupersede;
    path: {
        /**
         * Rate Line Id
         */
        rate_line_id: string;
    };
    query?: never;
    url: '/api/v1/rate-lines/{rate_line_id}/supersede';
};

export type SupersedeRateLineApiV1RateLinesRateLineIdSupersedePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SupersedeRateLineApiV1RateLinesRateLineIdSupersedePostError = SupersedeRateLineApiV1RateLinesRateLineIdSupersedePostErrors[keyof SupersedeRateLineApiV1RateLinesRateLineIdSupersedePostErrors];

export type SupersedeRateLineApiV1RateLinesRateLineIdSupersedePostResponses = {
    /**
     * Successful Response
     */
    201: RateLineResponse;
};

export type SupersedeRateLineApiV1RateLinesRateLineIdSupersedePostResponse = SupersedeRateLineApiV1RateLinesRateLineIdSupersedePostResponses[keyof SupersedeRateLineApiV1RateLinesRateLineIdSupersedePostResponses];

export type ListQuotationsApiV1QuotationsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Party Id
         */
        party_id?: string | null;
        /**
         * Origin Port Id
         */
        origin_port_id?: string | null;
        /**
         * Destination Port Id
         */
        destination_port_id?: string | null;
    };
    url: '/api/v1/quotations';
};

export type ListQuotationsApiV1QuotationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListQuotationsApiV1QuotationsGetError = ListQuotationsApiV1QuotationsGetErrors[keyof ListQuotationsApiV1QuotationsGetErrors];

export type ListQuotationsApiV1QuotationsGetResponses = {
    /**
     * Response List Quotations Api V1 Quotations Get
     *
     * Successful Response
     */
    200: Array<QuotationResponse>;
};

export type ListQuotationsApiV1QuotationsGetResponse = ListQuotationsApiV1QuotationsGetResponses[keyof ListQuotationsApiV1QuotationsGetResponses];

export type CreateQuotationApiV1QuotationsPostData = {
    body: QuotationCreate;
    path?: never;
    query?: never;
    url: '/api/v1/quotations';
};

export type CreateQuotationApiV1QuotationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateQuotationApiV1QuotationsPostError = CreateQuotationApiV1QuotationsPostErrors[keyof CreateQuotationApiV1QuotationsPostErrors];

export type CreateQuotationApiV1QuotationsPostResponses = {
    /**
     * Successful Response
     */
    201: QuotationResponse;
};

export type CreateQuotationApiV1QuotationsPostResponse = CreateQuotationApiV1QuotationsPostResponses[keyof CreateQuotationApiV1QuotationsPostResponses];

export type ListOrganizationSettingsApiV1OrganizationSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/organization-settings';
};

export type ListOrganizationSettingsApiV1OrganizationSettingsGetResponses = {
    /**
     * Response List Organization Settings Api V1 Organization Settings Get
     *
     * Successful Response
     */
    200: Array<OrganizationSettingResponse>;
};

export type ListOrganizationSettingsApiV1OrganizationSettingsGetResponse = ListOrganizationSettingsApiV1OrganizationSettingsGetResponses[keyof ListOrganizationSettingsApiV1OrganizationSettingsGetResponses];

export type UpsertOrganizationSettingApiV1OrganizationSettingsPutData = {
    body: OrganizationSettingUpsert;
    path?: never;
    query?: never;
    url: '/api/v1/organization-settings';
};

export type UpsertOrganizationSettingApiV1OrganizationSettingsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpsertOrganizationSettingApiV1OrganizationSettingsPutError = UpsertOrganizationSettingApiV1OrganizationSettingsPutErrors[keyof UpsertOrganizationSettingApiV1OrganizationSettingsPutErrors];

export type UpsertOrganizationSettingApiV1OrganizationSettingsPutResponses = {
    /**
     * Successful Response
     */
    200: OrganizationSettingResponse;
};

export type UpsertOrganizationSettingApiV1OrganizationSettingsPutResponse = UpsertOrganizationSettingApiV1OrganizationSettingsPutResponses[keyof UpsertOrganizationSettingApiV1OrganizationSettingsPutResponses];

export type ListPartiesApiV1PartiesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/parties';
};

export type ListPartiesApiV1PartiesGetResponses = {
    /**
     * Response List Parties Api V1 Parties Get
     *
     * Successful Response
     */
    200: Array<PartyResponse>;
};

export type ListPartiesApiV1PartiesGetResponse = ListPartiesApiV1PartiesGetResponses[keyof ListPartiesApiV1PartiesGetResponses];

export type CreatePartyApiV1PartiesPostData = {
    body: PartyCreate;
    path?: never;
    query?: never;
    url: '/api/v1/parties';
};

export type CreatePartyApiV1PartiesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePartyApiV1PartiesPostError = CreatePartyApiV1PartiesPostErrors[keyof CreatePartyApiV1PartiesPostErrors];

export type CreatePartyApiV1PartiesPostResponses = {
    /**
     * Successful Response
     */
    201: PartyResponse;
};

export type CreatePartyApiV1PartiesPostResponse = CreatePartyApiV1PartiesPostResponses[keyof CreatePartyApiV1PartiesPostResponses];

export type ResolvePartyApiV1PartiesResolveGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Tax Id
         */
        tax_id: string;
    };
    url: '/api/v1/parties/resolve';
};

export type ResolvePartyApiV1PartiesResolveGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResolvePartyApiV1PartiesResolveGetError = ResolvePartyApiV1PartiesResolveGetErrors[keyof ResolvePartyApiV1PartiesResolveGetErrors];

export type ResolvePartyApiV1PartiesResolveGetResponses = {
    /**
     * Successful Response
     */
    200: PartyResponse;
};

export type ResolvePartyApiV1PartiesResolveGetResponse = ResolvePartyApiV1PartiesResolveGetResponses[keyof ResolvePartyApiV1PartiesResolveGetResponses];

export type LookupPartyApiV1PartiesLookupPostData = {
    body: PartyLookupRequest;
    path?: never;
    query?: never;
    url: '/api/v1/parties/lookup';
};

export type LookupPartyApiV1PartiesLookupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LookupPartyApiV1PartiesLookupPostError = LookupPartyApiV1PartiesLookupPostErrors[keyof LookupPartyApiV1PartiesLookupPostErrors];

export type LookupPartyApiV1PartiesLookupPostResponses = {
    /**
     * Successful Response
     */
    200: PartyDraftResponse;
};

export type LookupPartyApiV1PartiesLookupPostResponse = LookupPartyApiV1PartiesLookupPostResponses[keyof LookupPartyApiV1PartiesLookupPostResponses];

export type LookupIbanApiV1PartiesIbanLookupPostData = {
    body: IbanLookupRequest;
    path?: never;
    query?: never;
    url: '/api/v1/parties/iban-lookup';
};

export type LookupIbanApiV1PartiesIbanLookupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LookupIbanApiV1PartiesIbanLookupPostError = LookupIbanApiV1PartiesIbanLookupPostErrors[keyof LookupIbanApiV1PartiesIbanLookupPostErrors];

export type LookupIbanApiV1PartiesIbanLookupPostResponses = {
    /**
     * Successful Response
     */
    200: IbanDraftResponse;
};

export type LookupIbanApiV1PartiesIbanLookupPostResponse = LookupIbanApiV1PartiesIbanLookupPostResponses[keyof LookupIbanApiV1PartiesIbanLookupPostResponses];

export type ListContactsApiV1PartiesPartyIdContactsGetData = {
    body?: never;
    path: {
        /**
         * Party Id
         */
        party_id: string;
    };
    query?: never;
    url: '/api/v1/parties/{party_id}/contacts';
};

export type ListContactsApiV1PartiesPartyIdContactsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListContactsApiV1PartiesPartyIdContactsGetError = ListContactsApiV1PartiesPartyIdContactsGetErrors[keyof ListContactsApiV1PartiesPartyIdContactsGetErrors];

export type ListContactsApiV1PartiesPartyIdContactsGetResponses = {
    /**
     * Response List Contacts Api V1 Parties  Party Id  Contacts Get
     *
     * Successful Response
     */
    200: Array<ContactResponse>;
};

export type ListContactsApiV1PartiesPartyIdContactsGetResponse = ListContactsApiV1PartiesPartyIdContactsGetResponses[keyof ListContactsApiV1PartiesPartyIdContactsGetResponses];

export type CreateContactApiV1PartiesPartyIdContactsPostData = {
    body: ContactCreate;
    path: {
        /**
         * Party Id
         */
        party_id: string;
    };
    query?: never;
    url: '/api/v1/parties/{party_id}/contacts';
};

export type CreateContactApiV1PartiesPartyIdContactsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateContactApiV1PartiesPartyIdContactsPostError = CreateContactApiV1PartiesPartyIdContactsPostErrors[keyof CreateContactApiV1PartiesPartyIdContactsPostErrors];

export type CreateContactApiV1PartiesPartyIdContactsPostResponses = {
    /**
     * Successful Response
     */
    201: ContactResponse;
};

export type CreateContactApiV1PartiesPartyIdContactsPostResponse = CreateContactApiV1PartiesPartyIdContactsPostResponses[keyof CreateContactApiV1PartiesPartyIdContactsPostResponses];

export type ListBankAccountsApiV1PartiesPartyIdBankAccountsGetData = {
    body?: never;
    path: {
        /**
         * Party Id
         */
        party_id: string;
    };
    query?: never;
    url: '/api/v1/parties/{party_id}/bank-accounts';
};

export type ListBankAccountsApiV1PartiesPartyIdBankAccountsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListBankAccountsApiV1PartiesPartyIdBankAccountsGetError = ListBankAccountsApiV1PartiesPartyIdBankAccountsGetErrors[keyof ListBankAccountsApiV1PartiesPartyIdBankAccountsGetErrors];

export type ListBankAccountsApiV1PartiesPartyIdBankAccountsGetResponses = {
    /**
     * Response List Bank Accounts Api V1 Parties  Party Id  Bank Accounts Get
     *
     * Successful Response
     */
    200: Array<BankAccountResponse>;
};

export type ListBankAccountsApiV1PartiesPartyIdBankAccountsGetResponse = ListBankAccountsApiV1PartiesPartyIdBankAccountsGetResponses[keyof ListBankAccountsApiV1PartiesPartyIdBankAccountsGetResponses];

export type CreateBankAccountApiV1PartiesPartyIdBankAccountsPostData = {
    body: BankAccountCreate;
    path: {
        /**
         * Party Id
         */
        party_id: string;
    };
    query?: never;
    url: '/api/v1/parties/{party_id}/bank-accounts';
};

export type CreateBankAccountApiV1PartiesPartyIdBankAccountsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateBankAccountApiV1PartiesPartyIdBankAccountsPostError = CreateBankAccountApiV1PartiesPartyIdBankAccountsPostErrors[keyof CreateBankAccountApiV1PartiesPartyIdBankAccountsPostErrors];

export type CreateBankAccountApiV1PartiesPartyIdBankAccountsPostResponses = {
    /**
     * Successful Response
     */
    201: BankAccountResponse;
};

export type CreateBankAccountApiV1PartiesPartyIdBankAccountsPostResponse = CreateBankAccountApiV1PartiesPartyIdBankAccountsPostResponses[keyof CreateBankAccountApiV1PartiesPartyIdBankAccountsPostResponses];

export type ListEmailDomainsApiV1PartiesPartyIdEmailDomainsGetData = {
    body?: never;
    path: {
        /**
         * Party Id
         */
        party_id: string;
    };
    query?: never;
    url: '/api/v1/parties/{party_id}/email-domains';
};

export type ListEmailDomainsApiV1PartiesPartyIdEmailDomainsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListEmailDomainsApiV1PartiesPartyIdEmailDomainsGetError = ListEmailDomainsApiV1PartiesPartyIdEmailDomainsGetErrors[keyof ListEmailDomainsApiV1PartiesPartyIdEmailDomainsGetErrors];

export type ListEmailDomainsApiV1PartiesPartyIdEmailDomainsGetResponses = {
    /**
     * Response List Email Domains Api V1 Parties  Party Id  Email Domains Get
     *
     * Successful Response
     */
    200: Array<EmailDomainResponse>;
};

export type ListEmailDomainsApiV1PartiesPartyIdEmailDomainsGetResponse = ListEmailDomainsApiV1PartiesPartyIdEmailDomainsGetResponses[keyof ListEmailDomainsApiV1PartiesPartyIdEmailDomainsGetResponses];

export type CreateEmailDomainApiV1PartiesPartyIdEmailDomainsPostData = {
    body: EmailDomainCreate;
    path: {
        /**
         * Party Id
         */
        party_id: string;
    };
    query?: never;
    url: '/api/v1/parties/{party_id}/email-domains';
};

export type CreateEmailDomainApiV1PartiesPartyIdEmailDomainsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEmailDomainApiV1PartiesPartyIdEmailDomainsPostError = CreateEmailDomainApiV1PartiesPartyIdEmailDomainsPostErrors[keyof CreateEmailDomainApiV1PartiesPartyIdEmailDomainsPostErrors];

export type CreateEmailDomainApiV1PartiesPartyIdEmailDomainsPostResponses = {
    /**
     * Successful Response
     */
    201: EmailDomainResponse;
};

export type CreateEmailDomainApiV1PartiesPartyIdEmailDomainsPostResponse = CreateEmailDomainApiV1PartiesPartyIdEmailDomainsPostResponses[keyof CreateEmailDomainApiV1PartiesPartyIdEmailDomainsPostResponses];

export type ListChargeOverridesApiV1PartiesPartyIdChargeOverridesGetData = {
    body?: never;
    path: {
        /**
         * Party Id
         */
        party_id: string;
    };
    query?: never;
    url: '/api/v1/parties/{party_id}/charge-overrides';
};

export type ListChargeOverridesApiV1PartiesPartyIdChargeOverridesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListChargeOverridesApiV1PartiesPartyIdChargeOverridesGetError = ListChargeOverridesApiV1PartiesPartyIdChargeOverridesGetErrors[keyof ListChargeOverridesApiV1PartiesPartyIdChargeOverridesGetErrors];

export type ListChargeOverridesApiV1PartiesPartyIdChargeOverridesGetResponses = {
    /**
     * Response List Charge Overrides Api V1 Parties  Party Id  Charge Overrides Get
     *
     * Successful Response
     */
    200: Array<ChargeOverrideResponse>;
};

export type ListChargeOverridesApiV1PartiesPartyIdChargeOverridesGetResponse = ListChargeOverridesApiV1PartiesPartyIdChargeOverridesGetResponses[keyof ListChargeOverridesApiV1PartiesPartyIdChargeOverridesGetResponses];

export type CreateChargeOverrideApiV1PartiesPartyIdChargeOverridesPostData = {
    body: ChargeOverrideCreate;
    path: {
        /**
         * Party Id
         */
        party_id: string;
    };
    query?: never;
    url: '/api/v1/parties/{party_id}/charge-overrides';
};

export type CreateChargeOverrideApiV1PartiesPartyIdChargeOverridesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateChargeOverrideApiV1PartiesPartyIdChargeOverridesPostError = CreateChargeOverrideApiV1PartiesPartyIdChargeOverridesPostErrors[keyof CreateChargeOverrideApiV1PartiesPartyIdChargeOverridesPostErrors];

export type CreateChargeOverrideApiV1PartiesPartyIdChargeOverridesPostResponses = {
    /**
     * Successful Response
     */
    201: ChargeOverrideResponse;
};

export type CreateChargeOverrideApiV1PartiesPartyIdChargeOverridesPostResponse = CreateChargeOverrideApiV1PartiesPartyIdChargeOverridesPostResponses[keyof CreateChargeOverrideApiV1PartiesPartyIdChargeOverridesPostResponses];

export type GetCarrierProfileApiV1PartiesPartyIdCarrierProfileGetData = {
    body?: never;
    path: {
        /**
         * Party Id
         */
        party_id: string;
    };
    query?: never;
    url: '/api/v1/parties/{party_id}/carrier-profile';
};

export type GetCarrierProfileApiV1PartiesPartyIdCarrierProfileGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCarrierProfileApiV1PartiesPartyIdCarrierProfileGetError = GetCarrierProfileApiV1PartiesPartyIdCarrierProfileGetErrors[keyof GetCarrierProfileApiV1PartiesPartyIdCarrierProfileGetErrors];

export type GetCarrierProfileApiV1PartiesPartyIdCarrierProfileGetResponses = {
    /**
     * Response Get Carrier Profile Api V1 Parties  Party Id  Carrier Profile Get
     *
     * Successful Response
     */
    200: CarrierProfileResponse | null;
};

export type GetCarrierProfileApiV1PartiesPartyIdCarrierProfileGetResponse = GetCarrierProfileApiV1PartiesPartyIdCarrierProfileGetResponses[keyof GetCarrierProfileApiV1PartiesPartyIdCarrierProfileGetResponses];

export type UpsertCarrierProfileApiV1PartiesPartyIdCarrierProfilePutData = {
    body: CarrierProfileUpsert;
    path: {
        /**
         * Party Id
         */
        party_id: string;
    };
    query?: never;
    url: '/api/v1/parties/{party_id}/carrier-profile';
};

export type UpsertCarrierProfileApiV1PartiesPartyIdCarrierProfilePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpsertCarrierProfileApiV1PartiesPartyIdCarrierProfilePutError = UpsertCarrierProfileApiV1PartiesPartyIdCarrierProfilePutErrors[keyof UpsertCarrierProfileApiV1PartiesPartyIdCarrierProfilePutErrors];

export type UpsertCarrierProfileApiV1PartiesPartyIdCarrierProfilePutResponses = {
    /**
     * Successful Response
     */
    200: CarrierProfileResponse;
};

export type UpsertCarrierProfileApiV1PartiesPartyIdCarrierProfilePutResponse = UpsertCarrierProfileApiV1PartiesPartyIdCarrierProfilePutResponses[keyof UpsertCarrierProfileApiV1PartiesPartyIdCarrierProfilePutResponses];

export type ListPortsApiV1PortsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search
         */
        search?: string | null;
    };
    url: '/api/v1/ports';
};

export type ListPortsApiV1PortsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPortsApiV1PortsGetError = ListPortsApiV1PortsGetErrors[keyof ListPortsApiV1PortsGetErrors];

export type ListPortsApiV1PortsGetResponses = {
    /**
     * Response List Ports Api V1 Ports Get
     *
     * Successful Response
     */
    200: Array<PortResponse>;
};

export type ListPortsApiV1PortsGetResponse = ListPortsApiV1PortsGetResponses[keyof ListPortsApiV1PortsGetResponses];

export type CreatePortApiV1PortsPostData = {
    body: PortCreate;
    path?: never;
    query?: never;
    url: '/api/v1/ports';
};

export type CreatePortApiV1PortsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePortApiV1PortsPostError = CreatePortApiV1PortsPostErrors[keyof CreatePortApiV1PortsPostErrors];

export type CreatePortApiV1PortsPostResponses = {
    /**
     * Successful Response
     */
    201: PortResponse;
};

export type CreatePortApiV1PortsPostResponse = CreatePortApiV1PortsPostResponses[keyof CreatePortApiV1PortsPostResponses];

export type ResolvePortApiV1PortsResolveGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Token
         */
        token: string;
    };
    url: '/api/v1/ports/resolve';
};

export type ResolvePortApiV1PortsResolveGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResolvePortApiV1PortsResolveGetError = ResolvePortApiV1PortsResolveGetErrors[keyof ResolvePortApiV1PortsResolveGetErrors];

export type ResolvePortApiV1PortsResolveGetResponses = {
    /**
     * Successful Response
     */
    200: PortResponse;
};

export type ResolvePortApiV1PortsResolveGetResponse = ResolvePortApiV1PortsResolveGetResponses[keyof ResolvePortApiV1PortsResolveGetResponses];

export type ListLocationsApiV1LocationsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Kind
         */
        kind?: string | null;
        /**
         * Search
         */
        search?: string | null;
    };
    url: '/api/v1/locations';
};

export type ListLocationsApiV1LocationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListLocationsApiV1LocationsGetError = ListLocationsApiV1LocationsGetErrors[keyof ListLocationsApiV1LocationsGetErrors];

export type ListLocationsApiV1LocationsGetResponses = {
    /**
     * Response List Locations Api V1 Locations Get
     *
     * Successful Response
     */
    200: Array<LocationResponse>;
};

export type ListLocationsApiV1LocationsGetResponse = ListLocationsApiV1LocationsGetResponses[keyof ListLocationsApiV1LocationsGetResponses];

export type CreateZoneApiV1LocationsPostData = {
    body: ZoneCreate;
    path?: never;
    query?: never;
    url: '/api/v1/locations';
};

export type CreateZoneApiV1LocationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateZoneApiV1LocationsPostError = CreateZoneApiV1LocationsPostErrors[keyof CreateZoneApiV1LocationsPostErrors];

export type CreateZoneApiV1LocationsPostResponses = {
    /**
     * Successful Response
     */
    201: LocationResponse;
};

export type CreateZoneApiV1LocationsPostResponse = CreateZoneApiV1LocationsPostResponses[keyof CreateZoneApiV1LocationsPostResponses];

export type ResolvePostalCodeApiV1LocationsResolveGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Country Code
         */
        country_code: string;
        /**
         * Postal Code
         */
        postal_code: string;
    };
    url: '/api/v1/locations/resolve';
};

export type ResolvePostalCodeApiV1LocationsResolveGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResolvePostalCodeApiV1LocationsResolveGetError = ResolvePostalCodeApiV1LocationsResolveGetErrors[keyof ResolvePostalCodeApiV1LocationsResolveGetErrors];

export type ResolvePostalCodeApiV1LocationsResolveGetResponses = {
    /**
     * Successful Response
     */
    200: LocationResponse;
};

export type ResolvePostalCodeApiV1LocationsResolveGetResponse = ResolvePostalCodeApiV1LocationsResolveGetResponses[keyof ResolvePostalCodeApiV1LocationsResolveGetResponses];

export type ListZoneMembersApiV1LocationsZoneIdMembersGetData = {
    body?: never;
    path: {
        /**
         * Zone Id
         */
        zone_id: string;
    };
    query?: never;
    url: '/api/v1/locations/{zone_id}/members';
};

export type ListZoneMembersApiV1LocationsZoneIdMembersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListZoneMembersApiV1LocationsZoneIdMembersGetError = ListZoneMembersApiV1LocationsZoneIdMembersGetErrors[keyof ListZoneMembersApiV1LocationsZoneIdMembersGetErrors];

export type ListZoneMembersApiV1LocationsZoneIdMembersGetResponses = {
    /**
     * Response List Zone Members Api V1 Locations  Zone Id  Members Get
     *
     * Successful Response
     */
    200: Array<ZoneMemberResponse>;
};

export type ListZoneMembersApiV1LocationsZoneIdMembersGetResponse = ListZoneMembersApiV1LocationsZoneIdMembersGetResponses[keyof ListZoneMembersApiV1LocationsZoneIdMembersGetResponses];

export type AddZoneMemberApiV1LocationsZoneIdMembersPostData = {
    body: ZoneMemberCreate;
    path: {
        /**
         * Zone Id
         */
        zone_id: string;
    };
    query?: never;
    url: '/api/v1/locations/{zone_id}/members';
};

export type AddZoneMemberApiV1LocationsZoneIdMembersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddZoneMemberApiV1LocationsZoneIdMembersPostError = AddZoneMemberApiV1LocationsZoneIdMembersPostErrors[keyof AddZoneMemberApiV1LocationsZoneIdMembersPostErrors];

export type AddZoneMemberApiV1LocationsZoneIdMembersPostResponses = {
    /**
     * Successful Response
     */
    201: ZoneMemberResponse;
};

export type AddZoneMemberApiV1LocationsZoneIdMembersPostResponse = AddZoneMemberApiV1LocationsZoneIdMembersPostResponses[keyof AddZoneMemberApiV1LocationsZoneIdMembersPostResponses];

export type ListTerminalsApiV1TerminalsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Port Id
         */
        port_id?: string | null;
        /**
         * Search
         */
        search?: string | null;
    };
    url: '/api/v1/terminals';
};

export type ListTerminalsApiV1TerminalsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTerminalsApiV1TerminalsGetError = ListTerminalsApiV1TerminalsGetErrors[keyof ListTerminalsApiV1TerminalsGetErrors];

export type ListTerminalsApiV1TerminalsGetResponses = {
    /**
     * Response List Terminals Api V1 Terminals Get
     *
     * Successful Response
     */
    200: Array<TerminalResponse>;
};

export type ListTerminalsApiV1TerminalsGetResponse = ListTerminalsApiV1TerminalsGetResponses[keyof ListTerminalsApiV1TerminalsGetResponses];

export type CreateTerminalApiV1TerminalsPostData = {
    body: TerminalCreate;
    path?: never;
    query?: never;
    url: '/api/v1/terminals';
};

export type CreateTerminalApiV1TerminalsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTerminalApiV1TerminalsPostError = CreateTerminalApiV1TerminalsPostErrors[keyof CreateTerminalApiV1TerminalsPostErrors];

export type CreateTerminalApiV1TerminalsPostResponses = {
    /**
     * Successful Response
     */
    201: TerminalResponse;
};

export type CreateTerminalApiV1TerminalsPostResponse = CreateTerminalApiV1TerminalsPostResponses[keyof CreateTerminalApiV1TerminalsPostResponses];

export type ResolveTerminalApiV1TerminalsResolveGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Isps Code
         */
        isps_code: string;
    };
    url: '/api/v1/terminals/resolve';
};

export type ResolveTerminalApiV1TerminalsResolveGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResolveTerminalApiV1TerminalsResolveGetError = ResolveTerminalApiV1TerminalsResolveGetErrors[keyof ResolveTerminalApiV1TerminalsResolveGetErrors];

export type ResolveTerminalApiV1TerminalsResolveGetResponses = {
    /**
     * Successful Response
     */
    200: TerminalResponse;
};

export type ResolveTerminalApiV1TerminalsResolveGetResponse = ResolveTerminalApiV1TerminalsResolveGetResponses[keyof ResolveTerminalApiV1TerminalsResolveGetResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];

export type ReadyReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ready';
};

export type ReadyReadyGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
