// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AppUserResponse
 */
export type AppUserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
};

/**
 * ExtractRequest
 */
export type ExtractRequest = {
    /**
     * Source Ref
     */
    source_ref: string;
    /**
     * Input Text
     */
    input_text: string;
};

/**
 * ExtractionDraftResponse
 */
export type ExtractionDraftResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Source Ref
     */
    source_ref: string;
    /**
     * Input Text
     */
    input_text: string;
    /**
     * Payload
     */
    payload: {
        [key: string]: unknown;
    };
    /**
     * Reviewed By
     */
    reviewed_by: string | null;
    /**
     * Reviewed At
     */
    reviewed_at: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * TableViewConfig
 */
export type TableViewConfig = {
    /**
     * Column Order
     */
    column_order?: Array<string>;
    /**
     * Column Visibility
     */
    column_visibility?: {
        [key: string]: boolean;
    };
    /**
     * Filters
     */
    filters?: {
        [key: string]: unknown;
    };
    /**
     * Sorting
     */
    sorting?: Array<{
        [key: string]: string;
    }>;
    /**
     * Density
     */
    density?: string;
};

/**
 * TableViewCreate
 */
export type TableViewCreate = {
    /**
     * Table Key
     */
    table_key: string;
    /**
     * Name
     */
    name: string;
    config?: TableViewConfig;
};

/**
 * TableViewResponse
 */
export type TableViewResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Table Key
     */
    table_key: string;
    /**
     * Name
     */
    name: string;
    /**
     * Config
     */
    config: {
        [key: string]: unknown;
    };
};

/**
 * TableViewUpdate
 */
export type TableViewUpdate = {
    /**
     * Name
     */
    name?: string | null;
    config?: TableViewConfig | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListUsersApiV1TenancyUsersGetData = {
    body?: never;
    headers: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id': string;
        /**
         * X-User-Id
         */
        'X-User-Id': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/tenancy/users';
};

export type ListUsersApiV1TenancyUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListUsersApiV1TenancyUsersGetError = ListUsersApiV1TenancyUsersGetErrors[keyof ListUsersApiV1TenancyUsersGetErrors];

export type ListUsersApiV1TenancyUsersGetResponses = {
    /**
     * Response List Users Api V1 Tenancy Users Get
     *
     * Successful Response
     */
    200: Array<AppUserResponse>;
};

export type ListUsersApiV1TenancyUsersGetResponse = ListUsersApiV1TenancyUsersGetResponses[keyof ListUsersApiV1TenancyUsersGetResponses];

export type ListTableViewsApiV1TenancyTableViewsGetData = {
    body?: never;
    headers: {
        /**
         * X-User-Id
         */
        'X-User-Id': string;
        /**
         * X-Organization-Id
         */
        'X-Organization-Id': string;
    };
    path?: never;
    query: {
        /**
         * Table Key
         */
        table_key: string;
    };
    url: '/api/v1/tenancy/table-views';
};

export type ListTableViewsApiV1TenancyTableViewsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTableViewsApiV1TenancyTableViewsGetError = ListTableViewsApiV1TenancyTableViewsGetErrors[keyof ListTableViewsApiV1TenancyTableViewsGetErrors];

export type ListTableViewsApiV1TenancyTableViewsGetResponses = {
    /**
     * Response List Table Views Api V1 Tenancy Table Views Get
     *
     * Successful Response
     */
    200: Array<TableViewResponse>;
};

export type ListTableViewsApiV1TenancyTableViewsGetResponse = ListTableViewsApiV1TenancyTableViewsGetResponses[keyof ListTableViewsApiV1TenancyTableViewsGetResponses];

export type CreateTableViewApiV1TenancyTableViewsPostData = {
    body: TableViewCreate;
    headers: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id': string;
        /**
         * X-User-Id
         */
        'X-User-Id': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/tenancy/table-views';
};

export type CreateTableViewApiV1TenancyTableViewsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTableViewApiV1TenancyTableViewsPostError = CreateTableViewApiV1TenancyTableViewsPostErrors[keyof CreateTableViewApiV1TenancyTableViewsPostErrors];

export type CreateTableViewApiV1TenancyTableViewsPostResponses = {
    /**
     * Successful Response
     */
    201: TableViewResponse;
};

export type CreateTableViewApiV1TenancyTableViewsPostResponse = CreateTableViewApiV1TenancyTableViewsPostResponses[keyof CreateTableViewApiV1TenancyTableViewsPostResponses];

export type DeleteTableViewApiV1TenancyTableViewsViewIdDeleteData = {
    body?: never;
    headers: {
        /**
         * X-User-Id
         */
        'X-User-Id': string;
        /**
         * X-Organization-Id
         */
        'X-Organization-Id': string;
    };
    path: {
        /**
         * View Id
         */
        view_id: string;
    };
    query?: never;
    url: '/api/v1/tenancy/table-views/{view_id}';
};

export type DeleteTableViewApiV1TenancyTableViewsViewIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTableViewApiV1TenancyTableViewsViewIdDeleteError = DeleteTableViewApiV1TenancyTableViewsViewIdDeleteErrors[keyof DeleteTableViewApiV1TenancyTableViewsViewIdDeleteErrors];

export type DeleteTableViewApiV1TenancyTableViewsViewIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTableViewApiV1TenancyTableViewsViewIdDeleteResponse = DeleteTableViewApiV1TenancyTableViewsViewIdDeleteResponses[keyof DeleteTableViewApiV1TenancyTableViewsViewIdDeleteResponses];

export type UpdateTableViewApiV1TenancyTableViewsViewIdPatchData = {
    body: TableViewUpdate;
    headers: {
        /**
         * X-User-Id
         */
        'X-User-Id': string;
        /**
         * X-Organization-Id
         */
        'X-Organization-Id': string;
    };
    path: {
        /**
         * View Id
         */
        view_id: string;
    };
    query?: never;
    url: '/api/v1/tenancy/table-views/{view_id}';
};

export type UpdateTableViewApiV1TenancyTableViewsViewIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTableViewApiV1TenancyTableViewsViewIdPatchError = UpdateTableViewApiV1TenancyTableViewsViewIdPatchErrors[keyof UpdateTableViewApiV1TenancyTableViewsViewIdPatchErrors];

export type UpdateTableViewApiV1TenancyTableViewsViewIdPatchResponses = {
    /**
     * Successful Response
     */
    200: TableViewResponse;
};

export type UpdateTableViewApiV1TenancyTableViewsViewIdPatchResponse = UpdateTableViewApiV1TenancyTableViewsViewIdPatchResponses[keyof UpdateTableViewApiV1TenancyTableViewsViewIdPatchResponses];

export type ListExtractionDraftsApiV1ExtractionsGetData = {
    body?: never;
    headers: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id': string;
        /**
         * X-User-Id
         */
        'X-User-Id': string;
    };
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: string | null;
    };
    url: '/api/v1/extractions';
};

export type ListExtractionDraftsApiV1ExtractionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListExtractionDraftsApiV1ExtractionsGetError = ListExtractionDraftsApiV1ExtractionsGetErrors[keyof ListExtractionDraftsApiV1ExtractionsGetErrors];

export type ListExtractionDraftsApiV1ExtractionsGetResponses = {
    /**
     * Response List Extraction Drafts Api V1 Extractions Get
     *
     * Successful Response
     */
    200: Array<ExtractionDraftResponse>;
};

export type ListExtractionDraftsApiV1ExtractionsGetResponse = ListExtractionDraftsApiV1ExtractionsGetResponses[keyof ListExtractionDraftsApiV1ExtractionsGetResponses];

export type CreateExtractionDraftApiV1ExtractionsPostData = {
    body: ExtractRequest;
    headers: {
        /**
         * X-Organization-Id
         */
        'X-Organization-Id': string;
        /**
         * X-User-Id
         */
        'X-User-Id': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/extractions';
};

export type CreateExtractionDraftApiV1ExtractionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateExtractionDraftApiV1ExtractionsPostError = CreateExtractionDraftApiV1ExtractionsPostErrors[keyof CreateExtractionDraftApiV1ExtractionsPostErrors];

export type CreateExtractionDraftApiV1ExtractionsPostResponses = {
    /**
     * Successful Response
     */
    201: ExtractionDraftResponse;
};

export type CreateExtractionDraftApiV1ExtractionsPostResponse = CreateExtractionDraftApiV1ExtractionsPostResponses[keyof CreateExtractionDraftApiV1ExtractionsPostResponses];

export type AcceptExtractionDraftApiV1ExtractionsDraftIdAcceptPostData = {
    body?: never;
    headers: {
        /**
         * X-User-Id
         */
        'X-User-Id': string;
        /**
         * X-Organization-Id
         */
        'X-Organization-Id': string;
    };
    path: {
        /**
         * Draft Id
         */
        draft_id: string;
    };
    query?: never;
    url: '/api/v1/extractions/{draft_id}/accept';
};

export type AcceptExtractionDraftApiV1ExtractionsDraftIdAcceptPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AcceptExtractionDraftApiV1ExtractionsDraftIdAcceptPostError = AcceptExtractionDraftApiV1ExtractionsDraftIdAcceptPostErrors[keyof AcceptExtractionDraftApiV1ExtractionsDraftIdAcceptPostErrors];

export type AcceptExtractionDraftApiV1ExtractionsDraftIdAcceptPostResponses = {
    /**
     * Successful Response
     */
    200: ExtractionDraftResponse;
};

export type AcceptExtractionDraftApiV1ExtractionsDraftIdAcceptPostResponse = AcceptExtractionDraftApiV1ExtractionsDraftIdAcceptPostResponses[keyof AcceptExtractionDraftApiV1ExtractionsDraftIdAcceptPostResponses];

export type RejectExtractionDraftApiV1ExtractionsDraftIdRejectPostData = {
    body?: never;
    headers: {
        /**
         * X-User-Id
         */
        'X-User-Id': string;
        /**
         * X-Organization-Id
         */
        'X-Organization-Id': string;
    };
    path: {
        /**
         * Draft Id
         */
        draft_id: string;
    };
    query?: never;
    url: '/api/v1/extractions/{draft_id}/reject';
};

export type RejectExtractionDraftApiV1ExtractionsDraftIdRejectPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RejectExtractionDraftApiV1ExtractionsDraftIdRejectPostError = RejectExtractionDraftApiV1ExtractionsDraftIdRejectPostErrors[keyof RejectExtractionDraftApiV1ExtractionsDraftIdRejectPostErrors];

export type RejectExtractionDraftApiV1ExtractionsDraftIdRejectPostResponses = {
    /**
     * Successful Response
     */
    200: ExtractionDraftResponse;
};

export type RejectExtractionDraftApiV1ExtractionsDraftIdRejectPostResponse = RejectExtractionDraftApiV1ExtractionsDraftIdRejectPostResponses[keyof RejectExtractionDraftApiV1ExtractionsDraftIdRejectPostResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];
