import { readFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { describe, expect, it } from "vitest"

const srcRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..")

describe("mail-integration surface for 25.0", () => {
  it("ships /mail as read-only known addresses without IMAP", () => {
    const page = readFileSync(path.join(srcRoot, "features/mail-integration/catalog-page.tsx"), "utf8")
    const route = readFileSync(path.join(srcRoot, "routes/mail.tsx"), "utf8")
    const nav = readFileSync(path.join(srcRoot, "components/layout/sidebar.tsx"), "utf8")
    const lists = readFileSync(path.join(srcRoot, "lib/business-lists.ts"), "utf8")
    const ops = readFileSync(path.join(srcRoot, "features/ops/ops-index.ts"), "utf8")
    expect(route).toContain("/mail")
    expect(nav).toContain("/mail")
    expect(lists).toContain("mailIntegration")
    expect(ops).toContain("/mail")
    expect(page).toContain('data-mail-integration="board"')
    expect(page).toContain("fetchEmailDomains")
    expect(page).toContain("fetchContacts")
    expect(page).toContain("resolvePartyEmail")
    expect(page).not.toContain("createContact")
    expect(page).not.toContain("createEmailDomain")
    expect(page).not.toContain("imap")
    expect(page).not.toContain("smtp")
    expect(page).not.toContain("CatalogCreateForm")
    expect(page).toContain('data-mail-client="mailto"')
    expect(page).toContain("mailto:")
    expect(page).not.toContain("office.js")
    expect(page).not.toContain("manifest.xml")
    expect(page).not.toContain("graph.microsoft")
  })

  it("ships inbound_message fixture list and write on the same /mail board", () => {
    const page = readFileSync(path.join(srcRoot, "features/mail-integration/catalog-page.tsx"), "utf8")
    const api = readFileSync(path.join(srcRoot, "lib/inbound-messages-api.ts"), "utf8")
    expect(page).toContain('data-inbound-message="fixture"')
    expect(page).toContain("CatalogLoadedTable")
    expect(page).toContain("createInboundMessage")
    expect(page).toContain("fetchInboundMessages")
    expect(page).toContain("resolveInboundMessageEmail")
    expect(page).toContain("extractInboundMessage")
    expect(page).toContain("Extract HITL")
    expect(page).toContain("createCustomerRfq")
    expect(page).toContain("Utwórz RFQ")
    expect(page).toContain("party_id")
    expect(api).toContain("/api/v1/inbound-messages")
    expect(api).toContain("resolve-email")
    expect(api).toContain("/extract")
    expect(api).not.toContain("graph.microsoft")
    const rfqApi = readFileSync(path.join(srcRoot, "lib/customer-rfqs-api.ts"), "utf8")
    expect(rfqApi).toContain("/api/v1/customer-rfqs")
    expect(rfqApi).not.toContain("amount")
  })
})
