/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChannelQuotesRouteImport } from './routes/channel-quotes'
import { Route as ChargeCodesRouteImport } from './routes/charge-codes'
import { Route as ChargesRouteImport } from './routes/charges'
import { Route as CommodityCodesRouteImport } from './routes/commodity-codes'
import { Route as CustomerSopsRouteImport } from './routes/customer-sops'
import { Route as DangerousGoodsRouteImport } from './routes/dangerous-goods'
import { Route as ExtractionsRouteImport } from './routes/extractions'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as NbpRatesRouteImport } from './routes/nbp-rates'
import { Route as NetworksRouteImport } from './routes/networks'
import { Route as OrganizationSettingsRouteImport } from './routes/organization-settings'
import { Route as PartiesRouteImport } from './routes/parties'
import { Route as PartyScorecardsRouteImport } from './routes/party-scorecards'
import { Route as PortSurchargesRouteImport } from './routes/port-surcharges'
import { Route as PortsRouteImport } from './routes/ports'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as RateLinesRouteImport } from './routes/rate-lines'
import { Route as SessionRouteImport } from './routes/session'
import { Route as TerminalsRouteImport } from './routes/terminals'
import { Route as TenancyUsersRouteImport } from './routes/tenancy.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelQuotesRoute = ChannelQuotesRouteImport.update({
  id: '/channel-quotes',
  path: '/channel-quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChargeCodesRoute = ChargeCodesRouteImport.update({
  id: '/charge-codes',
  path: '/charge-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChargesRoute = ChargesRouteImport.update({
  id: '/charges',
  path: '/charges',
  getParentRoute: () => rootRouteImport,
} as any)
const CommodityCodesRoute = CommodityCodesRouteImport.update({
  id: '/commodity-codes',
  path: '/commodity-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSopsRoute = CustomerSopsRouteImport.update({
  id: '/customer-sops',
  path: '/customer-sops',
  getParentRoute: () => rootRouteImport,
} as any)
const DangerousGoodsRoute = DangerousGoodsRouteImport.update({
  id: '/dangerous-goods',
  path: '/dangerous-goods',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractionsRoute = ExtractionsRouteImport.update({
  id: '/extractions',
  path: '/extractions',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const NbpRatesRoute = NbpRatesRouteImport.update({
  id: '/nbp-rates',
  path: '/nbp-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworksRoute = NetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSettingsRoute = OrganizationSettingsRouteImport.update({
  id: '/organization-settings',
  path: '/organization-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesRoute = PartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyScorecardsRoute = PartyScorecardsRouteImport.update({
  id: '/party-scorecards',
  path: '/party-scorecards',
  getParentRoute: () => rootRouteImport,
} as any)
const PortSurchargesRoute = PortSurchargesRouteImport.update({
  id: '/port-surcharges',
  path: '/port-surcharges',
  getParentRoute: () => rootRouteImport,
} as any)
const PortsRoute = PortsRouteImport.update({
  id: '/ports',
  path: '/ports',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const RateLinesRoute = RateLinesRouteImport.update({
  id: '/rate-lines',
  path: '/rate-lines',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalsRoute = TerminalsRouteImport.update({
  id: '/terminals',
  path: '/terminals',
  getParentRoute: () => rootRouteImport,
} as any)
const TenancyUsersRoute = TenancyUsersRouteImport.update({
  id: '/tenancy/users',
  path: '/tenancy/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channel-quotes': typeof ChannelQuotesRoute
  '/charge-codes': typeof ChargeCodesRoute
  '/charges': typeof ChargesRoute
  '/commodity-codes': typeof CommodityCodesRoute
  '/customer-sops': typeof CustomerSopsRoute
  '/dangerous-goods': typeof DangerousGoodsRoute
  '/extractions': typeof ExtractionsRoute
  '/locations': typeof LocationsRoute
  '/nbp-rates': typeof NbpRatesRoute
  '/networks': typeof NetworksRoute
  '/organization-settings': typeof OrganizationSettingsRoute
  '/parties': typeof PartiesRoute
  '/party-scorecards': typeof PartyScorecardsRoute
  '/port-surcharges': typeof PortSurchargesRoute
  '/ports': typeof PortsRoute
  '/quotations': typeof QuotationsRoute
  '/rate-lines': typeof RateLinesRoute
  '/session': typeof SessionRoute
  '/terminals': typeof TerminalsRoute
  '/tenancy/users': typeof TenancyUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channel-quotes': typeof ChannelQuotesRoute
  '/charge-codes': typeof ChargeCodesRoute
  '/charges': typeof ChargesRoute
  '/commodity-codes': typeof CommodityCodesRoute
  '/customer-sops': typeof CustomerSopsRoute
  '/dangerous-goods': typeof DangerousGoodsRoute
  '/extractions': typeof ExtractionsRoute
  '/locations': typeof LocationsRoute
  '/nbp-rates': typeof NbpRatesRoute
  '/networks': typeof NetworksRoute
  '/organization-settings': typeof OrganizationSettingsRoute
  '/parties': typeof PartiesRoute
  '/party-scorecards': typeof PartyScorecardsRoute
  '/port-surcharges': typeof PortSurchargesRoute
  '/ports': typeof PortsRoute
  '/quotations': typeof QuotationsRoute
  '/rate-lines': typeof RateLinesRoute
  '/session': typeof SessionRoute
  '/terminals': typeof TerminalsRoute
  '/tenancy/users': typeof TenancyUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channel-quotes': typeof ChannelQuotesRoute
  '/charge-codes': typeof ChargeCodesRoute
  '/charges': typeof ChargesRoute
  '/commodity-codes': typeof CommodityCodesRoute
  '/customer-sops': typeof CustomerSopsRoute
  '/dangerous-goods': typeof DangerousGoodsRoute
  '/extractions': typeof ExtractionsRoute
  '/locations': typeof LocationsRoute
  '/nbp-rates': typeof NbpRatesRoute
  '/networks': typeof NetworksRoute
  '/organization-settings': typeof OrganizationSettingsRoute
  '/parties': typeof PartiesRoute
  '/party-scorecards': typeof PartyScorecardsRoute
  '/port-surcharges': typeof PortSurchargesRoute
  '/ports': typeof PortsRoute
  '/quotations': typeof QuotationsRoute
  '/rate-lines': typeof RateLinesRoute
  '/session': typeof SessionRoute
  '/terminals': typeof TerminalsRoute
  '/tenancy/users': typeof TenancyUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channel-quotes'
    | '/charge-codes'
    | '/charges'
    | '/commodity-codes'
    | '/customer-sops'
    | '/dangerous-goods'
    | '/extractions'
    | '/locations'
    | '/nbp-rates'
    | '/networks'
    | '/organization-settings'
    | '/parties'
    | '/party-scorecards'
    | '/port-surcharges'
    | '/ports'
    | '/quotations'
    | '/rate-lines'
    | '/session'
    | '/terminals'
    | '/tenancy/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channel-quotes'
    | '/charge-codes'
    | '/charges'
    | '/commodity-codes'
    | '/customer-sops'
    | '/dangerous-goods'
    | '/extractions'
    | '/locations'
    | '/nbp-rates'
    | '/networks'
    | '/organization-settings'
    | '/parties'
    | '/party-scorecards'
    | '/port-surcharges'
    | '/ports'
    | '/quotations'
    | '/rate-lines'
    | '/session'
    | '/terminals'
    | '/tenancy/users'
  id:
    | '__root__'
    | '/'
    | '/channel-quotes'
    | '/charge-codes'
    | '/charges'
    | '/commodity-codes'
    | '/customer-sops'
    | '/dangerous-goods'
    | '/extractions'
    | '/locations'
    | '/nbp-rates'
    | '/networks'
    | '/organization-settings'
    | '/parties'
    | '/party-scorecards'
    | '/port-surcharges'
    | '/ports'
    | '/quotations'
    | '/rate-lines'
    | '/session'
    | '/terminals'
    | '/tenancy/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelQuotesRoute: typeof ChannelQuotesRoute
  ChargeCodesRoute: typeof ChargeCodesRoute
  ChargesRoute: typeof ChargesRoute
  CommodityCodesRoute: typeof CommodityCodesRoute
  CustomerSopsRoute: typeof CustomerSopsRoute
  DangerousGoodsRoute: typeof DangerousGoodsRoute
  ExtractionsRoute: typeof ExtractionsRoute
  LocationsRoute: typeof LocationsRoute
  NbpRatesRoute: typeof NbpRatesRoute
  NetworksRoute: typeof NetworksRoute
  OrganizationSettingsRoute: typeof OrganizationSettingsRoute
  PartiesRoute: typeof PartiesRoute
  PartyScorecardsRoute: typeof PartyScorecardsRoute
  PortSurchargesRoute: typeof PortSurchargesRoute
  PortsRoute: typeof PortsRoute
  QuotationsRoute: typeof QuotationsRoute
  RateLinesRoute: typeof RateLinesRoute
  SessionRoute: typeof SessionRoute
  TerminalsRoute: typeof TerminalsRoute
  TenancyUsersRoute: typeof TenancyUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel-quotes': {
      id: '/channel-quotes'
      path: '/channel-quotes'
      fullPath: '/channel-quotes'
      preLoaderRoute: typeof ChannelQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charge-codes': {
      id: '/charge-codes'
      path: '/charge-codes'
      fullPath: '/charge-codes'
      preLoaderRoute: typeof ChargeCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charges': {
      id: '/charges'
      path: '/charges'
      fullPath: '/charges'
      preLoaderRoute: typeof ChargesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commodity-codes': {
      id: '/commodity-codes'
      path: '/commodity-codes'
      fullPath: '/commodity-codes'
      preLoaderRoute: typeof CommodityCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-sops': {
      id: '/customer-sops'
      path: '/customer-sops'
      fullPath: '/customer-sops'
      preLoaderRoute: typeof CustomerSopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dangerous-goods': {
      id: '/dangerous-goods'
      path: '/dangerous-goods'
      fullPath: '/dangerous-goods'
      preLoaderRoute: typeof DangerousGoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extractions': {
      id: '/extractions'
      path: '/extractions'
      fullPath: '/extractions'
      preLoaderRoute: typeof ExtractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nbp-rates': {
      id: '/nbp-rates'
      path: '/nbp-rates'
      fullPath: '/nbp-rates'
      preLoaderRoute: typeof NbpRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networks': {
      id: '/networks'
      path: '/networks'
      fullPath: '/networks'
      preLoaderRoute: typeof NetworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization-settings': {
      id: '/organization-settings'
      path: '/organization-settings'
      fullPath: '/organization-settings'
      preLoaderRoute: typeof OrganizationSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties': {
      id: '/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party-scorecards': {
      id: '/party-scorecards'
      path: '/party-scorecards'
      fullPath: '/party-scorecards'
      preLoaderRoute: typeof PartyScorecardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/port-surcharges': {
      id: '/port-surcharges'
      path: '/port-surcharges'
      fullPath: '/port-surcharges'
      preLoaderRoute: typeof PortSurchargesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ports': {
      id: '/ports'
      path: '/ports'
      fullPath: '/ports'
      preLoaderRoute: typeof PortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-lines': {
      id: '/rate-lines'
      path: '/rate-lines'
      fullPath: '/rate-lines'
      preLoaderRoute: typeof RateLinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminals': {
      id: '/terminals'
      path: '/terminals'
      fullPath: '/terminals'
      preLoaderRoute: typeof TerminalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenancy/users': {
      id: '/tenancy/users'
      path: '/tenancy/users'
      fullPath: '/tenancy/users'
      preLoaderRoute: typeof TenancyUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelQuotesRoute: ChannelQuotesRoute,
  ChargeCodesRoute: ChargeCodesRoute,
  ChargesRoute: ChargesRoute,
  CommodityCodesRoute: CommodityCodesRoute,
  CustomerSopsRoute: CustomerSopsRoute,
  DangerousGoodsRoute: DangerousGoodsRoute,
  ExtractionsRoute: ExtractionsRoute,
  LocationsRoute: LocationsRoute,
  NbpRatesRoute: NbpRatesRoute,
  NetworksRoute: NetworksRoute,
  OrganizationSettingsRoute: OrganizationSettingsRoute,
  PartiesRoute: PartiesRoute,
  PartyScorecardsRoute: PartyScorecardsRoute,
  PortSurchargesRoute: PortSurchargesRoute,
  PortsRoute: PortsRoute,
  QuotationsRoute: QuotationsRoute,
  RateLinesRoute: RateLinesRoute,
  SessionRoute: SessionRoute,
  TerminalsRoute: TerminalsRoute,
  TenancyUsersRoute: TenancyUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
