/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AirRouteImport } from './routes/air'
import { Route as AsnsRouteImport } from './routes/asns'
import { Route as BookkeepingRouteImport } from './routes/bookkeeping'
import { Route as CarbonMethodsRouteImport } from './routes/carbon-methods'
import { Route as CashDiscountsRouteImport } from './routes/cash-discounts'
import { Route as CashflowsRouteImport } from './routes/cashflows'
import { Route as ChannelQuotesRouteImport } from './routes/channel-quotes'
import { Route as ChargeCodesRouteImport } from './routes/charge-codes'
import { Route as ChargeTemplatesRouteImport } from './routes/charge-templates'
import { Route as ChargesRouteImport } from './routes/charges'
import { Route as ChinaRailRouteImport } from './routes/china-rail'
import { Route as CircleSimsRouteImport } from './routes/circle-sims'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as CodRouteImport } from './routes/cod'
import { Route as CommodityCodesRouteImport } from './routes/commodity-codes'
import { Route as ConsignmentsRouteImport } from './routes/consignments'
import { Route as CostToServeRouteImport } from './routes/cost-to-serve'
import { Route as CreditReviewsRouteImport } from './routes/credit-reviews'
import { Route as CustomerContractsRouteImport } from './routes/customer-contracts'
import { Route as CustomerSopsRouteImport } from './routes/customer-sops'
import { Route as DangerousGoodsRouteImport } from './routes/dangerous-goods'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as DockAppointmentsRouteImport } from './routes/dock-appointments'
import { Route as DocumentTemplatesRouteImport } from './routes/document-templates'
import { Route as EdiRouteImport } from './routes/edi'
import { Route as EntityEventsRouteImport } from './routes/entity-events'
import { Route as ErpConnectorsRouteImport } from './routes/erp-connectors'
import { Route as ExceptionsRouteImport } from './routes/exceptions'
import { Route as ExchangeConnectorsRouteImport } from './routes/exchange-connectors'
import { Route as ExecutiveMarksRouteImport } from './routes/executive-marks'
import { Route as ExtractionsRouteImport } from './routes/extractions'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as FraudRouteImport } from './routes/fraud'
import { Route as FreeTimeClocksRouteImport } from './routes/free-time-clocks'
import { Route as FuelIndexesRouteImport } from './routes/fuel-indexes'
import { Route as FxDifferencesRouteImport } from './routes/fx-differences'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as GroupageRouteImport } from './routes/groupage'
import { Route as GroupageTariffsRouteImport } from './routes/groupage-tariffs'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IdpConnectorsRouteImport } from './routes/idp-connectors'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as KreptdLicencesRouteImport } from './routes/kreptd-licences'
import { Route as LaneKmsRouteImport } from './routes/lane-kms'
import { Route as LanePatternsRouteImport } from './routes/lane-patterns'
import { Route as LclRouteImport } from './routes/lcl'
import { Route as LocalChargesRouteImport } from './routes/local-charges'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as MailRouteImport } from './routes/mail'
import { Route as MemoryEdgesRouteImport } from './routes/memory-edges'
import { Route as MoneyCostRouteImport } from './routes/money-cost'
import { Route as MonitoringSchemesRouteImport } from './routes/monitoring-schemes'
import { Route as NbpRatesRouteImport } from './routes/nbp-rates'
import { Route as NetworksRouteImport } from './routes/networks'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OceanBillsRouteImport } from './routes/ocean-bills'
import { Route as OrganizationSettingsRouteImport } from './routes/organization-settings'
import { Route as OutboxRouteImport } from './routes/outbox'
import { Route as PalletBalancesRouteImport } from './routes/pallet-balances'
import { Route as PartiesRouteImport } from './routes/parties'
import { Route as PartyDocumentsRouteImport } from './routes/party-documents'
import { Route as PartyScorecardsRouteImport } from './routes/party-scorecards'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PlanSnapshotsRouteImport } from './routes/plan-snapshots'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as PoLinesRouteImport } from './routes/po-lines'
import { Route as PortSurchargesRouteImport } from './routes/port-surcharges'
import { Route as PortsRouteImport } from './routes/ports'
import { Route as PredictionLedgersRouteImport } from './routes/prediction-ledgers'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as QuoteInvoicesRouteImport } from './routes/quote-invoices'
import { Route as RailRouteImport } from './routes/rail'
import { Route as RankMarksRouteImport } from './routes/rank-marks'
import { Route as RateCardsRouteImport } from './routes/rate-cards'
import { Route as RateLinesRouteImport } from './routes/rate-lines'
import { Route as RoadRouteImport } from './routes/road'
import { Route as RolloutRouteImport } from './routes/rollout'
import { Route as RoutingGuidesRouteImport } from './routes/routing-guides'
import { Route as SanctionsRouteImport } from './routes/sanctions'
import { Route as SessionRouteImport } from './routes/session'
import { Route as ShipmentDocumentsRouteImport } from './routes/shipment-documents'
import { Route as ShipmentPackagesRouteImport } from './routes/shipment-packages'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as TaskTemplatesRouteImport } from './routes/task-templates'
import { Route as TelematicsConnectorsRouteImport } from './routes/telematics-connectors'
import { Route as TenantContractKeksRouteImport } from './routes/tenant-contract-keks'
import { Route as TenderAwardReviewsRouteImport } from './routes/tender-award-reviews'
import { Route as TenderBidStancesRouteImport } from './routes/tender-bid-stances'
import { Route as TenderCarbonMarksRouteImport } from './routes/tender-carbon-marks'
import { Route as TenderConsortiumMembersRouteImport } from './routes/tender-consortium-members'
import { Route as TenderDataRoomsRouteImport } from './routes/tender-data-rooms'
import { Route as TenderLanesRouteImport } from './routes/tender-lanes'
import { Route as TenderLotsRouteImport } from './routes/tender-lots'
import { Route as TenderMatrixCellsRouteImport } from './routes/tender-matrix-cells'
import { Route as TenderPlaybooksRouteImport } from './routes/tender-playbooks'
import { Route as TenderProspectsRouteImport } from './routes/tender-prospects'
import { Route as TenderQuotesRouteImport } from './routes/tender-quotes'
import { Route as TenderRfpIntakesRouteImport } from './routes/tender-rfp-intakes'
import { Route as TenderRoundsRouteImport } from './routes/tender-rounds'
import { Route as TenderTedNoticesRouteImport } from './routes/tender-ted-notices'
import { Route as TenderWinLossesRouteImport } from './routes/tender-win-losses'
import { Route as TendersRouteImport } from './routes/tenders'
import { Route as TerminalSlotConnectorsRouteImport } from './routes/terminal-slot-connectors'
import { Route as TerminalsRouteImport } from './routes/terminals'
import { Route as TowerImpactsRouteImport } from './routes/tower-impacts'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as TwinMarksRouteImport } from './routes/twin-marks'
import { Route as VisibilityConnectorsRouteImport } from './routes/visibility-connectors'
import { Route as WarRoomMarksRouteImport } from './routes/war-room-marks'
import { Route as WatchtowerRouteImport } from './routes/watchtower'
import { Route as WeatherObservationsRouteImport } from './routes/weather-observations'
import { Route as TenancyUsersRouteImport } from './routes/tenancy.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AirRoute = AirRouteImport.update({
  id: '/air',
  path: '/air',
  getParentRoute: () => rootRouteImport,
} as any)
const AsnsRoute = AsnsRouteImport.update({
  id: '/asns',
  path: '/asns',
  getParentRoute: () => rootRouteImport,
} as any)
const BookkeepingRoute = BookkeepingRouteImport.update({
  id: '/bookkeeping',
  path: '/bookkeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const CarbonMethodsRoute = CarbonMethodsRouteImport.update({
  id: '/carbon-methods',
  path: '/carbon-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const CashDiscountsRoute = CashDiscountsRouteImport.update({
  id: '/cash-discounts',
  path: '/cash-discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const CashflowsRoute = CashflowsRouteImport.update({
  id: '/cashflows',
  path: '/cashflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelQuotesRoute = ChannelQuotesRouteImport.update({
  id: '/channel-quotes',
  path: '/channel-quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChargeCodesRoute = ChargeCodesRouteImport.update({
  id: '/charge-codes',
  path: '/charge-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChargeTemplatesRoute = ChargeTemplatesRouteImport.update({
  id: '/charge-templates',
  path: '/charge-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ChargesRoute = ChargesRouteImport.update({
  id: '/charges',
  path: '/charges',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinaRailRoute = ChinaRailRouteImport.update({
  id: '/china-rail',
  path: '/china-rail',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleSimsRoute = CircleSimsRouteImport.update({
  id: '/circle-sims',
  path: '/circle-sims',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const CodRoute = CodRouteImport.update({
  id: '/cod',
  path: '/cod',
  getParentRoute: () => rootRouteImport,
} as any)
const CommodityCodesRoute = CommodityCodesRouteImport.update({
  id: '/commodity-codes',
  path: '/commodity-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsignmentsRoute = ConsignmentsRouteImport.update({
  id: '/consignments',
  path: '/consignments',
  getParentRoute: () => rootRouteImport,
} as any)
const CostToServeRoute = CostToServeRouteImport.update({
  id: '/cost-to-serve',
  path: '/cost-to-serve',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditReviewsRoute = CreditReviewsRouteImport.update({
  id: '/credit-reviews',
  path: '/credit-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerContractsRoute = CustomerContractsRouteImport.update({
  id: '/customer-contracts',
  path: '/customer-contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSopsRoute = CustomerSopsRouteImport.update({
  id: '/customer-sops',
  path: '/customer-sops',
  getParentRoute: () => rootRouteImport,
} as any)
const DangerousGoodsRoute = DangerousGoodsRouteImport.update({
  id: '/dangerous-goods',
  path: '/dangerous-goods',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const DockAppointmentsRoute = DockAppointmentsRouteImport.update({
  id: '/dock-appointments',
  path: '/dock-appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentTemplatesRoute = DocumentTemplatesRouteImport.update({
  id: '/document-templates',
  path: '/document-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const EdiRoute = EdiRouteImport.update({
  id: '/edi',
  path: '/edi',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityEventsRoute = EntityEventsRouteImport.update({
  id: '/entity-events',
  path: '/entity-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ErpConnectorsRoute = ErpConnectorsRouteImport.update({
  id: '/erp-connectors',
  path: '/erp-connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsRoute = ExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeConnectorsRoute = ExchangeConnectorsRouteImport.update({
  id: '/exchange-connectors',
  path: '/exchange-connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveMarksRoute = ExecutiveMarksRouteImport.update({
  id: '/executive-marks',
  path: '/executive-marks',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractionsRoute = ExtractionsRouteImport.update({
  id: '/extractions',
  path: '/extractions',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudRoute = FraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeTimeClocksRoute = FreeTimeClocksRouteImport.update({
  id: '/free-time-clocks',
  path: '/free-time-clocks',
  getParentRoute: () => rootRouteImport,
} as any)
const FuelIndexesRoute = FuelIndexesRouteImport.update({
  id: '/fuel-indexes',
  path: '/fuel-indexes',
  getParentRoute: () => rootRouteImport,
} as any)
const FxDifferencesRoute = FxDifferencesRouteImport.update({
  id: '/fx-differences',
  path: '/fx-differences',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupageRoute = GroupageRouteImport.update({
  id: '/groupage',
  path: '/groupage',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupageTariffsRoute = GroupageTariffsRouteImport.update({
  id: '/groupage-tariffs',
  path: '/groupage-tariffs',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IdpConnectorsRoute = IdpConnectorsRouteImport.update({
  id: '/idp-connectors',
  path: '/idp-connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const KreptdLicencesRoute = KreptdLicencesRouteImport.update({
  id: '/kreptd-licences',
  path: '/kreptd-licences',
  getParentRoute: () => rootRouteImport,
} as any)
const LaneKmsRoute = LaneKmsRouteImport.update({
  id: '/lane-kms',
  path: '/lane-kms',
  getParentRoute: () => rootRouteImport,
} as any)
const LanePatternsRoute = LanePatternsRouteImport.update({
  id: '/lane-patterns',
  path: '/lane-patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const LclRoute = LclRouteImport.update({
  id: '/lcl',
  path: '/lcl',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalChargesRoute = LocalChargesRouteImport.update({
  id: '/local-charges',
  path: '/local-charges',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryEdgesRoute = MemoryEdgesRouteImport.update({
  id: '/memory-edges',
  path: '/memory-edges',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyCostRoute = MoneyCostRouteImport.update({
  id: '/money-cost',
  path: '/money-cost',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringSchemesRoute = MonitoringSchemesRouteImport.update({
  id: '/monitoring-schemes',
  path: '/monitoring-schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const NbpRatesRoute = NbpRatesRouteImport.update({
  id: '/nbp-rates',
  path: '/nbp-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworksRoute = NetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OceanBillsRoute = OceanBillsRouteImport.update({
  id: '/ocean-bills',
  path: '/ocean-bills',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSettingsRoute = OrganizationSettingsRouteImport.update({
  id: '/organization-settings',
  path: '/organization-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OutboxRoute = OutboxRouteImport.update({
  id: '/outbox',
  path: '/outbox',
  getParentRoute: () => rootRouteImport,
} as any)
const PalletBalancesRoute = PalletBalancesRouteImport.update({
  id: '/pallet-balances',
  path: '/pallet-balances',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesRoute = PartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyDocumentsRoute = PartyDocumentsRouteImport.update({
  id: '/party-documents',
  path: '/party-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyScorecardsRoute = PartyScorecardsRouteImport.update({
  id: '/party-scorecards',
  path: '/party-scorecards',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanSnapshotsRoute = PlanSnapshotsRouteImport.update({
  id: '/plan-snapshots',
  path: '/plan-snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const PoLinesRoute = PoLinesRouteImport.update({
  id: '/po-lines',
  path: '/po-lines',
  getParentRoute: () => rootRouteImport,
} as any)
const PortSurchargesRoute = PortSurchargesRouteImport.update({
  id: '/port-surcharges',
  path: '/port-surcharges',
  getParentRoute: () => rootRouteImport,
} as any)
const PortsRoute = PortsRouteImport.update({
  id: '/ports',
  path: '/ports',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionLedgersRoute = PredictionLedgersRouteImport.update({
  id: '/prediction-ledgers',
  path: '/prediction-ledgers',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteInvoicesRoute = QuoteInvoicesRouteImport.update({
  id: '/quote-invoices',
  path: '/quote-invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const RailRoute = RailRouteImport.update({
  id: '/rail',
  path: '/rail',
  getParentRoute: () => rootRouteImport,
} as any)
const RankMarksRoute = RankMarksRouteImport.update({
  id: '/rank-marks',
  path: '/rank-marks',
  getParentRoute: () => rootRouteImport,
} as any)
const RateCardsRoute = RateCardsRouteImport.update({
  id: '/rate-cards',
  path: '/rate-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const RateLinesRoute = RateLinesRouteImport.update({
  id: '/rate-lines',
  path: '/rate-lines',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadRoute = RoadRouteImport.update({
  id: '/road',
  path: '/road',
  getParentRoute: () => rootRouteImport,
} as any)
const RolloutRoute = RolloutRouteImport.update({
  id: '/rollout',
  path: '/rollout',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutingGuidesRoute = RoutingGuidesRouteImport.update({
  id: '/routing-guides',
  path: '/routing-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const SanctionsRoute = SanctionsRouteImport.update({
  id: '/sanctions',
  path: '/sanctions',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentDocumentsRoute = ShipmentDocumentsRouteImport.update({
  id: '/shipment-documents',
  path: '/shipment-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentPackagesRoute = ShipmentPackagesRouteImport.update({
  id: '/shipment-packages',
  path: '/shipment-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskTemplatesRoute = TaskTemplatesRouteImport.update({
  id: '/task-templates',
  path: '/task-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TelematicsConnectorsRoute = TelematicsConnectorsRouteImport.update({
  id: '/telematics-connectors',
  path: '/telematics-connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantContractKeksRoute = TenantContractKeksRouteImport.update({
  id: '/tenant-contract-keks',
  path: '/tenant-contract-keks',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderAwardReviewsRoute = TenderAwardReviewsRouteImport.update({
  id: '/tender-award-reviews',
  path: '/tender-award-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderBidStancesRoute = TenderBidStancesRouteImport.update({
  id: '/tender-bid-stances',
  path: '/tender-bid-stances',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderCarbonMarksRoute = TenderCarbonMarksRouteImport.update({
  id: '/tender-carbon-marks',
  path: '/tender-carbon-marks',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderConsortiumMembersRoute = TenderConsortiumMembersRouteImport.update({
  id: '/tender-consortium-members',
  path: '/tender-consortium-members',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderDataRoomsRoute = TenderDataRoomsRouteImport.update({
  id: '/tender-data-rooms',
  path: '/tender-data-rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderLanesRoute = TenderLanesRouteImport.update({
  id: '/tender-lanes',
  path: '/tender-lanes',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderLotsRoute = TenderLotsRouteImport.update({
  id: '/tender-lots',
  path: '/tender-lots',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderMatrixCellsRoute = TenderMatrixCellsRouteImport.update({
  id: '/tender-matrix-cells',
  path: '/tender-matrix-cells',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderPlaybooksRoute = TenderPlaybooksRouteImport.update({
  id: '/tender-playbooks',
  path: '/tender-playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderProspectsRoute = TenderProspectsRouteImport.update({
  id: '/tender-prospects',
  path: '/tender-prospects',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderQuotesRoute = TenderQuotesRouteImport.update({
  id: '/tender-quotes',
  path: '/tender-quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderRfpIntakesRoute = TenderRfpIntakesRouteImport.update({
  id: '/tender-rfp-intakes',
  path: '/tender-rfp-intakes',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderRoundsRoute = TenderRoundsRouteImport.update({
  id: '/tender-rounds',
  path: '/tender-rounds',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderTedNoticesRoute = TenderTedNoticesRouteImport.update({
  id: '/tender-ted-notices',
  path: '/tender-ted-notices',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderWinLossesRoute = TenderWinLossesRouteImport.update({
  id: '/tender-win-losses',
  path: '/tender-win-losses',
  getParentRoute: () => rootRouteImport,
} as any)
const TendersRoute = TendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalSlotConnectorsRoute = TerminalSlotConnectorsRouteImport.update({
  id: '/terminal-slot-connectors',
  path: '/terminal-slot-connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalsRoute = TerminalsRouteImport.update({
  id: '/terminals',
  path: '/terminals',
  getParentRoute: () => rootRouteImport,
} as any)
const TowerImpactsRoute = TowerImpactsRouteImport.update({
  id: '/tower-impacts',
  path: '/tower-impacts',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const TwinMarksRoute = TwinMarksRouteImport.update({
  id: '/twin-marks',
  path: '/twin-marks',
  getParentRoute: () => rootRouteImport,
} as any)
const VisibilityConnectorsRoute = VisibilityConnectorsRouteImport.update({
  id: '/visibility-connectors',
  path: '/visibility-connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const WarRoomMarksRoute = WarRoomMarksRouteImport.update({
  id: '/war-room-marks',
  path: '/war-room-marks',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchtowerRoute = WatchtowerRouteImport.update({
  id: '/watchtower',
  path: '/watchtower',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherObservationsRoute = WeatherObservationsRouteImport.update({
  id: '/weather-observations',
  path: '/weather-observations',
  getParentRoute: () => rootRouteImport,
} as any)
const TenancyUsersRoute = TenancyUsersRouteImport.update({
  id: '/tenancy/users',
  path: '/tenancy/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/air': typeof AirRoute
  '/asns': typeof AsnsRoute
  '/bookkeeping': typeof BookkeepingRoute
  '/carbon-methods': typeof CarbonMethodsRoute
  '/cash-discounts': typeof CashDiscountsRoute
  '/cashflows': typeof CashflowsRoute
  '/channel-quotes': typeof ChannelQuotesRoute
  '/charge-codes': typeof ChargeCodesRoute
  '/charge-templates': typeof ChargeTemplatesRoute
  '/charges': typeof ChargesRoute
  '/china-rail': typeof ChinaRailRoute
  '/circle-sims': typeof CircleSimsRoute
  '/claims': typeof ClaimsRoute
  '/cod': typeof CodRoute
  '/commodity-codes': typeof CommodityCodesRoute
  '/consignments': typeof ConsignmentsRoute
  '/cost-to-serve': typeof CostToServeRoute
  '/credit-reviews': typeof CreditReviewsRoute
  '/customer-contracts': typeof CustomerContractsRoute
  '/customer-sops': typeof CustomerSopsRoute
  '/dangerous-goods': typeof DangerousGoodsRoute
  '/decisions': typeof DecisionsRoute
  '/dock-appointments': typeof DockAppointmentsRoute
  '/document-templates': typeof DocumentTemplatesRoute
  '/edi': typeof EdiRoute
  '/entity-events': typeof EntityEventsRoute
  '/erp-connectors': typeof ErpConnectorsRoute
  '/exceptions': typeof ExceptionsRoute
  '/exchange-connectors': typeof ExchangeConnectorsRoute
  '/executive-marks': typeof ExecutiveMarksRoute
  '/extractions': typeof ExtractionsRoute
  '/finance': typeof FinanceRoute
  '/fleet': typeof FleetRoute
  '/fraud': typeof FraudRoute
  '/free-time-clocks': typeof FreeTimeClocksRoute
  '/fuel-indexes': typeof FuelIndexesRoute
  '/fx-differences': typeof FxDifferencesRoute
  '/gdpr': typeof GdprRoute
  '/groupage': typeof GroupageRoute
  '/groupage-tariffs': typeof GroupageTariffsRoute
  '/health': typeof HealthRoute
  '/idp-connectors': typeof IdpConnectorsRoute
  '/invoices': typeof InvoicesRoute
  '/kreptd-licences': typeof KreptdLicencesRoute
  '/lane-kms': typeof LaneKmsRoute
  '/lane-patterns': typeof LanePatternsRoute
  '/lcl': typeof LclRoute
  '/local-charges': typeof LocalChargesRoute
  '/locations': typeof LocationsRoute
  '/mail': typeof MailRoute
  '/memory-edges': typeof MemoryEdgesRoute
  '/money-cost': typeof MoneyCostRoute
  '/monitoring-schemes': typeof MonitoringSchemesRoute
  '/nbp-rates': typeof NbpRatesRoute
  '/networks': typeof NetworksRoute
  '/notifications': typeof NotificationsRoute
  '/ocean-bills': typeof OceanBillsRoute
  '/organization-settings': typeof OrganizationSettingsRoute
  '/outbox': typeof OutboxRoute
  '/pallet-balances': typeof PalletBalancesRoute
  '/parties': typeof PartiesRoute
  '/party-documents': typeof PartyDocumentsRoute
  '/party-scorecards': typeof PartyScorecardsRoute
  '/payments': typeof PaymentsRoute
  '/plan-snapshots': typeof PlanSnapshotsRoute
  '/planning': typeof PlanningRoute
  '/po-lines': typeof PoLinesRoute
  '/port-surcharges': typeof PortSurchargesRoute
  '/ports': typeof PortsRoute
  '/prediction-ledgers': typeof PredictionLedgersRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/quality': typeof QualityRoute
  '/quotations': typeof QuotationsRoute
  '/quote-invoices': typeof QuoteInvoicesRoute
  '/rail': typeof RailRoute
  '/rank-marks': typeof RankMarksRoute
  '/rate-cards': typeof RateCardsRoute
  '/rate-lines': typeof RateLinesRoute
  '/road': typeof RoadRoute
  '/rollout': typeof RolloutRoute
  '/routing-guides': typeof RoutingGuidesRoute
  '/sanctions': typeof SanctionsRoute
  '/session': typeof SessionRoute
  '/shipment-documents': typeof ShipmentDocumentsRoute
  '/shipment-packages': typeof ShipmentPackagesRoute
  '/shipments': typeof ShipmentsRoute
  '/task-templates': typeof TaskTemplatesRoute
  '/telematics-connectors': typeof TelematicsConnectorsRoute
  '/tenant-contract-keks': typeof TenantContractKeksRoute
  '/tender-award-reviews': typeof TenderAwardReviewsRoute
  '/tender-bid-stances': typeof TenderBidStancesRoute
  '/tender-carbon-marks': typeof TenderCarbonMarksRoute
  '/tender-consortium-members': typeof TenderConsortiumMembersRoute
  '/tender-data-rooms': typeof TenderDataRoomsRoute
  '/tender-lanes': typeof TenderLanesRoute
  '/tender-lots': typeof TenderLotsRoute
  '/tender-matrix-cells': typeof TenderMatrixCellsRoute
  '/tender-playbooks': typeof TenderPlaybooksRoute
  '/tender-prospects': typeof TenderProspectsRoute
  '/tender-quotes': typeof TenderQuotesRoute
  '/tender-rfp-intakes': typeof TenderRfpIntakesRoute
  '/tender-rounds': typeof TenderRoundsRoute
  '/tender-ted-notices': typeof TenderTedNoticesRoute
  '/tender-win-losses': typeof TenderWinLossesRoute
  '/tenders': typeof TendersRoute
  '/terminal-slot-connectors': typeof TerminalSlotConnectorsRoute
  '/terminals': typeof TerminalsRoute
  '/tower-impacts': typeof TowerImpactsRoute
  '/tracking': typeof TrackingRoute
  '/twin-marks': typeof TwinMarksRoute
  '/visibility-connectors': typeof VisibilityConnectorsRoute
  '/war-room-marks': typeof WarRoomMarksRoute
  '/watchtower': typeof WatchtowerRoute
  '/weather-observations': typeof WeatherObservationsRoute
  '/tenancy/users': typeof TenancyUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/air': typeof AirRoute
  '/asns': typeof AsnsRoute
  '/bookkeeping': typeof BookkeepingRoute
  '/carbon-methods': typeof CarbonMethodsRoute
  '/cash-discounts': typeof CashDiscountsRoute
  '/cashflows': typeof CashflowsRoute
  '/channel-quotes': typeof ChannelQuotesRoute
  '/charge-codes': typeof ChargeCodesRoute
  '/charge-templates': typeof ChargeTemplatesRoute
  '/charges': typeof ChargesRoute
  '/china-rail': typeof ChinaRailRoute
  '/circle-sims': typeof CircleSimsRoute
  '/claims': typeof ClaimsRoute
  '/cod': typeof CodRoute
  '/commodity-codes': typeof CommodityCodesRoute
  '/consignments': typeof ConsignmentsRoute
  '/cost-to-serve': typeof CostToServeRoute
  '/credit-reviews': typeof CreditReviewsRoute
  '/customer-contracts': typeof CustomerContractsRoute
  '/customer-sops': typeof CustomerSopsRoute
  '/dangerous-goods': typeof DangerousGoodsRoute
  '/decisions': typeof DecisionsRoute
  '/dock-appointments': typeof DockAppointmentsRoute
  '/document-templates': typeof DocumentTemplatesRoute
  '/edi': typeof EdiRoute
  '/entity-events': typeof EntityEventsRoute
  '/erp-connectors': typeof ErpConnectorsRoute
  '/exceptions': typeof ExceptionsRoute
  '/exchange-connectors': typeof ExchangeConnectorsRoute
  '/executive-marks': typeof ExecutiveMarksRoute
  '/extractions': typeof ExtractionsRoute
  '/finance': typeof FinanceRoute
  '/fleet': typeof FleetRoute
  '/fraud': typeof FraudRoute
  '/free-time-clocks': typeof FreeTimeClocksRoute
  '/fuel-indexes': typeof FuelIndexesRoute
  '/fx-differences': typeof FxDifferencesRoute
  '/gdpr': typeof GdprRoute
  '/groupage': typeof GroupageRoute
  '/groupage-tariffs': typeof GroupageTariffsRoute
  '/health': typeof HealthRoute
  '/idp-connectors': typeof IdpConnectorsRoute
  '/invoices': typeof InvoicesRoute
  '/kreptd-licences': typeof KreptdLicencesRoute
  '/lane-kms': typeof LaneKmsRoute
  '/lane-patterns': typeof LanePatternsRoute
  '/lcl': typeof LclRoute
  '/local-charges': typeof LocalChargesRoute
  '/locations': typeof LocationsRoute
  '/mail': typeof MailRoute
  '/memory-edges': typeof MemoryEdgesRoute
  '/money-cost': typeof MoneyCostRoute
  '/monitoring-schemes': typeof MonitoringSchemesRoute
  '/nbp-rates': typeof NbpRatesRoute
  '/networks': typeof NetworksRoute
  '/notifications': typeof NotificationsRoute
  '/ocean-bills': typeof OceanBillsRoute
  '/organization-settings': typeof OrganizationSettingsRoute
  '/outbox': typeof OutboxRoute
  '/pallet-balances': typeof PalletBalancesRoute
  '/parties': typeof PartiesRoute
  '/party-documents': typeof PartyDocumentsRoute
  '/party-scorecards': typeof PartyScorecardsRoute
  '/payments': typeof PaymentsRoute
  '/plan-snapshots': typeof PlanSnapshotsRoute
  '/planning': typeof PlanningRoute
  '/po-lines': typeof PoLinesRoute
  '/port-surcharges': typeof PortSurchargesRoute
  '/ports': typeof PortsRoute
  '/prediction-ledgers': typeof PredictionLedgersRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/quality': typeof QualityRoute
  '/quotations': typeof QuotationsRoute
  '/quote-invoices': typeof QuoteInvoicesRoute
  '/rail': typeof RailRoute
  '/rank-marks': typeof RankMarksRoute
  '/rate-cards': typeof RateCardsRoute
  '/rate-lines': typeof RateLinesRoute
  '/road': typeof RoadRoute
  '/rollout': typeof RolloutRoute
  '/routing-guides': typeof RoutingGuidesRoute
  '/sanctions': typeof SanctionsRoute
  '/session': typeof SessionRoute
  '/shipment-documents': typeof ShipmentDocumentsRoute
  '/shipment-packages': typeof ShipmentPackagesRoute
  '/shipments': typeof ShipmentsRoute
  '/task-templates': typeof TaskTemplatesRoute
  '/telematics-connectors': typeof TelematicsConnectorsRoute
  '/tenant-contract-keks': typeof TenantContractKeksRoute
  '/tender-award-reviews': typeof TenderAwardReviewsRoute
  '/tender-bid-stances': typeof TenderBidStancesRoute
  '/tender-carbon-marks': typeof TenderCarbonMarksRoute
  '/tender-consortium-members': typeof TenderConsortiumMembersRoute
  '/tender-data-rooms': typeof TenderDataRoomsRoute
  '/tender-lanes': typeof TenderLanesRoute
  '/tender-lots': typeof TenderLotsRoute
  '/tender-matrix-cells': typeof TenderMatrixCellsRoute
  '/tender-playbooks': typeof TenderPlaybooksRoute
  '/tender-prospects': typeof TenderProspectsRoute
  '/tender-quotes': typeof TenderQuotesRoute
  '/tender-rfp-intakes': typeof TenderRfpIntakesRoute
  '/tender-rounds': typeof TenderRoundsRoute
  '/tender-ted-notices': typeof TenderTedNoticesRoute
  '/tender-win-losses': typeof TenderWinLossesRoute
  '/tenders': typeof TendersRoute
  '/terminal-slot-connectors': typeof TerminalSlotConnectorsRoute
  '/terminals': typeof TerminalsRoute
  '/tower-impacts': typeof TowerImpactsRoute
  '/tracking': typeof TrackingRoute
  '/twin-marks': typeof TwinMarksRoute
  '/visibility-connectors': typeof VisibilityConnectorsRoute
  '/war-room-marks': typeof WarRoomMarksRoute
  '/watchtower': typeof WatchtowerRoute
  '/weather-observations': typeof WeatherObservationsRoute
  '/tenancy/users': typeof TenancyUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/air': typeof AirRoute
  '/asns': typeof AsnsRoute
  '/bookkeeping': typeof BookkeepingRoute
  '/carbon-methods': typeof CarbonMethodsRoute
  '/cash-discounts': typeof CashDiscountsRoute
  '/cashflows': typeof CashflowsRoute
  '/channel-quotes': typeof ChannelQuotesRoute
  '/charge-codes': typeof ChargeCodesRoute
  '/charge-templates': typeof ChargeTemplatesRoute
  '/charges': typeof ChargesRoute
  '/china-rail': typeof ChinaRailRoute
  '/circle-sims': typeof CircleSimsRoute
  '/claims': typeof ClaimsRoute
  '/cod': typeof CodRoute
  '/commodity-codes': typeof CommodityCodesRoute
  '/consignments': typeof ConsignmentsRoute
  '/cost-to-serve': typeof CostToServeRoute
  '/credit-reviews': typeof CreditReviewsRoute
  '/customer-contracts': typeof CustomerContractsRoute
  '/customer-sops': typeof CustomerSopsRoute
  '/dangerous-goods': typeof DangerousGoodsRoute
  '/decisions': typeof DecisionsRoute
  '/dock-appointments': typeof DockAppointmentsRoute
  '/document-templates': typeof DocumentTemplatesRoute
  '/edi': typeof EdiRoute
  '/entity-events': typeof EntityEventsRoute
  '/erp-connectors': typeof ErpConnectorsRoute
  '/exceptions': typeof ExceptionsRoute
  '/exchange-connectors': typeof ExchangeConnectorsRoute
  '/executive-marks': typeof ExecutiveMarksRoute
  '/extractions': typeof ExtractionsRoute
  '/finance': typeof FinanceRoute
  '/fleet': typeof FleetRoute
  '/fraud': typeof FraudRoute
  '/free-time-clocks': typeof FreeTimeClocksRoute
  '/fuel-indexes': typeof FuelIndexesRoute
  '/fx-differences': typeof FxDifferencesRoute
  '/gdpr': typeof GdprRoute
  '/groupage': typeof GroupageRoute
  '/groupage-tariffs': typeof GroupageTariffsRoute
  '/health': typeof HealthRoute
  '/idp-connectors': typeof IdpConnectorsRoute
  '/invoices': typeof InvoicesRoute
  '/kreptd-licences': typeof KreptdLicencesRoute
  '/lane-kms': typeof LaneKmsRoute
  '/lane-patterns': typeof LanePatternsRoute
  '/lcl': typeof LclRoute
  '/local-charges': typeof LocalChargesRoute
  '/locations': typeof LocationsRoute
  '/mail': typeof MailRoute
  '/memory-edges': typeof MemoryEdgesRoute
  '/money-cost': typeof MoneyCostRoute
  '/monitoring-schemes': typeof MonitoringSchemesRoute
  '/nbp-rates': typeof NbpRatesRoute
  '/networks': typeof NetworksRoute
  '/notifications': typeof NotificationsRoute
  '/ocean-bills': typeof OceanBillsRoute
  '/organization-settings': typeof OrganizationSettingsRoute
  '/outbox': typeof OutboxRoute
  '/pallet-balances': typeof PalletBalancesRoute
  '/parties': typeof PartiesRoute
  '/party-documents': typeof PartyDocumentsRoute
  '/party-scorecards': typeof PartyScorecardsRoute
  '/payments': typeof PaymentsRoute
  '/plan-snapshots': typeof PlanSnapshotsRoute
  '/planning': typeof PlanningRoute
  '/po-lines': typeof PoLinesRoute
  '/port-surcharges': typeof PortSurchargesRoute
  '/ports': typeof PortsRoute
  '/prediction-ledgers': typeof PredictionLedgersRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/quality': typeof QualityRoute
  '/quotations': typeof QuotationsRoute
  '/quote-invoices': typeof QuoteInvoicesRoute
  '/rail': typeof RailRoute
  '/rank-marks': typeof RankMarksRoute
  '/rate-cards': typeof RateCardsRoute
  '/rate-lines': typeof RateLinesRoute
  '/road': typeof RoadRoute
  '/rollout': typeof RolloutRoute
  '/routing-guides': typeof RoutingGuidesRoute
  '/sanctions': typeof SanctionsRoute
  '/session': typeof SessionRoute
  '/shipment-documents': typeof ShipmentDocumentsRoute
  '/shipment-packages': typeof ShipmentPackagesRoute
  '/shipments': typeof ShipmentsRoute
  '/task-templates': typeof TaskTemplatesRoute
  '/telematics-connectors': typeof TelematicsConnectorsRoute
  '/tenant-contract-keks': typeof TenantContractKeksRoute
  '/tender-award-reviews': typeof TenderAwardReviewsRoute
  '/tender-bid-stances': typeof TenderBidStancesRoute
  '/tender-carbon-marks': typeof TenderCarbonMarksRoute
  '/tender-consortium-members': typeof TenderConsortiumMembersRoute
  '/tender-data-rooms': typeof TenderDataRoomsRoute
  '/tender-lanes': typeof TenderLanesRoute
  '/tender-lots': typeof TenderLotsRoute
  '/tender-matrix-cells': typeof TenderMatrixCellsRoute
  '/tender-playbooks': typeof TenderPlaybooksRoute
  '/tender-prospects': typeof TenderProspectsRoute
  '/tender-quotes': typeof TenderQuotesRoute
  '/tender-rfp-intakes': typeof TenderRfpIntakesRoute
  '/tender-rounds': typeof TenderRoundsRoute
  '/tender-ted-notices': typeof TenderTedNoticesRoute
  '/tender-win-losses': typeof TenderWinLossesRoute
  '/tenders': typeof TendersRoute
  '/terminal-slot-connectors': typeof TerminalSlotConnectorsRoute
  '/terminals': typeof TerminalsRoute
  '/tower-impacts': typeof TowerImpactsRoute
  '/tracking': typeof TrackingRoute
  '/twin-marks': typeof TwinMarksRoute
  '/visibility-connectors': typeof VisibilityConnectorsRoute
  '/war-room-marks': typeof WarRoomMarksRoute
  '/watchtower': typeof WatchtowerRoute
  '/weather-observations': typeof WeatherObservationsRoute
  '/tenancy/users': typeof TenancyUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/air'
    | '/asns'
    | '/bookkeeping'
    | '/carbon-methods'
    | '/cash-discounts'
    | '/cashflows'
    | '/channel-quotes'
    | '/charge-codes'
    | '/charge-templates'
    | '/charges'
    | '/china-rail'
    | '/circle-sims'
    | '/claims'
    | '/cod'
    | '/commodity-codes'
    | '/consignments'
    | '/cost-to-serve'
    | '/credit-reviews'
    | '/customer-contracts'
    | '/customer-sops'
    | '/dangerous-goods'
    | '/decisions'
    | '/dock-appointments'
    | '/document-templates'
    | '/edi'
    | '/entity-events'
    | '/erp-connectors'
    | '/exceptions'
    | '/exchange-connectors'
    | '/executive-marks'
    | '/extractions'
    | '/finance'
    | '/fleet'
    | '/fraud'
    | '/free-time-clocks'
    | '/fuel-indexes'
    | '/fx-differences'
    | '/gdpr'
    | '/groupage'
    | '/groupage-tariffs'
    | '/health'
    | '/idp-connectors'
    | '/invoices'
    | '/kreptd-licences'
    | '/lane-kms'
    | '/lane-patterns'
    | '/lcl'
    | '/local-charges'
    | '/locations'
    | '/mail'
    | '/memory-edges'
    | '/money-cost'
    | '/monitoring-schemes'
    | '/nbp-rates'
    | '/networks'
    | '/notifications'
    | '/ocean-bills'
    | '/organization-settings'
    | '/outbox'
    | '/pallet-balances'
    | '/parties'
    | '/party-documents'
    | '/party-scorecards'
    | '/payments'
    | '/plan-snapshots'
    | '/planning'
    | '/po-lines'
    | '/port-surcharges'
    | '/ports'
    | '/prediction-ledgers'
    | '/purchase-orders'
    | '/quality'
    | '/quotations'
    | '/quote-invoices'
    | '/rail'
    | '/rank-marks'
    | '/rate-cards'
    | '/rate-lines'
    | '/road'
    | '/rollout'
    | '/routing-guides'
    | '/sanctions'
    | '/session'
    | '/shipment-documents'
    | '/shipment-packages'
    | '/shipments'
    | '/task-templates'
    | '/telematics-connectors'
    | '/tenant-contract-keks'
    | '/tender-award-reviews'
    | '/tender-bid-stances'
    | '/tender-carbon-marks'
    | '/tender-consortium-members'
    | '/tender-data-rooms'
    | '/tender-lanes'
    | '/tender-lots'
    | '/tender-matrix-cells'
    | '/tender-playbooks'
    | '/tender-prospects'
    | '/tender-quotes'
    | '/tender-rfp-intakes'
    | '/tender-rounds'
    | '/tender-ted-notices'
    | '/tender-win-losses'
    | '/tenders'
    | '/terminal-slot-connectors'
    | '/terminals'
    | '/tower-impacts'
    | '/tracking'
    | '/twin-marks'
    | '/visibility-connectors'
    | '/war-room-marks'
    | '/watchtower'
    | '/weather-observations'
    | '/tenancy/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/air'
    | '/asns'
    | '/bookkeeping'
    | '/carbon-methods'
    | '/cash-discounts'
    | '/cashflows'
    | '/channel-quotes'
    | '/charge-codes'
    | '/charge-templates'
    | '/charges'
    | '/china-rail'
    | '/circle-sims'
    | '/claims'
    | '/cod'
    | '/commodity-codes'
    | '/consignments'
    | '/cost-to-serve'
    | '/credit-reviews'
    | '/customer-contracts'
    | '/customer-sops'
    | '/dangerous-goods'
    | '/decisions'
    | '/dock-appointments'
    | '/document-templates'
    | '/edi'
    | '/entity-events'
    | '/erp-connectors'
    | '/exceptions'
    | '/exchange-connectors'
    | '/executive-marks'
    | '/extractions'
    | '/finance'
    | '/fleet'
    | '/fraud'
    | '/free-time-clocks'
    | '/fuel-indexes'
    | '/fx-differences'
    | '/gdpr'
    | '/groupage'
    | '/groupage-tariffs'
    | '/health'
    | '/idp-connectors'
    | '/invoices'
    | '/kreptd-licences'
    | '/lane-kms'
    | '/lane-patterns'
    | '/lcl'
    | '/local-charges'
    | '/locations'
    | '/mail'
    | '/memory-edges'
    | '/money-cost'
    | '/monitoring-schemes'
    | '/nbp-rates'
    | '/networks'
    | '/notifications'
    | '/ocean-bills'
    | '/organization-settings'
    | '/outbox'
    | '/pallet-balances'
    | '/parties'
    | '/party-documents'
    | '/party-scorecards'
    | '/payments'
    | '/plan-snapshots'
    | '/planning'
    | '/po-lines'
    | '/port-surcharges'
    | '/ports'
    | '/prediction-ledgers'
    | '/purchase-orders'
    | '/quality'
    | '/quotations'
    | '/quote-invoices'
    | '/rail'
    | '/rank-marks'
    | '/rate-cards'
    | '/rate-lines'
    | '/road'
    | '/rollout'
    | '/routing-guides'
    | '/sanctions'
    | '/session'
    | '/shipment-documents'
    | '/shipment-packages'
    | '/shipments'
    | '/task-templates'
    | '/telematics-connectors'
    | '/tenant-contract-keks'
    | '/tender-award-reviews'
    | '/tender-bid-stances'
    | '/tender-carbon-marks'
    | '/tender-consortium-members'
    | '/tender-data-rooms'
    | '/tender-lanes'
    | '/tender-lots'
    | '/tender-matrix-cells'
    | '/tender-playbooks'
    | '/tender-prospects'
    | '/tender-quotes'
    | '/tender-rfp-intakes'
    | '/tender-rounds'
    | '/tender-ted-notices'
    | '/tender-win-losses'
    | '/tenders'
    | '/terminal-slot-connectors'
    | '/terminals'
    | '/tower-impacts'
    | '/tracking'
    | '/twin-marks'
    | '/visibility-connectors'
    | '/war-room-marks'
    | '/watchtower'
    | '/weather-observations'
    | '/tenancy/users'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/air'
    | '/asns'
    | '/bookkeeping'
    | '/carbon-methods'
    | '/cash-discounts'
    | '/cashflows'
    | '/channel-quotes'
    | '/charge-codes'
    | '/charge-templates'
    | '/charges'
    | '/china-rail'
    | '/circle-sims'
    | '/claims'
    | '/cod'
    | '/commodity-codes'
    | '/consignments'
    | '/cost-to-serve'
    | '/credit-reviews'
    | '/customer-contracts'
    | '/customer-sops'
    | '/dangerous-goods'
    | '/decisions'
    | '/dock-appointments'
    | '/document-templates'
    | '/edi'
    | '/entity-events'
    | '/erp-connectors'
    | '/exceptions'
    | '/exchange-connectors'
    | '/executive-marks'
    | '/extractions'
    | '/finance'
    | '/fleet'
    | '/fraud'
    | '/free-time-clocks'
    | '/fuel-indexes'
    | '/fx-differences'
    | '/gdpr'
    | '/groupage'
    | '/groupage-tariffs'
    | '/health'
    | '/idp-connectors'
    | '/invoices'
    | '/kreptd-licences'
    | '/lane-kms'
    | '/lane-patterns'
    | '/lcl'
    | '/local-charges'
    | '/locations'
    | '/mail'
    | '/memory-edges'
    | '/money-cost'
    | '/monitoring-schemes'
    | '/nbp-rates'
    | '/networks'
    | '/notifications'
    | '/ocean-bills'
    | '/organization-settings'
    | '/outbox'
    | '/pallet-balances'
    | '/parties'
    | '/party-documents'
    | '/party-scorecards'
    | '/payments'
    | '/plan-snapshots'
    | '/planning'
    | '/po-lines'
    | '/port-surcharges'
    | '/ports'
    | '/prediction-ledgers'
    | '/purchase-orders'
    | '/quality'
    | '/quotations'
    | '/quote-invoices'
    | '/rail'
    | '/rank-marks'
    | '/rate-cards'
    | '/rate-lines'
    | '/road'
    | '/rollout'
    | '/routing-guides'
    | '/sanctions'
    | '/session'
    | '/shipment-documents'
    | '/shipment-packages'
    | '/shipments'
    | '/task-templates'
    | '/telematics-connectors'
    | '/tenant-contract-keks'
    | '/tender-award-reviews'
    | '/tender-bid-stances'
    | '/tender-carbon-marks'
    | '/tender-consortium-members'
    | '/tender-data-rooms'
    | '/tender-lanes'
    | '/tender-lots'
    | '/tender-matrix-cells'
    | '/tender-playbooks'
    | '/tender-prospects'
    | '/tender-quotes'
    | '/tender-rfp-intakes'
    | '/tender-rounds'
    | '/tender-ted-notices'
    | '/tender-win-losses'
    | '/tenders'
    | '/terminal-slot-connectors'
    | '/terminals'
    | '/tower-impacts'
    | '/tracking'
    | '/twin-marks'
    | '/visibility-connectors'
    | '/war-room-marks'
    | '/watchtower'
    | '/weather-observations'
    | '/tenancy/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AirRoute: typeof AirRoute
  AsnsRoute: typeof AsnsRoute
  BookkeepingRoute: typeof BookkeepingRoute
  CarbonMethodsRoute: typeof CarbonMethodsRoute
  CashDiscountsRoute: typeof CashDiscountsRoute
  CashflowsRoute: typeof CashflowsRoute
  ChannelQuotesRoute: typeof ChannelQuotesRoute
  ChargeCodesRoute: typeof ChargeCodesRoute
  ChargeTemplatesRoute: typeof ChargeTemplatesRoute
  ChargesRoute: typeof ChargesRoute
  ChinaRailRoute: typeof ChinaRailRoute
  CircleSimsRoute: typeof CircleSimsRoute
  ClaimsRoute: typeof ClaimsRoute
  CodRoute: typeof CodRoute
  CommodityCodesRoute: typeof CommodityCodesRoute
  ConsignmentsRoute: typeof ConsignmentsRoute
  CostToServeRoute: typeof CostToServeRoute
  CreditReviewsRoute: typeof CreditReviewsRoute
  CustomerContractsRoute: typeof CustomerContractsRoute
  CustomerSopsRoute: typeof CustomerSopsRoute
  DangerousGoodsRoute: typeof DangerousGoodsRoute
  DecisionsRoute: typeof DecisionsRoute
  DockAppointmentsRoute: typeof DockAppointmentsRoute
  DocumentTemplatesRoute: typeof DocumentTemplatesRoute
  EdiRoute: typeof EdiRoute
  EntityEventsRoute: typeof EntityEventsRoute
  ErpConnectorsRoute: typeof ErpConnectorsRoute
  ExceptionsRoute: typeof ExceptionsRoute
  ExchangeConnectorsRoute: typeof ExchangeConnectorsRoute
  ExecutiveMarksRoute: typeof ExecutiveMarksRoute
  ExtractionsRoute: typeof ExtractionsRoute
  FinanceRoute: typeof FinanceRoute
  FleetRoute: typeof FleetRoute
  FraudRoute: typeof FraudRoute
  FreeTimeClocksRoute: typeof FreeTimeClocksRoute
  FuelIndexesRoute: typeof FuelIndexesRoute
  FxDifferencesRoute: typeof FxDifferencesRoute
  GdprRoute: typeof GdprRoute
  GroupageRoute: typeof GroupageRoute
  GroupageTariffsRoute: typeof GroupageTariffsRoute
  HealthRoute: typeof HealthRoute
  IdpConnectorsRoute: typeof IdpConnectorsRoute
  InvoicesRoute: typeof InvoicesRoute
  KreptdLicencesRoute: typeof KreptdLicencesRoute
  LaneKmsRoute: typeof LaneKmsRoute
  LanePatternsRoute: typeof LanePatternsRoute
  LclRoute: typeof LclRoute
  LocalChargesRoute: typeof LocalChargesRoute
  LocationsRoute: typeof LocationsRoute
  MailRoute: typeof MailRoute
  MemoryEdgesRoute: typeof MemoryEdgesRoute
  MoneyCostRoute: typeof MoneyCostRoute
  MonitoringSchemesRoute: typeof MonitoringSchemesRoute
  NbpRatesRoute: typeof NbpRatesRoute
  NetworksRoute: typeof NetworksRoute
  NotificationsRoute: typeof NotificationsRoute
  OceanBillsRoute: typeof OceanBillsRoute
  OrganizationSettingsRoute: typeof OrganizationSettingsRoute
  OutboxRoute: typeof OutboxRoute
  PalletBalancesRoute: typeof PalletBalancesRoute
  PartiesRoute: typeof PartiesRoute
  PartyDocumentsRoute: typeof PartyDocumentsRoute
  PartyScorecardsRoute: typeof PartyScorecardsRoute
  PaymentsRoute: typeof PaymentsRoute
  PlanSnapshotsRoute: typeof PlanSnapshotsRoute
  PlanningRoute: typeof PlanningRoute
  PoLinesRoute: typeof PoLinesRoute
  PortSurchargesRoute: typeof PortSurchargesRoute
  PortsRoute: typeof PortsRoute
  PredictionLedgersRoute: typeof PredictionLedgersRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  QualityRoute: typeof QualityRoute
  QuotationsRoute: typeof QuotationsRoute
  QuoteInvoicesRoute: typeof QuoteInvoicesRoute
  RailRoute: typeof RailRoute
  RankMarksRoute: typeof RankMarksRoute
  RateCardsRoute: typeof RateCardsRoute
  RateLinesRoute: typeof RateLinesRoute
  RoadRoute: typeof RoadRoute
  RolloutRoute: typeof RolloutRoute
  RoutingGuidesRoute: typeof RoutingGuidesRoute
  SanctionsRoute: typeof SanctionsRoute
  SessionRoute: typeof SessionRoute
  ShipmentDocumentsRoute: typeof ShipmentDocumentsRoute
  ShipmentPackagesRoute: typeof ShipmentPackagesRoute
  ShipmentsRoute: typeof ShipmentsRoute
  TaskTemplatesRoute: typeof TaskTemplatesRoute
  TelematicsConnectorsRoute: typeof TelematicsConnectorsRoute
  TenantContractKeksRoute: typeof TenantContractKeksRoute
  TenderAwardReviewsRoute: typeof TenderAwardReviewsRoute
  TenderBidStancesRoute: typeof TenderBidStancesRoute
  TenderCarbonMarksRoute: typeof TenderCarbonMarksRoute
  TenderConsortiumMembersRoute: typeof TenderConsortiumMembersRoute
  TenderDataRoomsRoute: typeof TenderDataRoomsRoute
  TenderLanesRoute: typeof TenderLanesRoute
  TenderLotsRoute: typeof TenderLotsRoute
  TenderMatrixCellsRoute: typeof TenderMatrixCellsRoute
  TenderPlaybooksRoute: typeof TenderPlaybooksRoute
  TenderProspectsRoute: typeof TenderProspectsRoute
  TenderQuotesRoute: typeof TenderQuotesRoute
  TenderRfpIntakesRoute: typeof TenderRfpIntakesRoute
  TenderRoundsRoute: typeof TenderRoundsRoute
  TenderTedNoticesRoute: typeof TenderTedNoticesRoute
  TenderWinLossesRoute: typeof TenderWinLossesRoute
  TendersRoute: typeof TendersRoute
  TerminalSlotConnectorsRoute: typeof TerminalSlotConnectorsRoute
  TerminalsRoute: typeof TerminalsRoute
  TowerImpactsRoute: typeof TowerImpactsRoute
  TrackingRoute: typeof TrackingRoute
  TwinMarksRoute: typeof TwinMarksRoute
  VisibilityConnectorsRoute: typeof VisibilityConnectorsRoute
  WarRoomMarksRoute: typeof WarRoomMarksRoute
  WatchtowerRoute: typeof WatchtowerRoute
  WeatherObservationsRoute: typeof WeatherObservationsRoute
  TenancyUsersRoute: typeof TenancyUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/air': {
      id: '/air'
      path: '/air'
      fullPath: '/air'
      preLoaderRoute: typeof AirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asns': {
      id: '/asns'
      path: '/asns'
      fullPath: '/asns'
      preLoaderRoute: typeof AsnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookkeeping': {
      id: '/bookkeeping'
      path: '/bookkeeping'
      fullPath: '/bookkeeping'
      preLoaderRoute: typeof BookkeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carbon-methods': {
      id: '/carbon-methods'
      path: '/carbon-methods'
      fullPath: '/carbon-methods'
      preLoaderRoute: typeof CarbonMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-discounts': {
      id: '/cash-discounts'
      path: '/cash-discounts'
      fullPath: '/cash-discounts'
      preLoaderRoute: typeof CashDiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashflows': {
      id: '/cashflows'
      path: '/cashflows'
      fullPath: '/cashflows'
      preLoaderRoute: typeof CashflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel-quotes': {
      id: '/channel-quotes'
      path: '/channel-quotes'
      fullPath: '/channel-quotes'
      preLoaderRoute: typeof ChannelQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charge-codes': {
      id: '/charge-codes'
      path: '/charge-codes'
      fullPath: '/charge-codes'
      preLoaderRoute: typeof ChargeCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charge-templates': {
      id: '/charge-templates'
      path: '/charge-templates'
      fullPath: '/charge-templates'
      preLoaderRoute: typeof ChargeTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charges': {
      id: '/charges'
      path: '/charges'
      fullPath: '/charges'
      preLoaderRoute: typeof ChargesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/china-rail': {
      id: '/china-rail'
      path: '/china-rail'
      fullPath: '/china-rail'
      preLoaderRoute: typeof ChinaRailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle-sims': {
      id: '/circle-sims'
      path: '/circle-sims'
      fullPath: '/circle-sims'
      preLoaderRoute: typeof CircleSimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cod': {
      id: '/cod'
      path: '/cod'
      fullPath: '/cod'
      preLoaderRoute: typeof CodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commodity-codes': {
      id: '/commodity-codes'
      path: '/commodity-codes'
      fullPath: '/commodity-codes'
      preLoaderRoute: typeof CommodityCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consignments': {
      id: '/consignments'
      path: '/consignments'
      fullPath: '/consignments'
      preLoaderRoute: typeof ConsignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-to-serve': {
      id: '/cost-to-serve'
      path: '/cost-to-serve'
      fullPath: '/cost-to-serve'
      preLoaderRoute: typeof CostToServeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-reviews': {
      id: '/credit-reviews'
      path: '/credit-reviews'
      fullPath: '/credit-reviews'
      preLoaderRoute: typeof CreditReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-contracts': {
      id: '/customer-contracts'
      path: '/customer-contracts'
      fullPath: '/customer-contracts'
      preLoaderRoute: typeof CustomerContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-sops': {
      id: '/customer-sops'
      path: '/customer-sops'
      fullPath: '/customer-sops'
      preLoaderRoute: typeof CustomerSopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dangerous-goods': {
      id: '/dangerous-goods'
      path: '/dangerous-goods'
      fullPath: '/dangerous-goods'
      preLoaderRoute: typeof DangerousGoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dock-appointments': {
      id: '/dock-appointments'
      path: '/dock-appointments'
      fullPath: '/dock-appointments'
      preLoaderRoute: typeof DockAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-templates': {
      id: '/document-templates'
      path: '/document-templates'
      fullPath: '/document-templates'
      preLoaderRoute: typeof DocumentTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edi': {
      id: '/edi'
      path: '/edi'
      fullPath: '/edi'
      preLoaderRoute: typeof EdiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity-events': {
      id: '/entity-events'
      path: '/entity-events'
      fullPath: '/entity-events'
      preLoaderRoute: typeof EntityEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erp-connectors': {
      id: '/erp-connectors'
      path: '/erp-connectors'
      fullPath: '/erp-connectors'
      preLoaderRoute: typeof ErpConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions': {
      id: '/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof ExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange-connectors': {
      id: '/exchange-connectors'
      path: '/exchange-connectors'
      fullPath: '/exchange-connectors'
      preLoaderRoute: typeof ExchangeConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-marks': {
      id: '/executive-marks'
      path: '/executive-marks'
      fullPath: '/executive-marks'
      preLoaderRoute: typeof ExecutiveMarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extractions': {
      id: '/extractions'
      path: '/extractions'
      fullPath: '/extractions'
      preLoaderRoute: typeof ExtractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud': {
      id: '/fraud'
      path: '/fraud'
      fullPath: '/fraud'
      preLoaderRoute: typeof FraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-time-clocks': {
      id: '/free-time-clocks'
      path: '/free-time-clocks'
      fullPath: '/free-time-clocks'
      preLoaderRoute: typeof FreeTimeClocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuel-indexes': {
      id: '/fuel-indexes'
      path: '/fuel-indexes'
      fullPath: '/fuel-indexes'
      preLoaderRoute: typeof FuelIndexesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fx-differences': {
      id: '/fx-differences'
      path: '/fx-differences'
      fullPath: '/fx-differences'
      preLoaderRoute: typeof FxDifferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groupage': {
      id: '/groupage'
      path: '/groupage'
      fullPath: '/groupage'
      preLoaderRoute: typeof GroupageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groupage-tariffs': {
      id: '/groupage-tariffs'
      path: '/groupage-tariffs'
      fullPath: '/groupage-tariffs'
      preLoaderRoute: typeof GroupageTariffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idp-connectors': {
      id: '/idp-connectors'
      path: '/idp-connectors'
      fullPath: '/idp-connectors'
      preLoaderRoute: typeof IdpConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kreptd-licences': {
      id: '/kreptd-licences'
      path: '/kreptd-licences'
      fullPath: '/kreptd-licences'
      preLoaderRoute: typeof KreptdLicencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lane-kms': {
      id: '/lane-kms'
      path: '/lane-kms'
      fullPath: '/lane-kms'
      preLoaderRoute: typeof LaneKmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lane-patterns': {
      id: '/lane-patterns'
      path: '/lane-patterns'
      fullPath: '/lane-patterns'
      preLoaderRoute: typeof LanePatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lcl': {
      id: '/lcl'
      path: '/lcl'
      fullPath: '/lcl'
      preLoaderRoute: typeof LclRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-charges': {
      id: '/local-charges'
      path: '/local-charges'
      fullPath: '/local-charges'
      preLoaderRoute: typeof LocalChargesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory-edges': {
      id: '/memory-edges'
      path: '/memory-edges'
      fullPath: '/memory-edges'
      preLoaderRoute: typeof MemoryEdgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money-cost': {
      id: '/money-cost'
      path: '/money-cost'
      fullPath: '/money-cost'
      preLoaderRoute: typeof MoneyCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring-schemes': {
      id: '/monitoring-schemes'
      path: '/monitoring-schemes'
      fullPath: '/monitoring-schemes'
      preLoaderRoute: typeof MonitoringSchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nbp-rates': {
      id: '/nbp-rates'
      path: '/nbp-rates'
      fullPath: '/nbp-rates'
      preLoaderRoute: typeof NbpRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networks': {
      id: '/networks'
      path: '/networks'
      fullPath: '/networks'
      preLoaderRoute: typeof NetworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocean-bills': {
      id: '/ocean-bills'
      path: '/ocean-bills'
      fullPath: '/ocean-bills'
      preLoaderRoute: typeof OceanBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization-settings': {
      id: '/organization-settings'
      path: '/organization-settings'
      fullPath: '/organization-settings'
      preLoaderRoute: typeof OrganizationSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outbox': {
      id: '/outbox'
      path: '/outbox'
      fullPath: '/outbox'
      preLoaderRoute: typeof OutboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pallet-balances': {
      id: '/pallet-balances'
      path: '/pallet-balances'
      fullPath: '/pallet-balances'
      preLoaderRoute: typeof PalletBalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties': {
      id: '/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party-documents': {
      id: '/party-documents'
      path: '/party-documents'
      fullPath: '/party-documents'
      preLoaderRoute: typeof PartyDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party-scorecards': {
      id: '/party-scorecards'
      path: '/party-scorecards'
      fullPath: '/party-scorecards'
      preLoaderRoute: typeof PartyScorecardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-snapshots': {
      id: '/plan-snapshots'
      path: '/plan-snapshots'
      fullPath: '/plan-snapshots'
      preLoaderRoute: typeof PlanSnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/po-lines': {
      id: '/po-lines'
      path: '/po-lines'
      fullPath: '/po-lines'
      preLoaderRoute: typeof PoLinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/port-surcharges': {
      id: '/port-surcharges'
      path: '/port-surcharges'
      fullPath: '/port-surcharges'
      preLoaderRoute: typeof PortSurchargesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ports': {
      id: '/ports'
      path: '/ports'
      fullPath: '/ports'
      preLoaderRoute: typeof PortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediction-ledgers': {
      id: '/prediction-ledgers'
      path: '/prediction-ledgers'
      fullPath: '/prediction-ledgers'
      preLoaderRoute: typeof PredictionLedgersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote-invoices': {
      id: '/quote-invoices'
      path: '/quote-invoices'
      fullPath: '/quote-invoices'
      preLoaderRoute: typeof QuoteInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rail': {
      id: '/rail'
      path: '/rail'
      fullPath: '/rail'
      preLoaderRoute: typeof RailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rank-marks': {
      id: '/rank-marks'
      path: '/rank-marks'
      fullPath: '/rank-marks'
      preLoaderRoute: typeof RankMarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-cards': {
      id: '/rate-cards'
      path: '/rate-cards'
      fullPath: '/rate-cards'
      preLoaderRoute: typeof RateCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-lines': {
      id: '/rate-lines'
      path: '/rate-lines'
      fullPath: '/rate-lines'
      preLoaderRoute: typeof RateLinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/road': {
      id: '/road'
      path: '/road'
      fullPath: '/road'
      preLoaderRoute: typeof RoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rollout': {
      id: '/rollout'
      path: '/rollout'
      fullPath: '/rollout'
      preLoaderRoute: typeof RolloutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routing-guides': {
      id: '/routing-guides'
      path: '/routing-guides'
      fullPath: '/routing-guides'
      preLoaderRoute: typeof RoutingGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanctions': {
      id: '/sanctions'
      path: '/sanctions'
      fullPath: '/sanctions'
      preLoaderRoute: typeof SanctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipment-documents': {
      id: '/shipment-documents'
      path: '/shipment-documents'
      fullPath: '/shipment-documents'
      preLoaderRoute: typeof ShipmentDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipment-packages': {
      id: '/shipment-packages'
      path: '/shipment-packages'
      fullPath: '/shipment-packages'
      preLoaderRoute: typeof ShipmentPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-templates': {
      id: '/task-templates'
      path: '/task-templates'
      fullPath: '/task-templates'
      preLoaderRoute: typeof TaskTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telematics-connectors': {
      id: '/telematics-connectors'
      path: '/telematics-connectors'
      fullPath: '/telematics-connectors'
      preLoaderRoute: typeof TelematicsConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant-contract-keks': {
      id: '/tenant-contract-keks'
      path: '/tenant-contract-keks'
      fullPath: '/tenant-contract-keks'
      preLoaderRoute: typeof TenantContractKeksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender-award-reviews': {
      id: '/tender-award-reviews'
      path: '/tender-award-reviews'
      fullPath: '/tender-award-reviews'
      preLoaderRoute: typeof TenderAwardReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender-bid-stances': {
      id: '/tender-bid-stances'
      path: '/tender-bid-stances'
      fullPath: '/tender-bid-stances'
      preLoaderRoute: typeof TenderBidStancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender-carbon-marks': {
      id: '/tender-carbon-marks'
      path: '/tender-carbon-marks'
      fullPath: '/tender-carbon-marks'
      preLoaderRoute: typeof TenderCarbonMarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender-consortium-members': {
      id: '/tender-consortium-members'
      path: '/tender-consortium-members'
      fullPath: '/tender-consortium-members'
      preLoaderRoute: typeof TenderConsortiumMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender-data-rooms': {
      id: '/tender-data-rooms'
      path: '/tender-data-rooms'
      fullPath: '/tender-data-rooms'
      preLoaderRoute: typeof TenderDataRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender-lanes': {
      id: '/tender-lanes'
      path: '/tender-lanes'
      fullPath: '/tender-lanes'
      preLoaderRoute: typeof TenderLanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender-lots': {
      id: '/tender-lots'
      path: '/tender-lots'
      fullPath: '/tender-lots'
      preLoaderRoute: typeof TenderLotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender-matrix-cells': {
      id: '/tender-matrix-cells'
      path: '/tender-matrix-cells'
      fullPath: '/tender-matrix-cells'
      preLoaderRoute: typeof TenderMatrixCellsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender-playbooks': {
      id: '/tender-playbooks'
      path: '/tender-playbooks'
      fullPath: '/tender-playbooks'
      preLoaderRoute: typeof TenderPlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender-prospects': {
      id: '/tender-prospects'
      path: '/tender-prospects'
      fullPath: '/tender-prospects'
      preLoaderRoute: typeof TenderProspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender-quotes': {
      id: '/tender-quotes'
      path: '/tender-quotes'
      fullPath: '/tender-quotes'
      preLoaderRoute: typeof TenderQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender-rfp-intakes': {
      id: '/tender-rfp-intakes'
      path: '/tender-rfp-intakes'
      fullPath: '/tender-rfp-intakes'
      preLoaderRoute: typeof TenderRfpIntakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender-rounds': {
      id: '/tender-rounds'
      path: '/tender-rounds'
      fullPath: '/tender-rounds'
      preLoaderRoute: typeof TenderRoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender-ted-notices': {
      id: '/tender-ted-notices'
      path: '/tender-ted-notices'
      fullPath: '/tender-ted-notices'
      preLoaderRoute: typeof TenderTedNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender-win-losses': {
      id: '/tender-win-losses'
      path: '/tender-win-losses'
      fullPath: '/tender-win-losses'
      preLoaderRoute: typeof TenderWinLossesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenders': {
      id: '/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof TendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal-slot-connectors': {
      id: '/terminal-slot-connectors'
      path: '/terminal-slot-connectors'
      fullPath: '/terminal-slot-connectors'
      preLoaderRoute: typeof TerminalSlotConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminals': {
      id: '/terminals'
      path: '/terminals'
      fullPath: '/terminals'
      preLoaderRoute: typeof TerminalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tower-impacts': {
      id: '/tower-impacts'
      path: '/tower-impacts'
      fullPath: '/tower-impacts'
      preLoaderRoute: typeof TowerImpactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twin-marks': {
      id: '/twin-marks'
      path: '/twin-marks'
      fullPath: '/twin-marks'
      preLoaderRoute: typeof TwinMarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visibility-connectors': {
      id: '/visibility-connectors'
      path: '/visibility-connectors'
      fullPath: '/visibility-connectors'
      preLoaderRoute: typeof VisibilityConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/war-room-marks': {
      id: '/war-room-marks'
      path: '/war-room-marks'
      fullPath: '/war-room-marks'
      preLoaderRoute: typeof WarRoomMarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchtower': {
      id: '/watchtower'
      path: '/watchtower'
      fullPath: '/watchtower'
      preLoaderRoute: typeof WatchtowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather-observations': {
      id: '/weather-observations'
      path: '/weather-observations'
      fullPath: '/weather-observations'
      preLoaderRoute: typeof WeatherObservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenancy/users': {
      id: '/tenancy/users'
      path: '/tenancy/users'
      fullPath: '/tenancy/users'
      preLoaderRoute: typeof TenancyUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AirRoute: AirRoute,
  AsnsRoute: AsnsRoute,
  BookkeepingRoute: BookkeepingRoute,
  CarbonMethodsRoute: CarbonMethodsRoute,
  CashDiscountsRoute: CashDiscountsRoute,
  CashflowsRoute: CashflowsRoute,
  ChannelQuotesRoute: ChannelQuotesRoute,
  ChargeCodesRoute: ChargeCodesRoute,
  ChargeTemplatesRoute: ChargeTemplatesRoute,
  ChargesRoute: ChargesRoute,
  ChinaRailRoute: ChinaRailRoute,
  CircleSimsRoute: CircleSimsRoute,
  ClaimsRoute: ClaimsRoute,
  CodRoute: CodRoute,
  CommodityCodesRoute: CommodityCodesRoute,
  ConsignmentsRoute: ConsignmentsRoute,
  CostToServeRoute: CostToServeRoute,
  CreditReviewsRoute: CreditReviewsRoute,
  CustomerContractsRoute: CustomerContractsRoute,
  CustomerSopsRoute: CustomerSopsRoute,
  DangerousGoodsRoute: DangerousGoodsRoute,
  DecisionsRoute: DecisionsRoute,
  DockAppointmentsRoute: DockAppointmentsRoute,
  DocumentTemplatesRoute: DocumentTemplatesRoute,
  EdiRoute: EdiRoute,
  EntityEventsRoute: EntityEventsRoute,
  ErpConnectorsRoute: ErpConnectorsRoute,
  ExceptionsRoute: ExceptionsRoute,
  ExchangeConnectorsRoute: ExchangeConnectorsRoute,
  ExecutiveMarksRoute: ExecutiveMarksRoute,
  ExtractionsRoute: ExtractionsRoute,
  FinanceRoute: FinanceRoute,
  FleetRoute: FleetRoute,
  FraudRoute: FraudRoute,
  FreeTimeClocksRoute: FreeTimeClocksRoute,
  FuelIndexesRoute: FuelIndexesRoute,
  FxDifferencesRoute: FxDifferencesRoute,
  GdprRoute: GdprRoute,
  GroupageRoute: GroupageRoute,
  GroupageTariffsRoute: GroupageTariffsRoute,
  HealthRoute: HealthRoute,
  IdpConnectorsRoute: IdpConnectorsRoute,
  InvoicesRoute: InvoicesRoute,
  KreptdLicencesRoute: KreptdLicencesRoute,
  LaneKmsRoute: LaneKmsRoute,
  LanePatternsRoute: LanePatternsRoute,
  LclRoute: LclRoute,
  LocalChargesRoute: LocalChargesRoute,
  LocationsRoute: LocationsRoute,
  MailRoute: MailRoute,
  MemoryEdgesRoute: MemoryEdgesRoute,
  MoneyCostRoute: MoneyCostRoute,
  MonitoringSchemesRoute: MonitoringSchemesRoute,
  NbpRatesRoute: NbpRatesRoute,
  NetworksRoute: NetworksRoute,
  NotificationsRoute: NotificationsRoute,
  OceanBillsRoute: OceanBillsRoute,
  OrganizationSettingsRoute: OrganizationSettingsRoute,
  OutboxRoute: OutboxRoute,
  PalletBalancesRoute: PalletBalancesRoute,
  PartiesRoute: PartiesRoute,
  PartyDocumentsRoute: PartyDocumentsRoute,
  PartyScorecardsRoute: PartyScorecardsRoute,
  PaymentsRoute: PaymentsRoute,
  PlanSnapshotsRoute: PlanSnapshotsRoute,
  PlanningRoute: PlanningRoute,
  PoLinesRoute: PoLinesRoute,
  PortSurchargesRoute: PortSurchargesRoute,
  PortsRoute: PortsRoute,
  PredictionLedgersRoute: PredictionLedgersRoute,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  QualityRoute: QualityRoute,
  QuotationsRoute: QuotationsRoute,
  QuoteInvoicesRoute: QuoteInvoicesRoute,
  RailRoute: RailRoute,
  RankMarksRoute: RankMarksRoute,
  RateCardsRoute: RateCardsRoute,
  RateLinesRoute: RateLinesRoute,
  RoadRoute: RoadRoute,
  RolloutRoute: RolloutRoute,
  RoutingGuidesRoute: RoutingGuidesRoute,
  SanctionsRoute: SanctionsRoute,
  SessionRoute: SessionRoute,
  ShipmentDocumentsRoute: ShipmentDocumentsRoute,
  ShipmentPackagesRoute: ShipmentPackagesRoute,
  ShipmentsRoute: ShipmentsRoute,
  TaskTemplatesRoute: TaskTemplatesRoute,
  TelematicsConnectorsRoute: TelematicsConnectorsRoute,
  TenantContractKeksRoute: TenantContractKeksRoute,
  TenderAwardReviewsRoute: TenderAwardReviewsRoute,
  TenderBidStancesRoute: TenderBidStancesRoute,
  TenderCarbonMarksRoute: TenderCarbonMarksRoute,
  TenderConsortiumMembersRoute: TenderConsortiumMembersRoute,
  TenderDataRoomsRoute: TenderDataRoomsRoute,
  TenderLanesRoute: TenderLanesRoute,
  TenderLotsRoute: TenderLotsRoute,
  TenderMatrixCellsRoute: TenderMatrixCellsRoute,
  TenderPlaybooksRoute: TenderPlaybooksRoute,
  TenderProspectsRoute: TenderProspectsRoute,
  TenderQuotesRoute: TenderQuotesRoute,
  TenderRfpIntakesRoute: TenderRfpIntakesRoute,
  TenderRoundsRoute: TenderRoundsRoute,
  TenderTedNoticesRoute: TenderTedNoticesRoute,
  TenderWinLossesRoute: TenderWinLossesRoute,
  TendersRoute: TendersRoute,
  TerminalSlotConnectorsRoute: TerminalSlotConnectorsRoute,
  TerminalsRoute: TerminalsRoute,
  TowerImpactsRoute: TowerImpactsRoute,
  TrackingRoute: TrackingRoute,
  TwinMarksRoute: TwinMarksRoute,
  VisibilityConnectorsRoute: VisibilityConnectorsRoute,
  WarRoomMarksRoute: WarRoomMarksRoute,
  WatchtowerRoute: WatchtowerRoute,
  WeatherObservationsRoute: WeatherObservationsRoute,
  TenancyUsersRoute: TenancyUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
