/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChargeCodesRouteImport } from './routes/charge-codes'
import { Route as ExtractionsRouteImport } from './routes/extractions'
import { Route as SessionRouteImport } from './routes/session'
import { Route as TenancyUsersRouteImport } from './routes/tenancy.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChargeCodesRoute = ChargeCodesRouteImport.update({
  id: '/charge-codes',
  path: '/charge-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractionsRoute = ExtractionsRouteImport.update({
  id: '/extractions',
  path: '/extractions',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const TenancyUsersRoute = TenancyUsersRouteImport.update({
  id: '/tenancy/users',
  path: '/tenancy/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/charge-codes': typeof ChargeCodesRoute
  '/extractions': typeof ExtractionsRoute
  '/session': typeof SessionRoute
  '/tenancy/users': typeof TenancyUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charge-codes': typeof ChargeCodesRoute
  '/extractions': typeof ExtractionsRoute
  '/session': typeof SessionRoute
  '/tenancy/users': typeof TenancyUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/charge-codes': typeof ChargeCodesRoute
  '/extractions': typeof ExtractionsRoute
  '/session': typeof SessionRoute
  '/tenancy/users': typeof TenancyUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/charge-codes' | '/extractions' | '/session' | '/tenancy/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/charge-codes' | '/extractions' | '/session' | '/tenancy/users'
  id:
    | '__root__'
    | '/'
    | '/charge-codes'
    | '/extractions'
    | '/session'
    | '/tenancy/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChargeCodesRoute: typeof ChargeCodesRoute
  ExtractionsRoute: typeof ExtractionsRoute
  SessionRoute: typeof SessionRoute
  TenancyUsersRoute: typeof TenancyUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charge-codes': {
      id: '/charge-codes'
      path: '/charge-codes'
      fullPath: '/charge-codes'
      preLoaderRoute: typeof ChargeCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extractions': {
      id: '/extractions'
      path: '/extractions'
      fullPath: '/extractions'
      preLoaderRoute: typeof ExtractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenancy/users': {
      id: '/tenancy/users'
      path: '/tenancy/users'
      fullPath: '/tenancy/users'
      preLoaderRoute: typeof TenancyUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChargeCodesRoute: ChargeCodesRoute,
  ExtractionsRoute: ExtractionsRoute,
  SessionRoute: SessionRoute,
  TenancyUsersRoute: TenancyUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
