from fastapi import APIRouter

from app.api import (
    bank_payments,
    booking_instructions,
    bookkeeping,
    cargo_claims,
    carrier_inquiries,
    cash_flows,
    channel_quotes,
    charge_codes,
    charge_templates,
    charges,
    cod_instructions,
    collective_invoices,
    commodity_codes,
    containers,
    cost_to_serve,
    credit_reviews,
    customer_rfqs,
    customer_sops,
    dangerous_goods,
    dock_appointments,
    document_checklist_rules,
    document_dispatch_rules,
    document_templates,
    edi_messages,
    entity_events,
    extractions,
    field_carry_forwards,
    fraud_flags,
    fuel_indexes,
    fx_differences,
    gdpr_requests,
    groupage_lines,
    groupage_tariffs,
    inbound_messages,
    incoterm_responsibilities,
    local_charges,
    locations,
    mail_drafts,
    money_costs,
    nbp_rates,
    networks,
    ocean_bills,
    operational_exceptions,
    operator_decisions,
    operator_notices,
    organization_calendars,
    organization_settings,
    outbox_events,
    pallet_balances,
    parties,
    party_lane_scorecards,
    party_scorecards,
    port_surcharges,
    ports,
    quotations,
    quote_invoice_settlements,
    rate_cards,
    rate_lines,
    resources,
    sales_invoices,
    session,
    shipment_documents,
    shipment_legs,
    shipment_packages,
    shipment_stakeholders,
    shipments,
    stops,
    table_views,
    tenancy,
    tender_bid_stances,
    tender_consortium_members,
    tender_data_rooms,
    tender_lanes,
    tender_lots,
    tender_matrix_cells,
    tender_playbooks,
    tender_prospects,
    tender_quotes,
    tender_rfp_intakes,
    tender_rounds,
    tender_win_losses,
    tenders,
    terminals,
    tracking_events,
    trips,
)
from app.domain.errors import PermissionDenied

api_router = APIRouter(prefix="/api/v1")
api_router.include_router(session.router)
api_router.include_router(tenancy.router)
api_router.include_router(table_views.router)
api_router.include_router(extractions.router)
api_router.include_router(charge_codes.router)
api_router.include_router(commodity_codes.router)
api_router.include_router(dangerous_goods.router)
api_router.include_router(document_checklist_rules.router)
api_router.include_router(document_dispatch_rules.router)
api_router.include_router(booking_instructions.router)
api_router.include_router(field_carry_forwards.router)
api_router.include_router(networks.router)
api_router.include_router(carrier_inquiries.router)
api_router.include_router(inbound_messages.router)
api_router.include_router(incoterm_responsibilities.router)
api_router.include_router(customer_rfqs.router)
api_router.include_router(operator_decisions.router)
api_router.include_router(operator_notices.router)
api_router.include_router(mail_drafts.router)
api_router.include_router(outbox_events.router)
api_router.include_router(entity_events.router)
api_router.include_router(nbp_rates.router)
api_router.include_router(charges.router)
api_router.include_router(rate_lines.router)
api_router.include_router(channel_quotes.router)
api_router.include_router(quotations.router)
api_router.include_router(shipments.router)
api_router.include_router(shipment_stakeholders.router)
api_router.include_router(stops.router)
api_router.include_router(resources.router)
api_router.include_router(trips.router)
api_router.include_router(containers.router)
api_router.include_router(tracking_events.router)
api_router.include_router(shipment_documents.router)
api_router.include_router(shipment_packages.router)
api_router.include_router(dock_appointments.router)
api_router.include_router(operational_exceptions.router)
api_router.include_router(cargo_claims.router)
api_router.include_router(cod_instructions.router)
api_router.include_router(ocean_bills.router)
api_router.include_router(pallet_balances.router)
api_router.include_router(document_templates.router)
api_router.include_router(rate_cards.router)
api_router.include_router(charge_templates.router)
api_router.include_router(fuel_indexes.router)
api_router.include_router(local_charges.router)
api_router.include_router(tender_quotes.router)
api_router.include_router(tender_data_rooms.router)
api_router.include_router(tender_lanes.router)
api_router.include_router(tender_lots.router)
api_router.include_router(tender_matrix_cells.router)
api_router.include_router(tender_playbooks.router)
api_router.include_router(tender_win_losses.router)
api_router.include_router(tender_bid_stances.router)
api_router.include_router(tender_consortium_members.router)
api_router.include_router(tender_prospects.router)
api_router.include_router(tender_rfp_intakes.router)
api_router.include_router(tender_rounds.router)
api_router.include_router(tenders.router)
api_router.include_router(fraud_flags.router)
api_router.include_router(edi_messages.router)
api_router.include_router(sales_invoices.router)
api_router.include_router(quote_invoice_settlements.router)
api_router.include_router(bank_payments.router)
api_router.include_router(money_costs.router)
api_router.include_router(fx_differences.router)
api_router.include_router(cash_flows.router)
api_router.include_router(cost_to_serve.router)
api_router.include_router(bookkeeping.router)
api_router.include_router(collective_invoices.router)
api_router.include_router(gdpr_requests.router)
api_router.include_router(groupage_lines.router)
api_router.include_router(groupage_tariffs.router)
api_router.include_router(shipment_legs.router)
api_router.include_router(organization_calendars.router)
api_router.include_router(organization_settings.router)
api_router.include_router(parties.router)
api_router.include_router(party_scorecards.router)
api_router.include_router(party_lane_scorecards.router)
api_router.include_router(credit_reviews.router)
api_router.include_router(customer_sops.router)
api_router.include_router(ports.router)
api_router.include_router(port_surcharges.router)
api_router.include_router(locations.router)
api_router.include_router(terminals.router)


@api_router.api_route(
    "/{undeclared_path:path}",
    methods=["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"],
    include_in_schema=False,
)
async def deny_undeclared_path(undeclared_path: str) -> None:
    _ = undeclared_path
    raise PermissionDenied("Brak deklaracji uprawnień")
