from fastapi import APIRouter

from app.api import (
    ab_sus_marks,
    abandoned_rto_marks,
    aeo_dossier_marks,
    air_ra3_marks,
    allocation_keys,
    allocation_levels,
    article50_marks,
    asns,
    automation_bias_marks,
    autonomy_levels,
    bank_payments,
    benefit_ledgers,
    bid_decision_marks,
    billing_marks,
    bin_pack_marks,
    bonded_marks,
    booking_instructions,
    bookkeeping,
    cabotage_marks,
    calibration_marks,
    campaign_marks,
    capa_marks,
    carbon_methods,
    cargo_claims,
    cargo_cover_marks,
    carrier_inquiries,
    cash_discounts,
    cash_flows,
    cfo_narrative_marks,
    channel_quotes,
    charge_codes,
    charge_templates,
    charges,
    chassis_marks,
    circle_sims,
    clause_notices,
    cmms_marks,
    cod_instructions,
    collaboration_marks,
    collective_invoices,
    combined_transport_marks,
    commodity_codes,
    company_marks,
    compliance_program_marks,
    consignments,
    containers,
    copy_ban_marks,
    cost_allocation_marks,
    cost_category_marks,
    cost_to_serve,
    counterfactual_runs,
    credit_reviews,
    crm_activities,
    crm_dedup_marks,
    crm_leads,
    crm_link_marks,
    crm_opportunities,
    crm_pipeline_marks,
    csrd_marks,
    customer_contracts,
    customer_po_marks,
    customer_rfqs,
    customer_sops,
    cutoff_marks,
    dangerous_goods,
    data_sources,
    delay_forecasts,
    demand_snapshot_marks,
    demo_gps_marks,
    demo_sim_marks,
    demo_wipe_marks,
    diversion_marks,
    dock_appointments,
    document_checklist_rules,
    document_dispatch_rules,
    document_templates,
    dual_ledger_marks,
    e_cmr_marks,
    e_delivery_marks,
    e_doreczenia_marks,
    eccn_marks,
    edi_map_marks,
    edi_messages,
    empty_depot_marks,
    entity_events,
    erp_connectors,
    erru_marks,
    eur1_atr_marks,
    exchange_connectors,
    executive_marks,
    extraction_prompt_marks,
    extractions,
    factoring_connectors,
    fair_share_marks,
    ferry_art9_marks,
    ferry_booking_marks,
    field_carry_forwards,
    field_confidence_marks,
    filing_scheme_marks,
    fleet_cost_marks,
    fraud_flags,
    free_time_clocks,
    freight_audit_marks,
    freight_term_marks,
    fuel_anomaly_marks,
    fuel_card_marks,
    fuel_indexes,
    funnel_marks,
    fx_differences,
    gdpr_requests,
    general_average_marks,
    groupage_dispatcher_marks,
    groupage_lines,
    groupage_tariffs,
    handover_notes,
    handover_sbar_marks,
    haulier_role_marks,
    high_value_marks,
    idp_connectors,
    impact_edge_marks,
    impact_node_marks,
    impact_scenarios,
    impersonate_guard_marks,
    inbound_messages,
    incoterm_responsibilities,
    ingest_gate_marks,
    integration_hub_marks,
    interval_scores,
    intervention_outcomes,
    inventory_collateral_marks,
    inventory_finance_marks,
    inventory_position_marks,
    iso_nis2_marks,
    jit_jis_marks,
    job_metric_marks,
    kpi_definition_marks,
    kreptd_licences,
    l3_gate_marks,
    label_parking_marks,
    lane_kms,
    lane_patterns,
    language_code_marks,
    lc_checklists,
    lcl_console_marks,
    legal_hold_marks,
    lez_marks,
    line_impact_layer_marks,
    line_impact_marks,
    load_order_marks,
    load_plan_marks,
    local_charges,
    locations,
    mail_accept_marks,
    mail_drafts,
    make_or_buy_marks,
    margin_floors,
    memory_edges,
    mobile_client_marks,
    model_feature_marks,
    money_costs,
    monitoring_schemes,
    mqc_marks,
    multi_manning_marks,
    nac_marks,
    named_place_marks,
    nbp_rates,
    ncts_drafts,
    networks,
    nvocc_marks,
    ocean_alliance_marks,
    ocean_bills,
    ocean_feeder_marks,
    offboarding_marks,
    oog_marks,
    oog_permit_marks,
    operational_exceptions,
    operator_decisions,
    operator_notices,
    ops_room_marks,
    organization_calendars,
    organization_settings,
    otif_marks,
    outbox_events,
    outcome_kinds,
    outcome_ledgers,
    pallet_balances,
    pallet_pool_marks,
    parties,
    partner_exchange_marks,
    party_documents,
    party_lane_scorecards,
    party_scorecards,
    payment_terms_marks,
    penalty_marks,
    peppol_marks,
    phyto_ata_marks,
    plan_snapshots,
    po_batch_marks,
    po_financing_marks,
    po_lines,
    po_plant_marks,
    po_sku_marks,
    port_surcharges,
    ports,
    position_events,
    posting_marks,
    prediction_ledgers,
    product_ticket_marks,
    profit_center_marks,
    purchase_orders,
    quality_descent_marks,
    quotations,
    quote_currency_marks,
    quote_invoice_settlements,
    quote_validity_marks,
    rag_sop_marks,
    rail_cim_marks,
    rail_uic_marks,
    rank_marks,
    rate_cards,
    rate_lines,
    reefer_marks,
    registry_poll_marks,
    regulatory_radar_marks,
    remediation_options,
    repair_playbooks,
    resources,
    rfid_marks,
    risk_register_marks,
    role_view_marks,
    route_plan_marks,
    routing_guide_enforcements,
    routing_guide_matches,
    routing_guides,
    sales_bind_marks,
    sales_invoices,
    sales_lanes,
    sanctions_marks,
    sap_connectors,
    schedule_exception_marks,
    session,
    shipment_clone_marks,
    shipment_documents,
    shipment_legs,
    shipment_packages,
    shipment_stakeholders,
    shipments,
    shipper_award_marks,
    shipper_bind_marks,
    shipper_like_marks,
    shipper_round_marks,
    shipper_tender_marks,
    sid_import_marks,
    silk_corridor_marks,
    sla_clauses,
    slot_guarantee_marks,
    spend_marks,
    spot_contract_marks,
    stops,
    style_cascade_marks,
    style_fidelity_marks,
    subcontract_edge_marks,
    suggestion_kinds,
    suggestion_ledgers,
    switch_bl_loi_marks,
    table_views,
    tacho_office_marks,
    tacho_plan_marks,
    task_templates,
    telematics_connectors,
    telematics_devices,
    tenancy,
    tenant_contract_keks,
    tender_award_reviews,
    tender_bid_stances,
    tender_carbon_marks,
    tender_consortium_members,
    tender_data_rooms,
    tender_decline_reasons,
    tender_lanes,
    tender_lots,
    tender_matrix_cells,
    tender_playbooks,
    tender_prospects,
    tender_quotes,
    tender_rfp_intakes,
    tender_rounds,
    tender_ted_notices,
    tender_win_losses,
    tenders,
    terminal_slot_connectors,
    terminals,
    terms_ai_marks,
    three_way_marks,
    time_to_fix_marks,
    tower_impacts,
    tracking_consents,
    tracking_events,
    trip_bill_marks,
    trips,
    twin_kinds,
    twin_marks,
    un_segregation_marks,
    vda_odette_marks,
    version_scores,
    version_windows,
    visibility_connectors,
    war_room_marks,
    weather_observations,
    webhook_outbox_marks,
    what_if_marks,
    wms_flow_marks,
    working_capital_marks,
    yard_marks,
)
from app.domain.errors import PermissionDenied

api_router = APIRouter(prefix="/api/v1")
api_router.include_router(session.router)
api_router.include_router(tenancy.router)
api_router.include_router(table_views.router)
api_router.include_router(extractions.router)
api_router.include_router(charge_codes.router)
api_router.include_router(commodity_codes.router)
api_router.include_router(dangerous_goods.router)
api_router.include_router(document_checklist_rules.router)
api_router.include_router(document_dispatch_rules.router)
api_router.include_router(booking_instructions.router)
api_router.include_router(field_carry_forwards.router)
api_router.include_router(networks.router)
api_router.include_router(carrier_inquiries.router)
api_router.include_router(inbound_messages.router)
api_router.include_router(incoterm_responsibilities.router)
api_router.include_router(customer_po_marks.router)
api_router.include_router(profit_center_marks.router)
api_router.include_router(haulier_role_marks.router)
api_router.include_router(high_value_marks.router)
api_router.include_router(payment_terms_marks.router)
api_router.include_router(customer_rfqs.router)
api_router.include_router(operator_decisions.router)
api_router.include_router(operator_notices.router)
api_router.include_router(mail_drafts.router)
api_router.include_router(mail_accept_marks.router)
api_router.include_router(role_view_marks.router)
api_router.include_router(route_plan_marks.router)
api_router.include_router(rag_sop_marks.router)
api_router.include_router(memory_edges.router)
api_router.include_router(executive_marks.router)
api_router.include_router(rail_cim_marks.router)
api_router.include_router(rail_uic_marks.router)
api_router.include_router(rank_marks.router)
api_router.include_router(task_templates.router)
api_router.include_router(outbox_events.router)
api_router.include_router(empty_depot_marks.router)
api_router.include_router(nvocc_marks.router)
api_router.include_router(multi_manning_marks.router)
api_router.include_router(named_place_marks.router)
api_router.include_router(posting_marks.router)
api_router.include_router(tacho_office_marks.router)
api_router.include_router(tacho_plan_marks.router)
api_router.include_router(label_parking_marks.router)
api_router.include_router(lez_marks.router)
api_router.include_router(line_impact_marks.router)
api_router.include_router(entity_events.router)
api_router.include_router(nbp_rates.router)
api_router.include_router(charges.router)
api_router.include_router(chassis_marks.router)
api_router.include_router(rate_lines.router)
api_router.include_router(channel_quotes.router)
api_router.include_router(quotations.router)
api_router.include_router(shipments.router)
api_router.include_router(shipper_like_marks.router)
api_router.include_router(shipper_round_marks.router)
api_router.include_router(shipper_tender_marks.router)
api_router.include_router(shipment_stakeholders.router)
api_router.include_router(stops.router)
api_router.include_router(subcontract_edge_marks.router)
api_router.include_router(switch_bl_loi_marks.router)
api_router.include_router(resources.router)
api_router.include_router(trips.router)
api_router.include_router(containers.router)
api_router.include_router(tracking_consents.router)
api_router.include_router(tracking_events.router)
api_router.include_router(shipment_documents.router)
api_router.include_router(shipment_packages.router)
api_router.include_router(dock_appointments.router)
api_router.include_router(operational_exceptions.router)
api_router.include_router(cargo_claims.router)
api_router.include_router(cargo_cover_marks.router)
api_router.include_router(cod_instructions.router)
api_router.include_router(ocean_alliance_marks.router)
api_router.include_router(ocean_bills.router)
api_router.include_router(ocean_feeder_marks.router)
api_router.include_router(oog_marks.router)
api_router.include_router(oog_permit_marks.router)
api_router.include_router(consignments.router)
api_router.include_router(pallet_balances.router)
api_router.include_router(document_templates.router)
api_router.include_router(dual_ledger_marks.router)
api_router.include_router(rate_cards.router)
api_router.include_router(charge_templates.router)
api_router.include_router(fuel_indexes.router)
api_router.include_router(kreptd_licences.router)
api_router.include_router(lane_patterns.router)
api_router.include_router(lane_kms.router)
api_router.include_router(lcl_console_marks.router)
api_router.include_router(nac_marks.router)
api_router.include_router(silk_corridor_marks.router)
api_router.include_router(lc_checklists.router)
api_router.include_router(language_code_marks.router)
api_router.include_router(ncts_drafts.router)
api_router.include_router(circle_sims.router)
api_router.include_router(circle_sims.pair_router)
api_router.include_router(clause_notices.router)
api_router.include_router(calibration_marks.router)
api_router.include_router(campaign_marks.router)
api_router.include_router(repair_playbooks.router)
api_router.include_router(spend_marks.router)
api_router.include_router(penalty_marks.router)
api_router.include_router(intervention_outcomes.router)
api_router.include_router(load_order_marks.router)
api_router.include_router(load_plan_marks.router)
api_router.include_router(cmms_marks.router)
api_router.include_router(legal_hold_marks.router)
api_router.include_router(company_marks.router)
api_router.include_router(bonded_marks.router)
api_router.include_router(filing_scheme_marks.router)
api_router.include_router(local_charges.router)
api_router.include_router(tender_quotes.router)
api_router.include_router(tender_data_rooms.router)
api_router.include_router(tender_decline_reasons.router)
api_router.include_router(tender_lanes.router)
api_router.include_router(tender_lots.router)
api_router.include_router(tender_matrix_cells.router)
api_router.include_router(tender_playbooks.router)
api_router.include_router(tender_win_losses.router)
api_router.include_router(tender_award_reviews.router)
api_router.include_router(tender_bid_stances.router)
api_router.include_router(tender_carbon_marks.router)
api_router.include_router(tender_consortium_members.router)
api_router.include_router(tender_prospects.router)
api_router.include_router(tender_rfp_intakes.router)
api_router.include_router(tender_rounds.router)
api_router.include_router(tender_ted_notices.router)
api_router.include_router(tenders.router)
api_router.include_router(fraud_flags.router)
api_router.include_router(terms_ai_marks.router)
api_router.include_router(three_way_marks.router)
api_router.include_router(funnel_marks.router)
api_router.include_router(edi_map_marks.router)
api_router.include_router(edi_messages.router)
api_router.include_router(sales_invoices.router)
api_router.include_router(sales_lanes.router)
api_router.include_router(schedule_exception_marks.router)
api_router.include_router(sanctions_marks.router)
api_router.include_router(quote_invoice_settlements.router)
api_router.include_router(bank_payments.router)
api_router.include_router(money_costs.router)
api_router.include_router(monitoring_schemes.router)
api_router.include_router(fx_differences.router)
api_router.include_router(carbon_methods.router)
api_router.include_router(plan_snapshots.router)
api_router.include_router(prediction_ledgers.router)
api_router.include_router(weather_observations.router)
api_router.include_router(free_time_clocks.router)
api_router.include_router(telematics_connectors.router)
api_router.include_router(telematics_devices.router)
api_router.include_router(erp_connectors.router)
api_router.include_router(factoring_connectors.router)
api_router.include_router(po_financing_marks.router)
api_router.include_router(wms_flow_marks.router)
api_router.include_router(rfid_marks.router)
api_router.include_router(inventory_finance_marks.router)
api_router.include_router(inventory_collateral_marks.router)
api_router.include_router(ops_room_marks.router)
api_router.include_router(line_impact_layer_marks.router)
api_router.include_router(product_ticket_marks.router)
api_router.include_router(risk_register_marks.router)
api_router.include_router(automation_bias_marks.router)
api_router.include_router(l3_gate_marks.router)
api_router.include_router(style_cascade_marks.router)
api_router.include_router(style_fidelity_marks.router)
api_router.include_router(quality_descent_marks.router)
api_router.include_router(field_confidence_marks.router)
api_router.include_router(compliance_program_marks.router)
api_router.include_router(customer_contracts.router)
api_router.include_router(exchange_connectors.router)
api_router.include_router(idp_connectors.router)
api_router.include_router(tenant_contract_keks.router)
api_router.include_router(visibility_connectors.router)
api_router.include_router(purchase_orders.router)
api_router.include_router(po_lines.router)
api_router.include_router(po_plant_marks.router)
api_router.include_router(po_sku_marks.router)
api_router.include_router(po_batch_marks.router)
api_router.include_router(abandoned_rto_marks.router)
api_router.include_router(ab_sus_marks.router)
api_router.include_router(air_ra3_marks.router)
api_router.include_router(aeo_dossier_marks.router)
api_router.include_router(yard_marks.router)
api_router.include_router(billing_marks.router)
api_router.include_router(reefer_marks.router)
api_router.include_router(registry_poll_marks.router)
api_router.include_router(working_capital_marks.router)
api_router.include_router(make_or_buy_marks.router)
api_router.include_router(cost_allocation_marks.router)
api_router.include_router(cost_category_marks.router)
api_router.include_router(impact_edge_marks.router)
api_router.include_router(impact_node_marks.router)
api_router.include_router(article50_marks.router)
api_router.include_router(data_sources.router)
api_router.include_router(ingest_gate_marks.router)
api_router.include_router(model_feature_marks.router)
api_router.include_router(cfo_narrative_marks.router)
api_router.include_router(kpi_definition_marks.router)
api_router.include_router(margin_floors.router)
api_router.include_router(shipment_clone_marks.router)
api_router.include_router(handover_sbar_marks.router)
api_router.include_router(handover_notes.router)
api_router.include_router(trip_bill_marks.router)
api_router.include_router(asns.router)
api_router.include_router(otif_marks.router)
api_router.include_router(routing_guide_enforcements.router)
api_router.include_router(routing_guide_matches.router)
api_router.include_router(routing_guides.router)
api_router.include_router(sap_connectors.router)
api_router.include_router(capa_marks.router)
api_router.include_router(sla_clauses.router)
api_router.include_router(slot_guarantee_marks.router)
api_router.include_router(delay_forecasts.router)
api_router.include_router(demand_snapshot_marks.router)
api_router.include_router(diversion_marks.router)
api_router.include_router(spot_contract_marks.router)
api_router.include_router(bid_decision_marks.router)
api_router.include_router(quote_currency_marks.router)
api_router.include_router(quote_validity_marks.router)
api_router.include_router(suggestion_ledgers.router)
api_router.include_router(suggestion_kinds.router)
api_router.include_router(autonomy_levels.router)
api_router.include_router(allocation_keys.router)
api_router.include_router(allocation_levels.router)
api_router.include_router(outcome_kinds.router)
api_router.include_router(outcome_ledgers.router)
api_router.include_router(interval_scores.router)
api_router.include_router(version_scores.router)
api_router.include_router(version_windows.router)
api_router.include_router(demo_gps_marks.router)
api_router.include_router(demo_sim_marks.router)
api_router.include_router(demo_wipe_marks.router)
api_router.include_router(remediation_options.router)
api_router.include_router(impact_scenarios.router)
api_router.include_router(impersonate_guard_marks.router)
api_router.include_router(freight_audit_marks.router)
api_router.include_router(freight_term_marks.router)
api_router.include_router(collaboration_marks.router)
api_router.include_router(terminal_slot_connectors.router)
api_router.include_router(tower_impacts.router)
api_router.include_router(twin_kinds.router)
api_router.include_router(twin_marks.router)
api_router.include_router(un_segregation_marks.router)
api_router.include_router(war_room_marks.router)
api_router.include_router(cash_discounts.router)
api_router.include_router(cash_flows.router)
api_router.include_router(copy_ban_marks.router)
api_router.include_router(erru_marks.router)
api_router.include_router(mobile_client_marks.router)
api_router.include_router(cost_to_serve.router)
api_router.include_router(counterfactual_runs.router)
api_router.include_router(counterfactual_runs.replay_router)
api_router.include_router(benefit_ledgers.router)
api_router.include_router(bookkeeping.router)
api_router.include_router(collective_invoices.router)
api_router.include_router(gdpr_requests.router)
api_router.include_router(general_average_marks.router)
api_router.include_router(groupage_dispatcher_marks.router)
api_router.include_router(groupage_lines.router)
api_router.include_router(groupage_tariffs.router)
api_router.include_router(shipment_legs.router)
api_router.include_router(organization_calendars.router)
api_router.include_router(organization_settings.router)
api_router.include_router(parties.router)
api_router.include_router(party_documents.router)
api_router.include_router(party_scorecards.router)
api_router.include_router(party_lane_scorecards.router)
api_router.include_router(credit_reviews.router)
api_router.include_router(csrd_marks.router)
api_router.include_router(crm_leads.router)
api_router.include_router(crm_opportunities.router)
api_router.include_router(crm_activities.router)
api_router.include_router(crm_pipeline_marks.router)
api_router.include_router(crm_dedup_marks.router)
api_router.include_router(crm_link_marks.router)
api_router.include_router(sales_bind_marks.router)
api_router.include_router(shipper_bind_marks.router)
api_router.include_router(shipper_award_marks.router)
api_router.include_router(extraction_prompt_marks.router)
api_router.include_router(customer_sops.router)
api_router.include_router(cutoff_marks.router)
api_router.include_router(ports.router)
api_router.include_router(position_events.router)
api_router.include_router(port_surcharges.router)
api_router.include_router(locations.router)
api_router.include_router(terminals.router)
api_router.include_router(time_to_fix_marks.router)
api_router.include_router(what_if_marks.router)
api_router.include_router(cabotage_marks.router)
api_router.include_router(combined_transport_marks.router)
api_router.include_router(ferry_art9_marks.router)
api_router.include_router(ferry_booking_marks.router)
api_router.include_router(fuel_anomaly_marks.router)
api_router.include_router(fuel_card_marks.router)
api_router.include_router(fleet_cost_marks.router)
api_router.include_router(bin_pack_marks.router)
api_router.include_router(pallet_pool_marks.router)
api_router.include_router(e_cmr_marks.router)
api_router.include_router(e_delivery_marks.router)
api_router.include_router(e_doreczenia_marks.router)
api_router.include_router(peppol_marks.router)
api_router.include_router(phyto_ata_marks.router)
api_router.include_router(sid_import_marks.router)
api_router.include_router(integration_hub_marks.router)
api_router.include_router(webhook_outbox_marks.router)
api_router.include_router(partner_exchange_marks.router)
api_router.include_router(regulatory_radar_marks.router)
api_router.include_router(iso_nis2_marks.router)
api_router.include_router(offboarding_marks.router)
api_router.include_router(jit_jis_marks.router)
api_router.include_router(job_metric_marks.router)
api_router.include_router(vda_odette_marks.router)
api_router.include_router(inventory_position_marks.router)
api_router.include_router(fair_share_marks.router)
api_router.include_router(mqc_marks.router)
api_router.include_router(eccn_marks.router)
api_router.include_router(eur1_atr_marks.router)


@api_router.api_route(
    "/{undeclared_path:path}",
    methods=["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"],
    include_in_schema=False,
)
async def deny_undeclared_path(undeclared_path: str) -> None:
    _ = undeclared_path
    raise PermissionDenied("Brak deklaracji uprawnień")
