export const BUSINESS_LISTS = {
  users: { route: "/tenancy/users", tableKey: "tenancy.users" },
  chargeCodes: { route: "/charge-codes", tableKey: "charge_codes" },
  commodityCodes: { route: "/commodity-codes", tableKey: "commodity_codes" },
  dangerousGoods: { route: "/dangerous-goods", tableKey: "dangerous_goods" },
  networks: { route: "/networks", tableKey: "networks" },
  nbpRates: { route: "/nbp-rates", tableKey: "nbp_rates" },
  rateLines: { route: "/rate-lines", tableKey: "rate_lines" },
  charges: { route: "/charges", tableKey: "charges" },
  channelQuotes: { route: "/channel-quotes", tableKey: "channel_quotes" },
  quotations: { route: "/quotations", tableKey: "quotations" },
  organizationSettings: { route: "/organization-settings", tableKey: "organization_settings" },
  extractions: { route: "/extractions", tableKey: "extraction.queue" },
  financeBoard: { route: "/finance", tableKey: "finance_board" },
  salesInvoice: { route: "/invoices", tableKey: "sales_invoice" },
  quoteInvoiceSettlement: { route: "/quote-invoices", tableKey: "quote_invoice_settlement" },
  bankPayment: { route: "/payments", tableKey: "bank_payment" },
  moneyCost: { route: "/money-cost", tableKey: "money_cost" },
  fxDifference: { route: "/fx-differences", tableKey: "fx_difference" },
  cashFlow: { route: "/cashflows", tableKey: "cash_flow" },
  costToServe: { route: "/cost-to-serve", tableKey: "cost_to_serve" },
  bookkeeping: { route: "/bookkeeping", tableKey: "bookkeeping" },
  roadTransport: { route: "/road", tableKey: "road_transport" },
  intermodalRail: { route: "/rail", tableKey: "intermodal_rail" },
  chinaRail: { route: "/china-rail", tableKey: "china_rail" },
  oceanLcl: { route: "/lcl", tableKey: "ocean_lcl" },
  sanctions: { route: "/sanctions", tableKey: "sanctions" },
  gdpr: { route: "/gdpr", tableKey: "gdpr" },
  aiCopilot: { route: "/ai", tableKey: "ai_copilot" },
  observability: { route: "/health", tableKey: "observability" },
  extractionQuality: { route: "/quality", tableKey: "extraction_quality" },
  tenantRollout: { route: "/rollout", tableKey: "tenant_rollout" },
  mailIntegration: { route: "/mail", tableKey: "mail_integration" },
  operatorNotice: { route: "/notifications", tableKey: "operator_notice" },
  shipment: { route: "/shipments", tableKey: "shipment" },
  tracking: { route: "/tracking", tableKey: "tracking" },
  operationalException: { route: "/exceptions", tableKey: "operational_exception" },
  cargoClaim: { route: "/claims", tableKey: "cargo_claim" },
  watchtower: { route: "/watchtower", tableKey: "watchtower" },
  shipmentDocument: { route: "/shipment-documents", tableKey: "shipment_document" },
  ediMessage: { route: "/edi", tableKey: "edi_message" },
  ports: { route: "/ports", tableKey: "ports" },
  portSurcharges: { route: "/port-surcharges", tableKey: "port_surcharges" },
  locations: { route: "/locations", tableKey: "locations" },
  terminals: { route: "/terminals", tableKey: "terminals" },
  parties: { route: "/parties", tableKey: "parties" },
  partyScorecards: { route: "/party-scorecards", tableKey: "party_scorecards" },
  customerSops: { route: "/customer-sops", tableKey: "customer_sops" },
  creditReviews: { route: "/credit-reviews", tableKey: "credit_reviews" },
  operatorDecisions: { route: "/decisions", tableKey: "operator_decisions" },
  outboxEvents: { route: "/outbox", tableKey: "outbox_events" },
} as const

export const REQUIRED_BUSINESS_LIST_ROUTES = [
  "/tenancy/users",
  "/charge-codes",
  "/commodity-codes",
  "/dangerous-goods",
  "/networks",
  "/nbp-rates",
  "/rate-lines",
  "/charges",
  "/channel-quotes",
  "/quotations",
  "/organization-settings",
  "/extractions",
  "/finance",
  "/invoices",
  "/quote-invoices",
  "/payments",
  "/money-cost",
  "/fx-differences",
  "/cashflows",
  "/cost-to-serve",
  "/bookkeeping",
  "/road",
  "/rail",
  "/china-rail",
  "/lcl",
  "/sanctions",
  "/gdpr",
  "/ai",
  "/health",
  "/quality",
  "/rollout",
  "/mail",
  "/notifications",
  "/shipments",
  "/tracking",
  "/exceptions",
  "/claims",
  "/watchtower",
  "/shipment-documents",
  "/edi",
  "/ports",
  "/port-surcharges",
  "/locations",
  "/terminals",
  "/parties",
  "/party-scorecards",
  "/customer-sops",
  "/credit-reviews",
  "/decisions",
  "/outbox",
] as const

export function businessListRoutes(): string[] {
  return Object.values(BUSINESS_LISTS).map((list) => list.route)
}

export function businessListTableKeys(): string[] {
  return Object.values(BUSINESS_LISTS).map((list) => list.tableKey)
}
