export const BUSINESS_LISTS = {
  users: { route: "/tenancy/users", tableKey: "tenancy.users" },
  chargeCodes: { route: "/charge-codes", tableKey: "charge_codes" },
  commodityCodes: { route: "/commodity-codes", tableKey: "commodity_codes" },
  dangerousGoods: { route: "/dangerous-goods", tableKey: "dangerous_goods" },
  networks: { route: "/networks", tableKey: "networks" },
  nbpRates: { route: "/nbp-rates", tableKey: "nbp_rates" },
  rateLines: { route: "/rate-lines", tableKey: "rate_lines" },
  charges: { route: "/charges", tableKey: "charges" },
  channelQuotes: { route: "/channel-quotes", tableKey: "channel_quotes" },
  quotations: { route: "/quotations", tableKey: "quotations" },
  organizationSettings: { route: "/organization-settings", tableKey: "organization_settings" },
  extractions: { route: "/extractions", tableKey: "extraction.queue" },
  financeBoard: { route: "/finance", tableKey: "finance_board" },
  salesInvoice: { route: "/invoices", tableKey: "sales_invoice" },
  quoteInvoiceSettlement: { route: "/quote-invoices", tableKey: "quote_invoice_settlement" },
  bankPayment: { route: "/payments", tableKey: "bank_payment" },
  moneyCost: { route: "/money-cost", tableKey: "money_cost" },
  fxDifference: { route: "/fx-differences", tableKey: "fx_difference" },
  cashFlow: { route: "/cashflows", tableKey: "cash_flow" },
  costToServe: { route: "/cost-to-serve", tableKey: "cost_to_serve" },
  bookkeeping: { route: "/bookkeeping", tableKey: "bookkeeping" },
  roadTransport: { route: "/road", tableKey: "road_transport" },
  intermodalRail: { route: "/rail", tableKey: "intermodal_rail" },
  chinaRail: { route: "/china-rail", tableKey: "china_rail" },
  oceanLcl: { route: "/lcl", tableKey: "ocean_lcl" },
  oceanBill: { route: "/ocean-bills", tableKey: "ocean_bill" },
  consignment: { route: "/consignments", tableKey: "consignment" },
  palletBalance: { route: "/pallet-balances", tableKey: "pallet_balance" },
  documentTemplate: { route: "/document-templates", tableKey: "document_template" },
  rateCard: { route: "/rate-cards", tableKey: "rate_card" },
  chargeTemplate: { route: "/charge-templates", tableKey: "charge_template" },
  fuelIndex: { route: "/fuel-indexes", tableKey: "fuel_index" },
  localCharge: { route: "/local-charges", tableKey: "local_charge" },
  tenderDataRoom: { route: "/tender-data-rooms", tableKey: "tender_data_room" },
  tenderMatrixCell: { route: "/tender-matrix-cells", tableKey: "tender_matrix_cell" },
  tenderPlaybook: { route: "/tender-playbooks", tableKey: "tender_playbook" },
  tenderWinLoss: { route: "/tender-win-losses", tableKey: "tender_win_loss" },
  tenderConsortiumMember: {
    route: "/tender-consortium-members",
    tableKey: "tender_consortium_member",
  },
  tenderRfpIntake: { route: "/tender-rfp-intakes", tableKey: "tender_rfp_intake" },
  tenderProspect: { route: "/tender-prospects", tableKey: "tender_prospect" },
  tenderBidStance: { route: "/tender-bid-stances", tableKey: "tender_bid_stance" },
  tenderCarbonMark: { route: "/tender-carbon-marks", tableKey: "tender_carbon_mark" },
  lanePattern: { route: "/lane-patterns", tableKey: "lane_pattern" },
  kreptdLicence: { route: "/kreptd-licences", tableKey: "kreptd_licence" },
  monitoringScheme: { route: "/monitoring-schemes", tableKey: "monitoring_scheme" },
  partyDocument: { route: "/party-documents", tableKey: "party_document" },
  cashDiscount: { route: "/cash-discounts", tableKey: "cash_discount" },
  carbonMethod: { route: "/carbon-methods", tableKey: "carbon_method" },
  predictionLedger: { route: "/prediction-ledgers", tableKey: "prediction_ledger" },
  planSnapshot: { route: "/plan-snapshots", tableKey: "plan_snapshot" },
  circleSim: { route: "/circle-sims", tableKey: "circle_sim" },
  laneKm: { route: "/lane-kms", tableKey: "lane_km" },
  lcChecklist: { route: "/lc-checklists", tableKey: "lc_checklist" },
  nctsDraft: { route: "/ncts-drafts", tableKey: "ncts_draft" },
  oogMark: { route: "/oog-marks", tableKey: "oog_mark" },
  loadPlanMark: { route: "/load-plan-marks", tableKey: "load_plan_mark" },
  cmmsMark: { route: "/cmms-marks", tableKey: "cmms_mark" },
  erpConnector: { route: "/erp-connectors", tableKey: "erp_connector" },
  idpConnector: { route: "/idp-connectors", tableKey: "idp_connector" },
  customerContract: { route: "/customer-contracts", tableKey: "customer_contract" },
  tenantContractKek: { route: "/tenant-contract-keks", tableKey: "tenant_contract_kek" },
  visibilityConnector: { route: "/visibility-connectors", tableKey: "visibility_connector" },
  purchaseOrder: { route: "/purchase-orders", tableKey: "purchase_order" },
  poLine: { route: "/po-lines", tableKey: "po_line" },
  asn: { route: "/asns", tableKey: "asn" },
  routingGuide: { route: "/routing-guides", tableKey: "routing_guide" },
  routingGuideEnforcement: {
    route: "/routing-guide-enforcements",
    tableKey: "routing_guide_enforcement",
  },
  routingGuideMatch: {
    route: "/routing-guide-matches",
    tableKey: "routing_guide_match",
  },
  otifMark: { route: "/otif-marks", tableKey: "otif_mark" },
  sapConnector: { route: "/sap-connectors", tableKey: "sap_connector" },
  capaMark: { route: "/capa-marks", tableKey: "capa_mark" },
  slaClause: { route: "/sla-clauses", tableKey: "sla_clause" },
  delayForecast: { route: "/delay-forecasts", tableKey: "delay_forecast" },
  remediationOption: {
    route: "/remediation-options",
    tableKey: "remediation_option",
  },
  impactScenario: { route: "/impact-scenarios", tableKey: "impact_scenario" },
  clauseNotice: { route: "/clause-notices", tableKey: "clause_notice" },
  calibrationMark: { route: "/calibration-marks", tableKey: "calibration_mark" },
  repairPlaybook: { route: "/repair-playbooks", tableKey: "repair_playbook" },
  spendMark: { route: "/spend-marks", tableKey: "spend_mark" },
  penaltyMark: { route: "/penalty-marks", tableKey: "penalty_mark" },
  interventionOutcome: {
    route: "/intervention-outcomes",
    tableKey: "intervention_outcome",
  },
  freightAuditMark: { route: "/freight-audit-marks", tableKey: "freight_audit_mark" },
  collaborationMark: { route: "/collaboration-marks", tableKey: "collaboration_mark" },
  crmLead: { route: "/crm-leads", tableKey: "crm_lead" },
  exchangeConnector: { route: "/exchange-connectors", tableKey: "exchange_connector" },
  terminalSlotConnector: { route: "/terminal-slot-connectors", tableKey: "terminal_slot_connector" },
  weatherObservation: { route: "/weather-observations", tableKey: "weather_observation" },
  freeTimeClock: { route: "/free-time-clocks", tableKey: "free_time_clock" },
  telematicsConnector: { route: "/telematics-connectors", tableKey: "telematics_connector" },
  towerImpact: { route: "/tower-impacts", tableKey: "tower_impact" },
  twinMark: { route: "/twin-marks", tableKey: "twin_mark" },
  warRoomMark: { route: "/war-room-marks", tableKey: "war_room_mark" },
  memoryEdge: { route: "/memory-edges", tableKey: "memory_edge" },
  executiveMark: { route: "/executive-marks", tableKey: "executive_mark" },
  rankMark: { route: "/rank-marks", tableKey: "rank_mark" },
  taskTemplate: { route: "/task-templates", tableKey: "task_template" },
  tenderAwardReview: { route: "/tender-award-reviews", tableKey: "tender_award_review" },
  tenderTedNotice: { route: "/tender-ted-notices", tableKey: "tender_ted_notice" },
  tenderLane: { route: "/tender-lanes", tableKey: "tender_lane" },
  tenderLot: { route: "/tender-lots", tableKey: "tender_lot" },
  tenderRound: { route: "/tender-rounds", tableKey: "tender_round" },
  tenderQuote: { route: "/tender-quotes", tableKey: "tender_quote" },
  tender: { route: "/tenders", tableKey: "tender" },
  airFreight: { route: "/air", tableKey: "air_freight" },
  groupageLines: { route: "/groupage", tableKey: "groupage_line" },
  groupageTariff: { route: "/groupage-tariffs", tableKey: "groupage_tariff" },
  shipmentPackage: { route: "/shipment-packages", tableKey: "shipment_package" },
  dockAppointment: { route: "/dock-appointments", tableKey: "dock_appointment" },
  codInstruction: { route: "/cod", tableKey: "cod_instruction" },
  sanctions: { route: "/sanctions", tableKey: "sanctions" },
  fraudFlag: { route: "/fraud", tableKey: "fraud_flag" },
  gdpr: { route: "/gdpr", tableKey: "gdpr" },
  aiCopilot: { route: "/ai", tableKey: "ai_copilot" },
  observability: { route: "/health", tableKey: "observability" },
  extractionQuality: { route: "/quality", tableKey: "extraction_quality" },
  tenantRollout: { route: "/rollout", tableKey: "tenant_rollout" },
  mailIntegration: { route: "/mail", tableKey: "mail_integration" },
  operatorNotice: { route: "/notifications", tableKey: "operator_notice" },
  shipment: { route: "/shipments", tableKey: "shipment" },
  fleet: { route: "/fleet", tableKey: "resource" },
  planning: { route: "/planning", tableKey: "planning" },
  tracking: { route: "/tracking", tableKey: "tracking" },
  operationalException: { route: "/exceptions", tableKey: "operational_exception" },
  cargoClaim: { route: "/claims", tableKey: "cargo_claim" },
  watchtower: { route: "/watchtower", tableKey: "watchtower" },
  shipmentDocument: { route: "/shipment-documents", tableKey: "shipment_document" },
  ediMessage: { route: "/edi", tableKey: "edi_message" },
  ports: { route: "/ports", tableKey: "ports" },
  portSurcharges: { route: "/port-surcharges", tableKey: "port_surcharges" },
  locations: { route: "/locations", tableKey: "locations" },
  terminals: { route: "/terminals", tableKey: "terminals" },
  parties: { route: "/parties", tableKey: "parties" },
  partyScorecards: { route: "/party-scorecards", tableKey: "party_scorecards" },
  customerSops: { route: "/customer-sops", tableKey: "customer_sops" },
  creditReviews: { route: "/credit-reviews", tableKey: "credit_reviews" },
  operatorDecisions: { route: "/decisions", tableKey: "operator_decisions" },
  outboxEvents: { route: "/outbox", tableKey: "outbox_events" },
  entityEvents: { route: "/entity-events", tableKey: "entity_events" },
} as const

export const REQUIRED_BUSINESS_LIST_ROUTES = [
  "/tenancy/users",
  "/charge-codes",
  "/commodity-codes",
  "/dangerous-goods",
  "/networks",
  "/nbp-rates",
  "/rate-lines",
  "/charges",
  "/channel-quotes",
  "/quotations",
  "/organization-settings",
  "/extractions",
  "/finance",
  "/invoices",
  "/quote-invoices",
  "/payments",
  "/money-cost",
  "/fx-differences",
  "/cashflows",
  "/cost-to-serve",
  "/bookkeeping",
  "/road",
  "/rail",
  "/china-rail",
  "/lcl",
  "/ocean-bills",
  "/consignments",
  "/pallet-balances",
  "/document-templates",
  "/rate-cards",
  "/charge-templates",
  "/fuel-indexes",
  "/local-charges",
  "/tender-data-rooms",
  "/tender-matrix-cells",
  "/tender-playbooks",
  "/tender-win-losses",
  "/tender-consortium-members",
  "/tender-rfp-intakes",
  "/tender-prospects",
  "/tender-bid-stances",
  "/tender-carbon-marks",
  "/lane-patterns",
  "/kreptd-licences",
  "/monitoring-schemes",
  "/party-documents",
  "/cash-discounts",
  "/carbon-methods",
  "/prediction-ledgers",
  "/plan-snapshots",
  "/circle-sims",
  "/lane-kms",
  "/lc-checklists",
  "/ncts-drafts",
  "/oog-marks",
  "/load-plan-marks",
  "/cmms-marks",
  "/erp-connectors",
  "/idp-connectors",
  "/customer-contracts",
  "/tenant-contract-keks",
  "/visibility-connectors",
  "/purchase-orders",
  "/po-lines",
  "/asns",
  "/routing-guide-enforcements",
  "/routing-guide-matches",
  "/routing-guides",
  "/otif-marks",
  "/sap-connectors",
  "/capa-marks",
  "/sla-clauses",
  "/delay-forecasts",
  "/remediation-options",
  "/impact-scenarios",
  "/clause-notices",
  "/calibration-marks",
  "/repair-playbooks",
  "/spend-marks",
  "/penalty-marks",
  "/intervention-outcomes",
  "/freight-audit-marks",
  "/collaboration-marks",
  "/crm-leads",
  "/exchange-connectors",
  "/terminal-slot-connectors",
  "/weather-observations",
  "/free-time-clocks",
  "/telematics-connectors",
  "/tower-impacts",
  "/twin-marks",
  "/war-room-marks",
  "/memory-edges",
  "/executive-marks",
  "/rank-marks",
  "/task-templates",
  "/tender-award-reviews",
  "/tender-ted-notices",
  "/tender-lanes",
  "/tender-lots",
  "/tender-rounds",
  "/tender-quotes",
  "/tenders",
  "/air",
  "/groupage",
  "/groupage-tariffs",
  "/shipment-packages",
  "/dock-appointments",
  "/cod",
  "/sanctions",
  "/fraud",
  "/gdpr",
  "/ai",
  "/health",
  "/quality",
  "/rollout",
  "/mail",
  "/notifications",
  "/shipments",
  "/fleet",
  "/planning",
  "/tracking",
  "/exceptions",
  "/claims",
  "/watchtower",
  "/shipment-documents",
  "/edi",
  "/ports",
  "/port-surcharges",
  "/locations",
  "/terminals",
  "/parties",
  "/party-scorecards",
  "/customer-sops",
  "/credit-reviews",
  "/decisions",
  "/outbox",
  "/entity-events",
] as const

export function businessListRoutes(): string[] {
  return Object.values(BUSINESS_LISTS).map((list) => list.route)
}

export function businessListTableKeys(): string[] {
  return Object.values(BUSINESS_LISTS).map((list) => list.tableKey)
}
