export const BUSINESS_LISTS = {
  users: { route: "/tenancy/users", tableKey: "tenancy.users" },
  chargeCodes: { route: "/charge-codes", tableKey: "charge_codes" },
  commodityCodes: { route: "/commodity-codes", tableKey: "commodity_codes" },
  dangerousGoods: { route: "/dangerous-goods", tableKey: "dangerous_goods" },
  networks: { route: "/networks", tableKey: "networks" },
  nbpRates: { route: "/nbp-rates", tableKey: "nbp_rates" },
  rateLines: { route: "/rate-lines", tableKey: "rate_lines" },
  charges: { route: "/charges", tableKey: "charges" },
  channelQuotes: { route: "/channel-quotes", tableKey: "channel_quotes" },
  quotations: { route: "/quotations", tableKey: "quotations" },
  organizationSettings: { route: "/organization-settings", tableKey: "organization_settings" },
  extractions: { route: "/extractions", tableKey: "extraction.queue" },
  financeBoard: { route: "/finance", tableKey: "finance_board" },
  salesInvoice: { route: "/invoices", tableKey: "sales_invoice" },
  quoteInvoiceSettlement: { route: "/quote-invoices", tableKey: "quote_invoice_settlement" },
  bankPayment: { route: "/payments", tableKey: "bank_payment" },
  moneyCost: { route: "/money-cost", tableKey: "money_cost" },
  fxDifference: { route: "/fx-differences", tableKey: "fx_difference" },
  cashFlow: { route: "/cashflows", tableKey: "cash_flow" },
  costToServe: { route: "/cost-to-serve", tableKey: "cost_to_serve" },
  bookkeeping: { route: "/bookkeeping", tableKey: "bookkeeping" },
  roadTransport: { route: "/road", tableKey: "road_transport" },
  intermodalRail: { route: "/rail", tableKey: "intermodal_rail" },
  chinaRail: { route: "/china-rail", tableKey: "china_rail" },
  oceanLcl: { route: "/lcl", tableKey: "ocean_lcl" },
  oceanBill: { route: "/ocean-bills", tableKey: "ocean_bill" },
  palletBalance: { route: "/pallet-balances", tableKey: "pallet_balance" },
  documentTemplate: { route: "/document-templates", tableKey: "document_template" },
  rateCard: { route: "/rate-cards", tableKey: "rate_card" },
  chargeTemplate: { route: "/charge-templates", tableKey: "charge_template" },
  fuelIndex: { route: "/fuel-indexes", tableKey: "fuel_index" },
  localCharge: { route: "/local-charges", tableKey: "local_charge" },
  tenderDataRoom: { route: "/tender-data-rooms", tableKey: "tender_data_room" },
  tenderMatrixCell: { route: "/tender-matrix-cells", tableKey: "tender_matrix_cell" },
  tenderPlaybook: { route: "/tender-playbooks", tableKey: "tender_playbook" },
  tenderWinLoss: { route: "/tender-win-losses", tableKey: "tender_win_loss" },
  tenderConsortiumMember: {
    route: "/tender-consortium-members",
    tableKey: "tender_consortium_member",
  },
  tenderRfpIntake: { route: "/tender-rfp-intakes", tableKey: "tender_rfp_intake" },
  tenderProspect: { route: "/tender-prospects", tableKey: "tender_prospect" },
  tenderBidStance: { route: "/tender-bid-stances", tableKey: "tender_bid_stance" },
  tenderCarbonMark: { route: "/tender-carbon-marks", tableKey: "tender_carbon_mark" },
  lanePattern: { route: "/lane-patterns", tableKey: "lane_pattern" },
  kreptdLicence: { route: "/kreptd-licences", tableKey: "kreptd_licence" },
  monitoringScheme: { route: "/monitoring-schemes", tableKey: "monitoring_scheme" },
  tenderAwardReview: { route: "/tender-award-reviews", tableKey: "tender_award_review" },
  tenderTedNotice: { route: "/tender-ted-notices", tableKey: "tender_ted_notice" },
  tenderLane: { route: "/tender-lanes", tableKey: "tender_lane" },
  tenderLot: { route: "/tender-lots", tableKey: "tender_lot" },
  tenderRound: { route: "/tender-rounds", tableKey: "tender_round" },
  tenderQuote: { route: "/tender-quotes", tableKey: "tender_quote" },
  tender: { route: "/tenders", tableKey: "tender" },
  airFreight: { route: "/air", tableKey: "air_freight" },
  groupageLines: { route: "/groupage", tableKey: "groupage_line" },
  groupageTariff: { route: "/groupage-tariffs", tableKey: "groupage_tariff" },
  shipmentPackage: { route: "/shipment-packages", tableKey: "shipment_package" },
  dockAppointment: { route: "/dock-appointments", tableKey: "dock_appointment" },
  codInstruction: { route: "/cod", tableKey: "cod_instruction" },
  sanctions: { route: "/sanctions", tableKey: "sanctions" },
  fraudFlag: { route: "/fraud", tableKey: "fraud_flag" },
  gdpr: { route: "/gdpr", tableKey: "gdpr" },
  aiCopilot: { route: "/ai", tableKey: "ai_copilot" },
  observability: { route: "/health", tableKey: "observability" },
  extractionQuality: { route: "/quality", tableKey: "extraction_quality" },
  tenantRollout: { route: "/rollout", tableKey: "tenant_rollout" },
  mailIntegration: { route: "/mail", tableKey: "mail_integration" },
  operatorNotice: { route: "/notifications", tableKey: "operator_notice" },
  shipment: { route: "/shipments", tableKey: "shipment" },
  tracking: { route: "/tracking", tableKey: "tracking" },
  operationalException: { route: "/exceptions", tableKey: "operational_exception" },
  cargoClaim: { route: "/claims", tableKey: "cargo_claim" },
  watchtower: { route: "/watchtower", tableKey: "watchtower" },
  shipmentDocument: { route: "/shipment-documents", tableKey: "shipment_document" },
  ediMessage: { route: "/edi", tableKey: "edi_message" },
  ports: { route: "/ports", tableKey: "ports" },
  portSurcharges: { route: "/port-surcharges", tableKey: "port_surcharges" },
  locations: { route: "/locations", tableKey: "locations" },
  terminals: { route: "/terminals", tableKey: "terminals" },
  parties: { route: "/parties", tableKey: "parties" },
  partyScorecards: { route: "/party-scorecards", tableKey: "party_scorecards" },
  customerSops: { route: "/customer-sops", tableKey: "customer_sops" },
  creditReviews: { route: "/credit-reviews", tableKey: "credit_reviews" },
  operatorDecisions: { route: "/decisions", tableKey: "operator_decisions" },
  outboxEvents: { route: "/outbox", tableKey: "outbox_events" },
  entityEvents: { route: "/entity-events", tableKey: "entity_events" },
} as const

export const REQUIRED_BUSINESS_LIST_ROUTES = [
  "/tenancy/users",
  "/charge-codes",
  "/commodity-codes",
  "/dangerous-goods",
  "/networks",
  "/nbp-rates",
  "/rate-lines",
  "/charges",
  "/channel-quotes",
  "/quotations",
  "/organization-settings",
  "/extractions",
  "/finance",
  "/invoices",
  "/quote-invoices",
  "/payments",
  "/money-cost",
  "/fx-differences",
  "/cashflows",
  "/cost-to-serve",
  "/bookkeeping",
  "/road",
  "/rail",
  "/china-rail",
  "/lcl",
  "/ocean-bills",
  "/pallet-balances",
  "/document-templates",
  "/rate-cards",
  "/charge-templates",
  "/fuel-indexes",
  "/local-charges",
  "/tender-data-rooms",
  "/tender-matrix-cells",
  "/tender-playbooks",
  "/tender-win-losses",
  "/tender-consortium-members",
  "/tender-rfp-intakes",
  "/tender-prospects",
  "/tender-bid-stances",
  "/tender-carbon-marks",
  "/lane-patterns",
  "/kreptd-licences",
  "/monitoring-schemes",
  "/tender-award-reviews",
  "/tender-ted-notices",
  "/tender-lanes",
  "/tender-lots",
  "/tender-rounds",
  "/tender-quotes",
  "/tenders",
  "/air",
  "/groupage",
  "/groupage-tariffs",
  "/shipment-packages",
  "/dock-appointments",
  "/cod",
  "/sanctions",
  "/fraud",
  "/gdpr",
  "/ai",
  "/health",
  "/quality",
  "/rollout",
  "/mail",
  "/notifications",
  "/shipments",
  "/tracking",
  "/exceptions",
  "/claims",
  "/watchtower",
  "/shipment-documents",
  "/edi",
  "/ports",
  "/port-surcharges",
  "/locations",
  "/terminals",
  "/parties",
  "/party-scorecards",
  "/customer-sops",
  "/credit-reviews",
  "/decisions",
  "/outbox",
  "/entity-events",
] as const

export function businessListRoutes(): string[] {
  return Object.values(BUSINESS_LISTS).map((list) => list.route)
}

export function businessListTableKeys(): string[] {
  return Object.values(BUSINESS_LISTS).map((list) => list.tableKey)
}
